Repository MCreator/MCreator, pull requests merged in 2020-12, with the labels that each got.

#602 Added hoe to "Block destroy tool" and fixed minor bug with replaceable blocks
  plugins/generator-1.15.2/forge-1.15.2/templates/block.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/plant.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/block.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/plant.java.ftl
  src/main/java/net/mcreator/ui/init/BlockItemIcons.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: bug, new feature

#616 Added empty bucket dependency to "Bucket filled" trigger
  plugins/generator-1.15.2/forge-1.15.2/triggers/bucket_filled.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/triggers/bucket_filled.java.ftl
  plugins/mcreator-core/triggers/bucket_filled.json
Labels: new feature

#622 Fixing 2 typo in Potions tooltip
  plugins/mcreator-localization/help/default/potion/display_name.md
  plugins/mcreator-localization/help/default/potion/icon.md
Labels: bug

#651 Improvements to "Block direction" and "Item in armor slot" procedure blocks
  plugins/generator-1.15.2/forge-1.15.2/procedures/block_set_direction.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/entity_get_armor_slot_item.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/entity_set_armor_slot_item.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/world_data_block_direction_at.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/block_set_direction.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/entity_get_armor_slot_item.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/entity_set_armor_slot_item.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/world_data_block_direction_at.java.ftl
  plugins/mcreator-core/procedures/entity_get_armor_slot_item.json
  plugins/mcreator-core/procedures/entity_set_armor_slot_item.json
Labels: new feature

#671 Added tag injection tool
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/MainMenuBar.java
  src/main/java/net/mcreator/ui/MainToolBar.java
  src/main/java/net/mcreator/ui/action/ActionRegistry.java
  src/main/java/net/mcreator/ui/dialogs/tools/InjectTagsTool.java
  src/main/resources/net/mcreator/ui/res/16px/injecttags.png
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#679 Fix #678
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/fv15/DimensionPortalSelectedFixer.java
  src/main/java/net/mcreator/ui/modgui/DimensionGUI.java
  src/main/java/net/mcreator/workspace/elements/ModElement.java
Labels: bug

#617 Added mode parameter to "Explode" procedure block
  plugins/generator-1.15.2/forge-1.15.2/procedures/explode.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/explode.java.ftl
  plugins/mcreator-core/procedures/explode.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#560 Added "disable_local_variables" for Blockly statements and general wait procedure block
  plugins/generator-1.15.2/forge-1.15.2/procedures/wait.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/wait.java.ftl
  plugins/mcreator-core/procedures/wait.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/BlocklyToCode.java
  src/main/java/net/mcreator/blockly/data/StatementInput.java
  src/main/java/net/mcreator/blockly/java/blocks/GetVariableBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/SetVariableBlock.java
Labels: new feature

#692 [Recovered PR] Added "disable_local_variables" for Blockly statements and general wait
  plugins/generator-1.15.2/forge-1.15.2/procedures/wait.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/procedures/wait.java.ftl
  plugins/mcreator-core/procedures/wait.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/BlocklyToCode.java
  src/main/java/net/mcreator/blockly/data/StatementInput.java
  src/main/java/net/mcreator/blockly/data/ToolboxBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/GetVariableBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/SetVariableBlock.java
  src/main/java/net/mcreator/generator/blockly/BlocklyBlockCodeGenerator.java
Labels: new feature

#639 Add "isImmuneToFire" option to Item and Tool mod elements
  plugins/generator-1.16.4/forge-1.16.4/templates/item.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/tool.java.ftl
  plugins/mcreator-localization/help/default/item/immune_to_fire.md
  plugins/mcreator-localization/help/fr_FR/item/immune_to_fire.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/element/types/Tool.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/main/java/net/mcreator/ui/modgui/ToolGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#690 Ported item event triggers to food element
  plugins/generator-1.15.2/forge-1.15.2/templates/food.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/food.java.ftl
  src/main/java/net/mcreator/element/types/Food.java
  src/main/java/net/mcreator/ui/modgui/FoodGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#710 Fixed explode procedure mode always defaulting to "BREAK"
  plugins/mcreator-core/procedures/explode.json
Labels: bug

#705 Sounds and Particle for Biome Ambience - 1.16.4
  plugins/generator-1.16.4/forge-1.16.4/templates/biome.java.ftl
  plugins/mcreator-localization/help/default/biome/additions_sound.md
  plugins/mcreator-localization/help/default/biome/ambient_sound.md
  plugins/mcreator-localization/help/default/biome/mood_sound.md
  plugins/mcreator-localization/help/default/biome/mood_sound_delay.md
  plugins/mcreator-localization/help/default/biome/music.md
  plugins/mcreator-localization/help/default/biome/particle_probability.md
  plugins/mcreator-localization/help/default/biome/particle_type.md
  plugins/mcreator-localization/help/default/biome/spawn_particle.md
  plugins/mcreator-localization/help/default/item/immune_to_fire.md
  plugins/mcreator-localization/help/fr_FR/biome/additions_sound.md
  plugins/mcreator-localization/help/fr_FR/biome/ambient_sound.md
  plugins/mcreator-localization/help/fr_FR/biome/mood_sound.md
  plugins/mcreator-localization/help/fr_FR/biome/mood_sound_delay.md
  plugins/mcreator-localization/help/fr_FR/biome/music.md
  plugins/mcreator-localization/help/fr_FR/biome/particle_effect.md
  plugins/mcreator-localization/help/fr_FR/biome/particle_probability.md
  plugins/mcreator-localization/help/fr_FR/biome/spawn_particle.md
  plugins/mcreator-localization/help/fr_FR/item/immune_to_fire.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Biome.java
  src/main/java/net/mcreator/ui/minecraft/SoundSelector.java
  src/main/java/net/mcreator/ui/modgui/BiomeGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature
