Repository MCreator/MCreator, pull requests merged in 2021-10, with the labels that each got.

#1805 Added support for hex color codes in toolbox categories
  src/main/java/net/mcreator/blockly/data/ToolboxCategory.java
Labels: new feature

#1812 Fixed some issues with join text block and parentheses removal
  src/main/java/net/mcreator/blockly/java/ProcedureCodeOptimizer.java
  src/main/java/net/mcreator/blockly/java/blocks/TextJoinBlock.java
Labels: bug

#1818 Fix water entities
  plugins/generator-1.16.5/forge-1.16.5/templates/livingentity.java.ftl
Labels: bug

#1943 Fix #1942
  plugins/generator-1.16.5/forge-1.16.5/templates/block.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/dimension/portaltrigger.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/food.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/item.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/livingentity.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/musicdisc.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/plant.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/tool.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/utils/procedures.java.ftl
  plugins/generator-1.17.1/forge-1.17.1/templates/block/block.java.ftl
  plugins/generator-1.17.1/forge-1.17.1/templates/dimension/portaltrigger.java.ftl
  plugins/generator-1.17.1/forge-1.17.1/templates/item/item.java.ftl
  plugins/generator-1.17.1/forge-1.17.1/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.17.1/forge-1.17.1/utils/procedures.java.ftl
  plugins/generator-1.17.1/forge-1.17.1/utils/triggers.java.ftl
  src/main/java/net/mcreator/element/parts/Procedure.java
Labels: bug

#1944 Fixed issue with logic binary block
  src/main/java/net/mcreator/blockly/java/blocks/BinaryOperationsBlock.java
Labels: bug

#1947 1.17 Item Textures
  plugins/mcreator-core/datalists/blocksitems.yaml
  plugins/mcreator-core/datalists/icons/AMETHYST_SHARD.png
  plugins/mcreator-core/datalists/icons/AXOLOTL_BUCKET.png
  plugins/mcreator-core/datalists/icons/AXOLOTL_SPAWN_EGG.png
  plugins/mcreator-core/datalists/icons/BUNDLE.png
  plugins/mcreator-core/datalists/icons/COPPER_INGOT.png
  plugins/mcreator-core/datalists/icons/GLOW_BERRIES.png
  plugins/mcreator-core/datalists/icons/GLOW_INK_SAC.png
  plugins/mcreator-core/datalists/icons/GLOW_ITEM_FRAME.png
  plugins/mcreator-core/datalists/icons/GLOW_SQUID_SPAWN_EGG.png
  plugins/mcreator-core/datalists/icons/GOAT_SPAWN_EGG.png
  plugins/mcreator-core/datalists/icons/POWDER_SNOW_BUCKET.png
  plugins/mcreator-core/datalists/icons/RAW_COPPER.png
  plugins/mcreator-core/datalists/icons/RAW_GOLD.png
  plugins/mcreator-core/datalists/icons/RAW_IRON.png
  plugins/mcreator-core/datalists/icons/SPYGLASS.png
Labels: official
