Repository MCreator/MCreator, pull requests merged in 2021-05, with the labels that each got.

#1212 Set text inside a text field procedure block
  plugins/generator-1.15.2/forge-1.15.2/procedures/gui_set_text_textfield.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/gui_set_text_textfield.java.ftl
  plugins/mcreator-core/procedures/gui_set_text_textfield.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#1184 Add a plugin update checker
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/plugin/PluginInfo.java
  src/main/java/net/mcreator/plugin/PluginLoader.java
  src/main/java/net/mcreator/plugin/PluginUpdateInfo.java
  src/main/java/net/mcreator/preferences/PreferencesData.java
  src/main/java/net/mcreator/ui/MCreatorApplication.java
  src/main/java/net/mcreator/ui/dialogs/UpdatePluginDialog.java
Labels: new feature

#1213 Migration to Java 11
  .idea/.name
  .idea/compiler.xml
  .idea/misc.xml
  .travis.yml
  build.gradle
  lib/blockly.jar
  platform/linux/linux.gradle
  platform/mac/mac.gradle
  platform/setup.gradle
  platform/windows/installer/install.nsi
  platform/windows/windows.gradle
  plugins/generator-addon-1.16.x/addon-1.16.x/workspacebase/gradle/wrapper/gradle-wrapper.jar
  plugins/generator-addon-1.16.x/addon-1.16.x/workspacebase/gradle/wrapper/gradle-wrapper.properties
  plugins/generator-datapack-1.15.x/datapack-1.15.x/workspacebase/gradle/wrapper/gradle-wrapper.jar
  plugins/generator-datapack-1.15.x/datapack-1.15.x/workspacebase/gradle/wrapper/gradle-wrapper.properties
  plugins/generator-datapack-1.16.x/datapack-1.16.x/workspacebase/gradle/wrapper/gradle-wrapper.jar
  plugins/generator-datapack-1.16.x/datapack-1.16.x/workspacebase/gradle/wrapper/gradle-wrapper.properties
  src/main/java/net/mcreator/Launcher.java
  src/main/java/net/mcreator/io/FileIO.java
  src/main/java/net/mcreator/java/ImportTreeBuilder.java
  src/main/java/net/mcreator/java/JModLibraryInfo.java
  src/main/java/net/mcreator/java/ProjectJarManager.java
  src/main/java/net/mcreator/ui/MCreator.java
  src/main/java/net/mcreator/ui/MCreatorApplication.java
  src/main/java/net/mcreator/ui/TaskbarIntegration.java
  src/main/java/net/mcreator/ui/action/AcceleratorDialog.java
  src/main/java/net/mcreator/ui/action/AcceleratorMap.java
  src/main/java/net/mcreator/ui/blockly/BlocklyPanel.java
  src/main/java/net/mcreator/ui/blockly/WebConsoleListener.java
  src/main/java/net/mcreator/ui/component/JSelectableListMouseListenerWithDND.java
  src/main/java/net/mcreator/ui/component/ListGroup.java
  src/main/java/net/mcreator/ui/component/util/MacOSUIUtil.java
  src/main/java/net/mcreator/ui/component/util/ThreadUtil.java
  src/main/java/net/mcreator/ui/component/zoompane/JZoomport.java
  src/main/java/net/mcreator/ui/component/zoompane/ZoomedMouseEvent.java
  src/main/java/net/mcreator/ui/component/zoompane/ZoomedMouseWheelEvent.java
  src/main/java/net/mcreator/ui/dialogs/ProgressDialog.java
  src/main/java/net/mcreator/ui/gradle/GradleConsole.java
  src/main/java/net/mcreator/ui/ide/CodeEditorView.java
  src/main/java/net/mcreator/ui/ide/RSyntaxTextAreaStyler.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYG.java
  src/main/java/net/mcreator/util/DesktopUtils.java
  src/main/resources/blockly/blockly.html
  src/test/java/net/mcreator/integration/TestSetup.java
Labels: new feature, official

#1262 Fix missing and broken gamerule tests
  src/main/java/net/mcreator/element/types/GameRule.java
  src/main/java/net/mcreator/ui/modgui/GameRuleGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: bug

#1258 Fix for plant placement/grow condition
  plugins/generator-1.15.2/forge-1.15.2/templates/plant.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/plant.java.ftl
Labels: bug

#1063 Move default entity animations to plugins
  plugins/mcreator-core/templates/animations/Constant X axis rotation.json
  plugins/mcreator-core/templates/animations/Constant Y axis rotation.json
  plugins/mcreator-core/templates/animations/Constant Z axis rotation.json
  plugins/mcreator-core/templates/animations/Constant slow Y axis rotation.json
  plugins/mcreator-core/templates/animations/Constant slow Z axis rotation.json
  plugins/mcreator-core/templates/animations/Constant slow x rotation.json
  plugins/mcreator-core/templates/animations/Head movement animation.json
  plugins/mcreator-core/templates/animations/Left arm swing animation (Y axis).json
  plugins/mcreator-core/templates/animations/Left arm swing animation (Z axis).json
  plugins/mcreator-core/templates/animations/Left arm swing animation.json
  plugins/mcreator-core/templates/animations/Left leg swing animation (Y axis).json
  plugins/mcreator-core/templates/animations/Left leg swing animation (Z axis).json
  plugins/mcreator-core/templates/animations/Left leg swing animation.json
  plugins/mcreator-core/templates/animations/Right arm swing animation (Y axis).json
  plugins/mcreator-core/templates/animations/Right arm swing animation (Z axis).json
  plugins/mcreator-core/templates/animations/Right arm swing animation.json
  plugins/mcreator-core/templates/animations/Right leg swing animation (Y axis).json
  plugins/mcreator-core/templates/animations/Right leg swing animation (Z axis).json
  plugins/mcreator-core/templates/animations/Right leg swing animation.json
  plugins/mcreator-core/templates/animations/Rotate X axis from head pitch.json
  plugins/mcreator-core/templates/animations/Rotate X axis from head yaw.json
  plugins/mcreator-core/templates/animations/Rotate Y axis from head pitch.json
  plugins/mcreator-core/templates/animations/Rotate Y axis from head yaw.json
  plugins/mcreator-core/templates/animations/Rotate Z axis from head pitch.json
  plugins/mcreator-core/templates/animations/Rotate Z axis from head yaw.json
  src/main/java/net/mcreator/ui/MCreatorApplication.java
  src/main/java/net/mcreator/ui/dialogs/JavaModelAnimationEditorDialog.java
  src/main/java/net/mcreator/ui/init/EntityAnimationsLoader.java
  src/test/java/net/mcreator/integration/TestSetup.java
Labels: new feature

#981 Placing condition for blocks and "Is valid position" procedure block
  plugins/generator-1.15.2/forge-1.15.2/procedures/block_is_valid_position.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/block.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/block_is_valid_position.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/block.java.ftl
  plugins/mcreator-core/procedures/block_is_valid_position.json
  plugins/mcreator-localization/help/default/block/placing_condition.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#1126 Right-click mod element features
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
Labels: new feature

#943 Ported some block properties to fluids
  plugins/generator-1.15.2/forge-1.15.2/templates/fluid.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/fluid.java.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Fluid.java
  src/main/java/net/mcreator/ui/modgui/FluidGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#1289 Added a way to filter multiple things at once
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
Labels: new feature

#1307 Fix blockly editor charset
  src/main/java/net/mcreator/ui/blockly/BlocklyPanel.java
Labels: bug

#1304 Save grid settings for GUI and Overlay
  src/main/java/net/mcreator/element/parts/GridSettings.java
  src/main/java/net/mcreator/element/types/GUI.java
  src/main/java/net/mcreator/element/types/Overlay.java
  src/main/java/net/mcreator/ui/modgui/CustomGUIGUI.java
  src/main/java/net/mcreator/ui/modgui/OverlayGUI.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYG.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYGEditor.java
Labels: new feature

#1067 Custom MCreator UI themes
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/fluidbucket.png
  plugins/mcreator-themes/themes/default_dark/styles/blockly.css
  plugins/mcreator-themes/themes/default_dark/styles/code_editor.xml
  plugins/mcreator-themes/themes/default_dark/theme.json
  plugins/mcreator-themes/themes/default_light/styles/blockly.css
  plugins/mcreator-themes/themes/default_light/styles/code_editor.xml
  plugins/mcreator-themes/themes/default_light/theme.json
  src/main/java/net/mcreator/generator/Generator.java
  src/main/java/net/mcreator/preferences/PreferencesData.java
  src/main/java/net/mcreator/themes/ColorScheme.java
  src/main/java/net/mcreator/themes/Theme.java
  src/main/java/net/mcreator/themes/ThemeLoader.java
  src/main/java/net/mcreator/ui/MCreator.java
  src/main/java/net/mcreator/ui/MCreatorApplication.java
  src/main/java/net/mcreator/ui/MainMenuBar.java
  src/main/java/net/mcreator/ui/SplashScreen.java
  src/main/java/net/mcreator/ui/TaskbarIntegration.java
  src/main/java/net/mcreator/ui/action/impl/AboutAction.java
  src/main/java/net/mcreator/ui/action/impl/workspace/ExportWorkspaceForDistAction.java
  src/main/java/net/mcreator/ui/blockly/BlocklyPanel.java
  src/main/java/net/mcreator/ui/component/ConsolePane.java
  src/main/java/net/mcreator/ui/dialogs/MCItemSelectorDialog.java
  src/main/java/net/mcreator/ui/dialogs/MCreatorDialog.java
  src/main/java/net/mcreator/ui/dialogs/TextureSelectorDialog.java
  src/main/java/net/mcreator/ui/dialogs/UpdateNotifyDialog.java
  src/main/java/net/mcreator/ui/dialogs/preferences/PluginsPanel.java
  src/main/java/net/mcreator/ui/dialogs/preferences/PreferencesDialog.java
  src/main/java/net/mcreator/ui/dialogs/preferences/ThemesPanel.java
  src/main/java/net/mcreator/ui/ide/RSyntaxTextAreaStyler.java
  src/main/java/net/mcreator/ui/init/UIRES.java
  src/main/java/net/mcreator/ui/laf/DarkMCreatorTheme.java
  src/main/java/net/mcreator/ui/laf/LightMCreatorTheme.java
  src/main/java/net/mcreator/ui/laf/MCreatorLookAndFeel.java
  src/main/java/net/mcreator/ui/laf/MCreatorTheme.java
  src/main/java/net/mcreator/ui/laf/renderer/LargeIconModListRender.java
  src/main/java/net/mcreator/ui/laf/renderer/ListIconModListRender.java
  src/main/java/net/mcreator/ui/laf/renderer/MinecraftCompletionCellRenderer.java
  src/main/java/net/mcreator/ui/laf/renderer/SmallIconModListRender.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelSounds.java
  src/main/java/net/mcreator/ui/workspace/selector/RecentWorkspacesRenderer.java
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYG.java
  src/main/resources/net/mcreator/ui/res/fallback.png
  src/main/resources/net/mcreator/ui/res/icon.ico
  src/main/resources/net/mcreator/ui/res/icon.png
  src/test/java/net/mcreator/integration/TestSetup.java
Labels: new feature

#1338 Added previews for some block bases
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/minecraft/MinecraftImageGenerator.java
  src/main/java/net/mcreator/util/image/ImageUtils.java
Labels: new feature

#1315 Added some fluid bucket properties and fixed issues with fluid localization
  plugins/generator-1.15.2/forge-1.15.2/fluid.definition.yaml
  plugins/generator-1.15.2/forge-1.15.2/templates/fluid.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/bucket.json.ftl
  plugins/generator-1.16.5/forge-1.16.5/fluid.definition.yaml
  plugins/generator-1.16.5/forge-1.16.5/templates/fluid.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/json/bucket.json.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/fv20/FluidNameFixer.java
  src/main/java/net/mcreator/element/types/Fluid.java
  src/main/java/net/mcreator/ui/modgui/FluidGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: bug, new feature

#1340 Option to open configuration folders from MCreator
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/dialogs/preferences/EditTemplatesPanel.java
  src/main/java/net/mcreator/ui/dialogs/preferences/PluginsPanel.java
Labels: new feature

#1342 Field exclusions for definition files
  src/main/java/net/mcreator/generator/GeneratorConfiguration.java
  src/main/java/net/mcreator/ui/component/UnsupportedComponent.java
  src/main/java/net/mcreator/ui/modgui/ModElementGUI.java
Labels: new feature

#1347 New theme features
  plugins/mcreator-themes/themes/default_dark/styles/console_font.ttf
  plugins/mcreator-themes/themes/default_dark/styles/secondary_font.ttf
  src/main/java/net/mcreator/themes/ColorScheme.java
  src/main/java/net/mcreator/themes/Theme.java
  src/main/java/net/mcreator/ui/laf/MCreatorLookAndFeel.java
  src/main/java/net/mcreator/ui/laf/MCreatorTheme.java
  src/main/java/net/mcreator/ui/laf/renderer/LargeIconModListRender.java
  src/main/java/net/mcreator/ui/laf/renderer/ListIconModListRender.java
  src/main/java/net/mcreator/ui/laf/renderer/SmallIconModListRender.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelSounds.java
  src/main/java/net/mcreator/ui/workspace/selector/RecentWorkspacesRenderer.java
Labels: new feature
