Repository MCreator/MCreator, pull requests merged in 2021-12, with the labels that each got.

#2096 Update splash.png for the next release
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official

#2073 [1.18] Data lists
  plugins/mcreator-core/datalists/achievements.yaml
  plugins/mcreator-core/datalists/biomes.yaml
  plugins/mcreator-core/datalists/blocksitems.yaml
  plugins/mcreator-core/datalists/defaultfeatures.yaml
  plugins/mcreator-core/datalists/mobspawntypes.yaml
  plugins/mcreator-core/datalists/screens.yaml
  plugins/mcreator-core/datalists/sounds.yaml
Labels: new feature

#2079 [1.18] Forge mappings
  plugins/generator-1.18/forge-1.18/mappings/achievements.yaml
  plugins/generator-1.18/forge-1.18/mappings/biomedictionarytypes.yaml
  plugins/generator-1.18/forge-1.18/mappings/biomes.yaml
  plugins/generator-1.18/forge-1.18/mappings/blocksitems.yaml
  plugins/generator-1.18/forge-1.18/mappings/damagesources.yaml
  plugins/generator-1.18/forge-1.18/mappings/defaultfeatures.yaml
  plugins/generator-1.18/forge-1.18/mappings/directions.yaml
  plugins/generator-1.18/forge-1.18/mappings/effects.yaml
  plugins/generator-1.18/forge-1.18/mappings/enchantments.yaml
  plugins/generator-1.18/forge-1.18/mappings/enchantmenttypes.yaml
  plugins/generator-1.18/forge-1.18/mappings/entities.yaml
  plugins/generator-1.18/forge-1.18/mappings/fluids.yaml
  plugins/generator-1.18/forge-1.18/mappings/gamemodes.yaml
  plugins/generator-1.18/forge-1.18/mappings/gamerules.yaml
  plugins/generator-1.18/forge-1.18/mappings/keybuttons.yaml
  plugins/generator-1.18/forge-1.18/mappings/mapcolors.yaml
  plugins/generator-1.18/forge-1.18/mappings/materials.yaml
  plugins/generator-1.18/forge-1.18/mappings/mobspawntypes.yaml
  plugins/generator-1.18/forge-1.18/mappings/particles.yaml
  plugins/generator-1.18/forge-1.18/mappings/pathnodetypes.yaml
  plugins/generator-1.18/forge-1.18/mappings/planttypes.yaml
  plugins/generator-1.18/forge-1.18/mappings/potions.yaml
  plugins/generator-1.18/forge-1.18/mappings/screens.yaml
  plugins/generator-1.18/forge-1.18/mappings/soundcategories.yaml
  plugins/generator-1.18/forge-1.18/mappings/sounds.yaml
  plugins/generator-1.18/forge-1.18/mappings/stepsounds.yaml
  plugins/generator-1.18/forge-1.18/mappings/tabs.yaml
Labels: new feature

#2104 Add missing 1.18 texture
  plugins/mcreator-core/datalists/icons/MUSIC_DISC_OTHERSIDE.png
Labels: new feature, official

#2116 Update Log4j to 2.15
  build.gradle
Labels: bug, dependencies

#2094 Mod element GUI fixes
  src/main/java/net/mcreator/ui/minecraft/JEntriesList.java
  src/main/java/net/mcreator/ui/minecraft/MCItemHolder.java
  src/main/java/net/mcreator/ui/minecraft/boundingboxes/JBoundingBoxEntry.java
  src/main/java/net/mcreator/ui/minecraft/boundingboxes/JBoundingBoxList.java
  src/main/java/net/mcreator/ui/minecraft/potions/JPotionList.java
  src/main/java/net/mcreator/ui/minecraft/potions/JPotionListEntry.java
  src/main/java/net/mcreator/ui/minecraft/spawntypes/JSpawnEntriesList.java
  src/main/java/net/mcreator/ui/minecraft/spawntypes/JSpawnListEntry.java
  src/main/java/net/mcreator/ui/modgui/BiomeGUI.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/main/java/net/mcreator/ui/modgui/PotionGUI.java
  src/main/java/net/mcreator/ui/modgui/codeviewer/ModElementCodeViewer.java
Labels: bug

#2122 Fix #2112
  plugins/generator-1.17.1/forge-1.17.1/jsontriggers/block_placed.json.ftl
  plugins/generator-1.17.1/forge-1.17.1/jsontriggers/item_consumed.json.ftl
  plugins/generator-1.17.1/forge-1.17.1/jsontriggers/item_damaged.json.ftl
  plugins/generator-1.17.1/forge-1.17.1/jsontriggers/item_in_inventory.json.ftl
  plugins/generator-datapack-1.17.x/datapack-1.17.x/jsontriggers/block_placed.json.ftl
  plugins/generator-datapack-1.17.x/datapack-1.17.x/jsontriggers/item_consumed.json.ftl
  plugins/generator-datapack-1.17.x/datapack-1.17.x/jsontriggers/item_damaged.json.ftl
  plugins/generator-datapack-1.17.x/datapack-1.17.x/jsontriggers/item_in_inventory.json.ftl
Labels: bug

#2138 [1.17.1] End dimensions invert values of imitate overworld
  plugins/generator-1.17.1/forge-1.17.1/templates/json/dimension/dimension_end.json.ftl
  plugins/generator-1.17.1/forge-1.17.1/templates/json/dimension/dimension_nether.json.ftl
  plugins/generator-datapack-1.17.x/datapack-1.17.x/templates/dimension/dimension_end.json.ftl
  plugins/generator-datapack-1.17.x/datapack-1.17.x/templates/dimension/dimension_nether.json.ftl
Labels: bug

#2146 Code preview generator fix
  src/main/java/net/mcreator/ui/modgui/codeviewer/ModElementCodeViewer.java
Labels: bug

#2169 [Bug] Apply ProcedureVariablesConverter to procedure templates
  src/main/java/net/mcreator/blockly/java/ProcedureTemplateIO.java
Labels: bug
