Repository MCreator/MCreator, pull requests merged in 2021-03, with the labels that each got.

#922 Angular velocity and acceleration for particles
  plugins/generator-1.15.2/forge-1.15.2/templates/particle.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/particle.java.ftl
  plugins/mcreator-localization/help/default/particle/angular_acceleration.md
  plugins/mcreator-localization/help/default/particle/angular_velocity.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Particle.java
  src/main/java/net/mcreator/ui/modgui/ParticleGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#899 Speed and jump factors for blocks
  plugins/generator-1.15.2/forge-1.15.2/templates/block.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/plant.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/block.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/plant.java.ftl
  plugins/mcreator-localization/help/default/block/jump_factor.md
  plugins/mcreator-localization/help/default/block/speed_factor.md
  plugins/mcreator-localization/help/fr_FR/block/jump_factor.md
  plugins/mcreator-localization/help/fr_FR/block/speed_factor.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#877 PlantGUI refont + new plant option to grow on
  plugins/generator-1.15.2/forge-1.15.2/templates/plant.java.ftl
  plugins/generator-1.16.4/forge-1.16.4/templates/plant.java.ftl
  plugins/mcreator-localization/help/default/plant/can_be_placed_on.md
  plugins/mcreator-localization/help/default/plant/placing_condition.md
  plugins/mcreator-localization/help/fr_FR/plant/can_be_placed_on.md
  plugins/mcreator-localization/help/fr_FR/plant/placing_condition.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#985 Validators should skip validation if the component is disabled
  src/main/java/net/mcreator/ui/component/JItemListField.java
  src/main/java/net/mcreator/ui/dialogs/workspace/AbstractWorkspacePanel.java
  src/main/java/net/mcreator/ui/dialogs/workspace/WorkspaceDialogs.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/InputSlotDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/OutputSlotDialog.java
  src/main/java/net/mcreator/ui/minecraft/MCItemHolder.java
  src/main/java/net/mcreator/ui/modgui/ArmorGUI.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/main/java/net/mcreator/ui/modgui/PaintingGUI.java
  src/main/java/net/mcreator/ui/modgui/ParticleGUI.java
  src/main/java/net/mcreator/ui/modgui/PotionGUI.java
  src/main/java/net/mcreator/ui/modgui/RangedItemGUI.java
  src/main/java/net/mcreator/ui/validation/AggregatedValidationResult.java
  src/main/java/net/mcreator/ui/validation/IValidable.java
  src/main/java/net/mcreator/ui/validation/ValidationGroup.java
  src/main/java/net/mcreator/ui/validation/Validator.java
  src/main/java/net/mcreator/ui/validation/component/VButton.java
  src/main/java/net/mcreator/ui/validation/component/VComboBox.java
  src/main/java/net/mcreator/ui/validation/component/VTextField.java
  src/main/java/net/mcreator/ui/validation/validators/CommaSeparatedNumbersValidator.java
  src/main/java/net/mcreator/ui/validation/validators/JavaMemeberNameValidator.java
  src/main/java/net/mcreator/ui/validation/validators/MCItemHolderValidator.java
  src/main/java/net/mcreator/ui/validation/validators/RegistryNameValidator.java
  src/main/java/net/mcreator/ui/validation/validators/TextFieldValidator.java
  src/main/java/net/mcreator/ui/validation/validators/TileHolderValidator.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
Labels: bug

#989 Minor fixes to class finder for the code editor
  src/main/java/net/mcreator/java/ClassFinder.java
  src/main/java/net/mcreator/java/DeclarationFinder.java
Labels: bug

#961 Added display name to Gamerule
  plugins/generator-1.15.2/forge-1.15.2/gamerule.definition.yaml
  plugins/generator-1.16.4/forge-1.16.4/gamerule.definition.yaml
  plugins/mcreator-localization/help/default/gamerule/description.md
  plugins/mcreator-localization/help/default/gamerule/display_name.md
  plugins/mcreator-localization/help/fr_FR/gamerule/display_name.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/fv17/GameruleDisplayNameFixer.java
  src/main/java/net/mcreator/element/types/GameRule.java
  src/main/java/net/mcreator/ui/modgui/GameRuleGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#1059 Add FrozenTopLayer to default features
  plugins/generator-1.15.2/forge-1.15.2/mappings/defaultfeatures.yaml
  plugins/generator-1.16.5/forge-1.16.5/mappings/defaultfeatures.yaml
  plugins/mcreator-core/datalists/defaultfeatures.yaml
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/fv18/BiomeFrozenTopLayerConverter.java
  src/main/java/net/mcreator/ui/modgui/BiomeGUI.java
Labels: bug, new feature
