Repository MCreator/MCreator, pull requests merged in 2021-08, with the labels that each got.

#1583 Tick condition for potion effects
  plugins/generator-1.15.2/forge-1.15.2/templates/potioneffect.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/potioneffect.java.ftl
  plugins/mcreator-core/templates/ptpl/Poison-like effect tick condition.ptpl
  plugins/mcreator-localization/help/default/potioneffect/active_tick_condition.md
  plugins/mcreator-localization/help/fr_FR/potioneffect/active_tick_condition.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/PotionEffect.java
  src/main/java/net/mcreator/ui/modgui/PotionEffectGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#1501 Added support for potions in custom brewing recipes
  plugins/generator-1.15.2/forge-1.15.2/mappings/blocksitems.yaml
  plugins/generator-1.15.2/forge-1.15.2/mappings/potions.yaml
  plugins/generator-1.15.2/forge-1.15.2/templates/brewingrecipe.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/mappings/blocksitems.yaml
  plugins/generator-1.16.5/forge-1.16.5/mappings/potions.yaml
  plugins/generator-1.16.5/forge-1.16.5/templates/brewingrecipe.java.ftl
  plugins/mcreator-core/datalists/potions.yaml
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/minecraft/MCItem.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/main/java/net/mcreator/ui/datapack/recipe/BrewingRecipeMaker.java
  src/main/java/net/mcreator/ui/dialogs/MCItemSelectorDialog.java
  src/main/java/net/mcreator/ui/dialogs/workspace/GeneratorSelector.java
  src/main/java/net/mcreator/ui/minecraft/MCItemHolder.java
  src/main/java/net/mcreator/ui/modgui/RecipeGUI.java
  src/main/resources/blockly/js/mcreator_blocks.js
Labels: new feature

#1545 Added some more fluid properties and triggers
  plugins/generator-1.15.2/forge-1.15.2/templates/fluid.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/fluid.java.ftl
  plugins/mcreator-localization/help/default/fluid/before_replacing_block.md
  plugins/mcreator-localization/help/default/fluid/flow_condition.md
  plugins/mcreator-localization/help/default/fluid/flow_strength.md
  plugins/mcreator-localization/help/default/fluid/tint_type.md
  plugins/mcreator-localization/help/fr_FR/fluid/before_replacing_block.md
  plugins/mcreator-localization/help/fr_FR/fluid/flow_condition.md
  plugins/mcreator-localization/help/fr_FR/fluid/flow_strength.md
  plugins/mcreator-localization/help/fr_FR/fluid/tint_type.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Fluid.java
  src/main/java/net/mcreator/ui/modgui/FluidGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#1594 Functions to use readable names in procedure dropdowns
  plugins/mcreator-core/datalists/biomes.yaml
  plugins/mcreator-core/datalists/entities.yaml
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/main/resources/blockly/js/mcreator_blockly.js
  src/main/resources/blockly/js/mcreator_blocks.js
Labels: new feature

#1601 "Is immune to fire" option for armor items
  plugins/generator-1.15.2/forge-1.15.2/armor.definition.yaml
  plugins/generator-1.16.5/forge-1.16.5/templates/armor.java.ftl
  src/main/java/net/mcreator/element/types/Armor.java
  src/main/java/net/mcreator/ui/modgui/ArmorGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#1622 Added dependencies to some block/plant triggers
  plugins/generator-1.15.2/forge-1.15.2/templates/block.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/plant.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/block.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/plant.java.ftl
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/main/java/net/mcreator/ui/procedure/AbstractProcedureSelector.java
Labels: new feature

#1619 Optional entity input for "Get/Set variable" block
  plugins/generator-1.15.2/forge-1.15.2/variables/blockstate.yaml
  plugins/generator-1.15.2/forge-1.15.2/variables/direction.yaml
  plugins/generator-1.15.2/forge-1.15.2/variables/itemstack.yaml
  plugins/generator-1.15.2/forge-1.15.2/variables/logic.yaml
  plugins/generator-1.15.2/forge-1.15.2/variables/number.yaml
  plugins/generator-1.15.2/forge-1.15.2/variables/string.yaml
  plugins/generator-1.16.5/forge-1.16.5/variables/blockstate.yaml
  plugins/generator-1.16.5/forge-1.16.5/variables/direction.yaml
  plugins/generator-1.16.5/forge-1.16.5/variables/itemstack.yaml
  plugins/generator-1.16.5/forge-1.16.5/variables/logic.yaml
  plugins/generator-1.16.5/forge-1.16.5/variables/number.yaml
  plugins/generator-1.16.5/forge-1.16.5/variables/string.yaml
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/java/BlocklyVariables.java
  src/main/java/net/mcreator/blockly/java/blocks/GetVariableBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/SetVariableBlock.java
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/fv24/ProcedureVariablesEntityFixer.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptTemplates.java
  src/main/resources/blockly/js/mcreator_blocks.js
Labels: new feature

#1626 Fix Fabric imports
  src/main/java/net/mcreator/java/ImportFormat.java
Labels: new feature

#1643 Fix procedures that return blockstate values
  plugins/generator-1.15.2/forge-1.15.2/variables/blockstate.yaml
  plugins/generator-1.16.5/forge-1.16.5/variables/blockstate.yaml
Labels: bug

#1655 Fixed compilation error if no dispense procedure is selected
  plugins/generator-1.15.2/forge-1.15.2/templates/item.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/item.java.ftl
Labels: bug

#1549 1.17 data lists
  plugins/mcreator-core/datalists/achievements.yaml
  plugins/mcreator-core/datalists/biomes.yaml
  plugins/mcreator-core/datalists/blocksitems.yaml
  plugins/mcreator-core/datalists/damagesources.yaml
  plugins/mcreator-core/datalists/defaultfeatures.yaml
  plugins/mcreator-core/datalists/entities.yaml
  plugins/mcreator-core/datalists/gamerules.yaml
  plugins/mcreator-core/datalists/mapcolors.yaml
  plugins/mcreator-core/datalists/materials.yaml
  plugins/mcreator-core/datalists/particles.yaml
  plugins/mcreator-core/datalists/pathnodetypes.yaml
  plugins/mcreator-core/datalists/sounds.yaml
  plugins/mcreator-core/datalists/stepsounds.yaml
Labels: new feature

#1680 Add check for idea.project existence before using it
  platform/setup.gradle
Labels: official
