Repository MCreator/MCreator, pull requests merged in 2021-06, with the labels that each got.

#1360 Added shortcuts for the "Get/Set var" and dependency procedure blocks
  src/main/java/net/mcreator/blockly/data/Dependency.java
  src/main/java/net/mcreator/ui/modgui/ProcedureGUI.java
Labels: new feature

#1350 Rename Folder feature
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/laf/renameFolder.gif
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
  src/main/java/net/mcreator/workspace/elements/FolderElement.java
Labels: new feature

#1345 Pressure plate block base
  plugins/generator-1.15.2/forge-1.15.2/block.definition.yaml
  plugins/generator-1.15.2/forge-1.15.2/templates/block.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/pressure_plate.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/pressure_plate_down.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/pressure_plate_item.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/txblock/pressure_plate_states.json.ftl
  plugins/generator-1.16.5/forge-1.16.5/block.definition.yaml
  plugins/generator-1.16.5/forge-1.16.5/templates/block.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/json/txblock/pressure_plate.json.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/json/txblock/pressure_plate_down.json.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/json/txblock/pressure_plate_item.json.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/json/txblock/pressure_plate_states.json.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/minecraft/MinecraftImageGenerator.java
  src/main/java/net/mcreator/ui/dialogs/tools/WoodPackMakerTool.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
Labels: new feature

#1362 Local and global blockstate variables, global direction variables
  plugins/generator-1.15.2/forge-1.15.2/mappings/types.yaml
  plugins/generator-1.15.2/forge-1.15.2/procedures/_procedure_retval.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/_return.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/procedure.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/utils/mcitems.ftl
  plugins/generator-1.15.2/forge-1.15.2/variables/blockstate.yaml
  plugins/generator-1.15.2/forge-1.15.2/variables/direction.yaml
  plugins/generator-1.15.2/forge-1.15.2/variables/itemstack.yaml
  plugins/generator-1.15.2/forge-1.15.2/variables/logic.yaml
  plugins/generator-1.15.2/forge-1.15.2/variables/number.yaml
  plugins/generator-1.15.2/forge-1.15.2/variables/string.yaml
  plugins/generator-1.16.5/forge-1.16.5/mappings/types.yaml
  plugins/generator-1.16.5/forge-1.16.5/procedures/_procedure_retval.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/_return.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/procedure.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/utils/mcitems.ftl
  plugins/generator-1.16.5/forge-1.16.5/variables/blockstate.yaml
  plugins/generator-1.16.5/forge-1.16.5/variables/direction.yaml
  plugins/generator-1.16.5/forge-1.16.5/variables/itemstack.yaml
  plugins/generator-1.16.5/forge-1.16.5/variables/logic.yaml
  plugins/generator-1.16.5/forge-1.16.5/variables/number.yaml
  plugins/generator-1.16.5/forge-1.16.5/variables/string.yaml
  plugins/mcreator-core/variables/blockstate.json
  src/main/java/net/mcreator/blockly/java/BlocklyToProcedure.java
  src/main/java/net/mcreator/blockly/java/BlocklyVariables.java
  src/main/java/net/mcreator/blockly/java/blocks/CustomDependencyBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/GetVariableBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/SetVariableBlock.java
  src/main/java/net/mcreator/element/types/Procedure.java
  src/main/java/net/mcreator/ui/dialogs/NewVariableDialog.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanelVariables.java
  src/main/java/net/mcreator/workspace/elements/VariableTypeLoader.java
Labels: new feature

#1303 Custom sounds new block and plant option
  plugins/generator-1.15.2/forge-1.15.2/templates/block.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/plant.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/block.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/plant.java.ftl
  plugins/mcreator-localization/help/default/biome/particle_probability.md
  plugins/mcreator-localization/help/default/block/break_sound.md
  plugins/mcreator-localization/help/default/block/fall_sound.md
  plugins/mcreator-localization/help/default/block/hit_sound.md
  plugins/mcreator-localization/help/default/block/place_sound.md
  plugins/mcreator-localization/help/default/block/step_sound.md
  plugins/mcreator-localization/help/default/rangeditem/bullet_ignite_fire.md
  plugins/mcreator-localization/help/fr_FR/block/break_sound.md
  plugins/mcreator-localization/help/fr_FR/block/fall_sound.md
  plugins/mcreator-localization/help/fr_FR/block/hit_sound.md
  plugins/mcreator-localization/help/fr_FR/block/place_sound.md
  plugins/mcreator-localization/help/fr_FR/block/step_sound.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#1426 Fixed new mod element registry name label switching to english
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/dialogs/NewModElementDialog.java
Labels: bug

#1240 Add redstone parameters to blocks
  plugins/generator-1.15.2/forge-1.15.2/templates/block.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/utils/procedures.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/block.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/utils/procedures.java.ftl
  plugins/mcreator-localization/help/default/block/emits_redstone.md
  plugins/mcreator-localization/help/default/block/redstone_connect.md
  plugins/mcreator-localization/help/default/block/redstone_power.md
  plugins/mcreator-localization/help/fr_FR/block/emits_redstone.md
  plugins/mcreator-localization/help/fr_FR/block/particle_condition.md
  plugins/mcreator-localization/help/fr_FR/block/redstone_connect.md
  plugins/mcreator-localization/help/fr_FR/block/redstone_power.md
  plugins/mcreator-localization/help/fr_FR/block/redstone_provider.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/parts/NumberProcedure.java
  src/main/java/net/mcreator/element/parts/Procedure.java
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/procedure/AbstractProcedureSelector.java
  src/main/java/net/mcreator/ui/procedure/CBoxEntry.java
  src/main/java/net/mcreator/ui/procedure/NumberProcedureSelector.java
  src/main/java/net/mcreator/workspace/elements/ModElementManager.java
  src/test/java/net/mcreator/integration/ModElementUITest.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/generator/GTSampleElements.java
Labels: new feature

#1353 Added more fluid properties
  plugins/generator-1.15.2/forge-1.15.2/templates/fluid.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/fluid.java.ftl
  plugins/mcreator-localization/help/default/fluid/bucket_texture.md
  plugins/mcreator-localization/help/default/fluid/can_multiply.md
  plugins/mcreator-localization/help/default/fluid/drip_particle.md
  plugins/mcreator-localization/help/default/fluid/empty_sound.md
  plugins/mcreator-localization/help/default/fluid/flow_rate.md
  plugins/mcreator-localization/help/default/fluid/level_decrease.md
  plugins/mcreator-localization/help/default/fluid/slope_find_distance.md
  plugins/mcreator-localization/help/default/fluid/spawn_drip_particles.md
  plugins/mcreator-localization/help/default/fluid/temperature.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Fluid.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/FluidGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#1464 Added dialog tests
  src/main/java/net/mcreator/ui/dialogs/UpdateNotifyDialog.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/DesaturateDialog.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/FromTemplateDialog.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/HSVNoiseDialog.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/NewImageDialog.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/NewLayerDialog.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/RecolorDialog.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/ResizeCanvasDialog.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/ResizeDialog.java
  src/main/java/net/mcreator/ui/dialogs/preferences/PreferencesDialog.java
  src/main/java/net/mcreator/ui/dialogs/tools/ArmorPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/InjectTagsTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/MaterialPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/OrePackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/ToolPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/WoodPackMakerTool.java
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
  src/test/java/net/mcreator/integration/TestSetup.java
  src/test/java/net/mcreator/integration/ui/DialogsTest.java
  src/test/java/net/mcreator/integration/ui/ModElementUITest.java
Labels: official

#1438 Support for selecting what screen custom overlay overlays (overlay targets)
  plugins/generator-1.15.2/forge-1.15.2/mappings/screens.yaml
  plugins/generator-1.15.2/forge-1.15.2/templates/overlay.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/mappings/screens.yaml
  plugins/generator-1.16.5/forge-1.16.5/templates/overlay.java.ftl
  plugins/mcreator-core/datalists/screens.yaml
  plugins/mcreator-localization/help/default/overlay/overlay_target.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Overlay.java
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/dialogs/workspace/GeneratorSelector.java
  src/main/java/net/mcreator/ui/modgui/OverlayGUI.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYGEditor.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#1308 "Dispense behavior" options for items
  plugins/generator-1.15.2/forge-1.15.2/templates/item.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/utils/procedures.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/item.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/utils/procedures.java.ftl
  plugins/mcreator-localization/help/default/item/dispense_result_itemstack.md
  plugins/mcreator-localization/help/default/item/dispense_success_condition.md
  plugins/mcreator-localization/help/default/item/has_dispense_behavior.md
  plugins/mcreator-localization/help/fr_FR/item/dispense_result_itemstack.md
  plugins/mcreator-localization/help/fr_FR/item/dispense_success_condition.md
  plugins/mcreator-localization/help/fr_FR/item/has_dispense_behavior.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/parts/Procedure.java
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/element/types/Procedure.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/main/java/net/mcreator/ui/procedure/ProcedureSelector.java
  src/main/java/net/mcreator/workspace/elements/VariableTypeLoader.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/generator/GTSampleElements.java
  src/test/java/net/mcreator/integration/ui/ModElementUITest.java
Labels: new feature
