Repository MCreator/MCreator, pull requests merged in 2021-07, with the labels that each got.

#1497 Update splash screen
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official

#1499 Fixed custom log rotation not matching vanilla log rotation
  plugins/generator-1.15.2/forge-1.15.2/templates/block.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/json/block_states.json.ftl
  plugins/generator-1.15.2/forge-1.15.2/utils/boundingboxes.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/block.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/json/block_states.json.ftl
  plugins/generator-1.16.5/forge-1.16.5/utils/boundingboxes.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/utils/mcitems.ftl
Labels: bug

#1486 Action result type variable and optional result type for some procedure triggers
  plugins/generator-1.15.2/forge-1.15.2/mappings/types.yaml
  plugins/generator-1.15.2/forge-1.15.2/procedures/action_result_type.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/block.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/dimension/portaltrigger.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/food.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/item.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/livingentity.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/musicdisc.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/plant.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/templates/tool.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/utils/procedures.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/mappings/types.yaml
  plugins/generator-1.16.5/forge-1.16.5/procedures/action_result_type.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/block.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/dimension/portaltrigger.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/food.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/item.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/livingentity.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/musicdisc.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/plant.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/tool.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/utils/procedures.java.ftl
  plugins/mcreator-core/procedures/action_result_type.json
  plugins/mcreator-core/variables/actionresulttype.json
  plugins/mcreator-localization/help/default/block/when_right_clicked.md
  plugins/mcreator-localization/help/default/dimension/when_portal_used.md
  plugins/mcreator-localization/help/default/entity/when_right_clicked.md
  plugins/mcreator-localization/help/default/item/when_right_clicked_block.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/DimensionGUI.java
  src/main/java/net/mcreator/ui/modgui/FoodGUI.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/main/java/net/mcreator/ui/modgui/MusicDiscGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/main/java/net/mcreator/ui/modgui/ToolGUI.java
  src/main/java/net/mcreator/workspace/elements/VariableTypeLoader.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/generator/GTSampleElements.java
  src/test/java/net/mcreator/integration/ui/ModElementUITest.java
Labels: new feature

#1512 Improve chunk.png
  plugins/mcreator-themes/themes/default_dark/images/chunk.png
  plugins/mcreator-themes/themes/default_light/images/chunk.png
Labels: official

#1513 Added immediatesourceentity dependency to ranged item triggers
  plugins/generator-1.15.2/forge-1.15.2/templates/rangeditem.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/rangeditem.java.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/modgui/RangedItemGUI.java
Labels: new feature

#1515 Support for break/continue block inside custom blocks
  plugins/mcreator-core/procedures/entity_inventory_foreach.json
  plugins/mcreator-core/procedures/world_entity_inrange_foreach.json
  plugins/mcreator-core/procedures/world_entity_player_foreach.json
  src/main/resources/blockly/js/mcreator_blocks.js
Labels: new feature

#1281 Add more procedures (Plugin "More Procedures") part 1/2
  plugins/generator-1.15.2/forge-1.15.2/procedures/entity_get_fly_speed.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/entity_get_oxygen.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/entity_get_walk_speed.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/entity_is_elytra_flying.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/entity_isblocking.java.ftl
  plugins/generator-1.15.2/forge-1.15.2/procedures/entity_set_oxygen.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/entity_get_fly_speed.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/entity_get_oxygen.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/entity_get_walk_speed.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/entity_is_elytra_flying.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/entity_isblocking.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/entity_set_oxygen.java.ftl
  plugins/mcreator-core/procedures/entity_get_fly_speed.json
  plugins/mcreator-core/procedures/entity_get_oxygen.json
  plugins/mcreator-core/procedures/entity_get_walk_speed.json
  plugins/mcreator-core/procedures/entity_is_elytra_flying.json
  plugins/mcreator-core/procedures/entity_isblocking.json
  plugins/mcreator-core/procedures/entity_set_oxygen.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#1530 Added "side" field for global triggers
  plugins/mcreator-core/triggers/block_break.json
  plugins/mcreator-core/triggers/block_multiplace.json
  plugins/mcreator-core/triggers/block_place.json
  plugins/mcreator-core/triggers/chat_sent.json
  plugins/mcreator-core/triggers/command_executed.json
  plugins/mcreator-core/triggers/crop_attempts_growth.json
  plugins/mcreator-core/triggers/entity_dropxp.json
  plugins/mcreator-core/triggers/entity_grief.json
  plugins/mcreator-core/triggers/entity_healed.json
  plugins/mcreator-core/triggers/entity_item_pickup.json
  plugins/mcreator-core/triggers/entity_pickupxp.json
  plugins/mcreator-core/triggers/entity_pre_hurt.json
  plugins/mcreator-core/triggers/entity_sets_attack_target.json
  plugins/mcreator-core/triggers/entity_struck_by_lightning.json
  plugins/mcreator-core/triggers/entity_tamed.json
  plugins/mcreator-core/triggers/entity_travels_to_dimension.json
  plugins/mcreator-core/triggers/explosion_occurs.json
  plugins/mcreator-core/triggers/farmland_trampled.json
  plugins/mcreator-core/triggers/gem_dropped.json
  plugins/mcreator-core/triggers/gem_expired.json
  plugins/mcreator-core/triggers/item_destroyed.json
  plugins/mcreator-core/triggers/mod_clientload.json
  plugins/mcreator-core/triggers/mod_serverload.json
  plugins/mcreator-core/triggers/player_completes_advancement.json
  plugins/mcreator-core/triggers/player_fishes_item.json
  plugins/mcreator-core/triggers/player_in_bed.json
  plugins/mcreator-core/triggers/player_left_click_block.json
  plugins/mcreator-core/triggers/player_log_in.json
  plugins/mcreator-core/triggers/player_log_out.json
  plugins/mcreator-core/triggers/player_respawn.json
  plugins/mcreator-core/triggers/player_right_click_block.json
  plugins/mcreator-core/triggers/player_right_click_entity.json
  plugins/mcreator-core/triggers/player_right_click_item.json
  plugins/mcreator-core/triggers/player_xp_change.json
  plugins/mcreator-core/triggers/player_xp_level_change.json
  plugins/mcreator-core/triggers/sapling_glow.json
  plugins/mcreator-core/triggers/village_siege.json
  plugins/mcreator-core/triggers/world_ticks.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/data/ExternalTrigger.java
  src/main/java/net/mcreator/ui/modgui/ProcedureGUI.java
Labels: new feature

#1466 Minor refactoring of image maker
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-localization/lang/texts_cs_CZ.properties
  plugins/mcreator-localization/lang/texts_fr_FR.properties
  plugins/mcreator-localization/lang/texts_he_IL.properties
  plugins/mcreator-localization/lang/texts_ja_JP.properties
  plugins/mcreator-localization/lang/texts_pt_BR.properties
  plugins/mcreator-localization/lang/texts_ru_RU.properties
  plugins/mcreator-localization/lang/texts_vi_VN.properties
  plugins/mcreator-localization/lang/texts_zh_CN.properties
  plugins/mcreator-localization/lang/texts_zh_TW.properties
  plugins/mcreator-themes/themes/default_dark/images/16px/reset.png
  plugins/mcreator-themes/themes/default_light/images/16px/reset.png
  src/main/java/net/mcreator/ui/MainMenuBar.java
  src/main/java/net/mcreator/ui/action/ActionRegistry.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/RecolorDialog.java
  src/main/java/net/mcreator/ui/dialogs/tools/WoodPackMakerTool.java
  src/main/java/net/mcreator/ui/views/editor/image/action/ImageEditorRedoAction.java
  src/main/java/net/mcreator/ui/views/editor/image/action/ImageEditorUndoAction.java
  src/main/java/net/mcreator/ui/views/editor/image/canvas/CanvasRenderer.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/ToolPanel.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/component/ColorSelector.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/AbstractModificationTool.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/ColorPickerTool.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/DrawingTool.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/FloodFillTool.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/PencilTool.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/ShapeTool.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/StampTool.java
Labels: new feature

#1531 Fishing rod tool type
  plugins/generator-1.15.2/forge-1.15.2/templates/tool.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/tool.java.ftl
  src/main/java/net/mcreator/ui/init/BlockItemIcons.java
  src/main/java/net/mcreator/ui/modgui/ToolGUI.java
  src/main/java/net/mcreator/ui/validation/validators/JavaMemeberNameValidator.java
Labels: new feature

#1538 Custom backgrounds for themes
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/preferences/PreferencesData.java
  src/main/java/net/mcreator/ui/MCreator.java
  src/main/java/net/mcreator/ui/init/BackgroundLoader.java
Labels: new feature

#1454 Parameter for generators to define their JDK version
  build.gradle
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/generator/GeneratorConfiguration.java
  src/main/java/net/mcreator/gradle/GradleDaemonUtils.java
  src/main/java/net/mcreator/gradle/GradleUtils.java
  src/main/java/net/mcreator/io/FileIO.java
  src/main/java/net/mcreator/io/OS.java
  src/main/java/net/mcreator/io/zip/ZipIO.java
  src/main/java/net/mcreator/ui/action/impl/workspace/SDKManager.java
  src/main/java/net/mcreator/ui/dialogs/ProgressDialog.java
  src/main/java/net/mcreator/ui/dialogs/workspace/GeneratorSelector.java
  src/main/java/net/mcreator/ui/dialogs/workspace/WorkspaceGeneratorSetupDialog.java
  src/main/java/net/mcreator/ui/gradle/GradleConsole.java
Labels: new feature

#1569 Implement auto Crowdin updates
  .github/workflows/crowdin_download.yml
  .github/workflows/crowdin_upload.yml
  crowdin.yml
Labels: new feature, official

#1571 Fix #1566
  plugins/generator-1.16.5/forge-1.16.5/workspacebase/build.gradle
  src/main/java/net/mcreator/gradle/GradleUtils.java
Labels: bug

#1580 Fixed some issues with the wood pack maker
  src/main/java/net/mcreator/ui/dialogs/tools/WoodPackMakerTool.java
Labels: bug

#1587 Added tick rate option to fluids
  plugins/generator-1.15.2/forge-1.15.2/templates/fluid.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/fluid.java.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Fluid.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/FluidGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: bug, new feature

#1541 Minor features for plants
  plugins/generator-1.15.2/forge-1.15.2/templates/plant.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/plant.java.ftl
  plugins/mcreator-localization/help/default/plant/patch_size.md
  plugins/mcreator-localization/help/default/plant/suspicious_stew_duration.md
  plugins/mcreator-localization/help/default/plant/suspicious_stew_effect.md
  plugins/mcreator-localization/help/fr_FR/plant/patch_size.md
  plugins/mcreator-localization/help/fr_FR/plant/suspicious_stew_duration.md
  plugins/mcreator-localization/help/fr_FR/plant/suspicious_stew_effect.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature
