Repository MCreator/MCreator, pull requests merged in 2022-12, with the labels that each got.

#2806 Translatable components support for GUIs and overlays
  plugins/generator-1.18.2/forge-1.18.2/gui.definition.yaml
  plugins/generator-1.18.2/forge-1.18.2/overlay.definition.yaml
  plugins/generator-1.18.2/forge-1.18.2/templates/gui/gui_window.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/overlay.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/gui.definition.yaml
  plugins/generator-1.19.2/forge-1.19.2/overlay.definition.yaml
  plugins/generator-1.19.2/forge-1.19.2/templates/gui/gui_window.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/overlay.java.ftl
  src/main/java/net/mcreator/element/parts/gui/Label.java
  src/main/java/net/mcreator/element/types/interfaces/IGUI.java
  src/main/java/net/mcreator/generator/Generator.java
  src/main/java/net/mcreator/generator/GeneratorTokens.java
  src/main/java/net/mcreator/generator/LanguageFilesGenerator.java
  src/main/java/net/mcreator/generator/LocalizationUtils.java
Labels: new feature

#3357 Minor procedure fixes
  plugins/generator-1.18.2/forge-1.18.2/procedures/block_fluidtank_check_fill.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/block_fluidtank_fill.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/block_fluidtank_check_fill.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/block_fluidtank_fill.java.ftl
  src/main/java/net/mcreator/blockly/java/blocks/GetVariableBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/SetVariableBlock.java
Labels: bug

#3352 Optimization of GUI/overlay templates and dialogs
  plugins/generator-1.18.2/forge-1.18.2/templates/gui/gui_msg_button.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/gui/gui_window.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/overlay.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/gui/gui_msg_button.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/gui/gui_window.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/overlay.java.ftl
  src/main/java/net/mcreator/element/types/Overlay.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/ButtonDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/LabelDialog.java
Labels: bug

#3353 1.18+ biome gen settings
  plugins/generator-1.18.2/forge-1.18.2/templates/biome/biome.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/json/dimension/multi_noise.json.ftl
  plugins/generator-1.18.2/forge-1.18.2/utils/biomeutils.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/biome/biome.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/json/dimension/multi_noise.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/utils/biomeutils.ftl
  plugins/generator-addon-1.19.x/addon-1.19.x/biome.definition.yaml
  plugins/generator-addon-1.19.x/addon-1.19.x/templates/biome.json.ftl
  plugins/generator-datapack-1.18.x/datapack-1.18.x/templates/dimension/multi_noise.json.ftl
  plugins/generator-datapack-1.18.x/datapack-1.18.x/utils/biomeutils.ftl
  plugins/generator-datapack-1.19.x/datapack-1.19.x/templates/dimension/multi_noise.json.ftl
  plugins/generator-datapack-1.19.x/datapack-1.19.x/utils/biomeutils.ftl
  plugins/mcreator-localization/help/default/biome/base_height.md
  plugins/mcreator-localization/help/default/biome/coverage_estimate.md
  plugins/mcreator-localization/help/default/biome/gen_continentalness.md
  plugins/mcreator-localization/help/default/biome/gen_erosion.md
  plugins/mcreator-localization/help/default/biome/gen_humidity.md
  plugins/mcreator-localization/help/default/biome/gen_temperature.md
  plugins/mcreator-localization/help/default/biome/gen_weirdness.md
  plugins/mcreator-localization/help/default/biome/height_variation.md
  plugins/mcreator-localization/help/default/biome/raining_possibility.md
  plugins/mcreator-localization/help/default/biome/temperature.md
  plugins/mcreator-localization/help/default/biome/weight.md
  plugins/mcreator-localization/help/fr_FR/biome/base_height.md
  plugins/mcreator-localization/help/fr_FR/biome/coverage_estimate.md
  plugins/mcreator-localization/help/fr_FR/biome/gen_continentalness.md
  plugins/mcreator-localization/help/fr_FR/biome/gen_erosion.md
  plugins/mcreator-localization/help/fr_FR/biome/gen_humidity.md
  plugins/mcreator-localization/help/fr_FR/biome/gen_temperature.md
  plugins/mcreator-localization/help/fr_FR/biome/gen_weirdness.md
  plugins/mcreator-localization/help/fr_FR/biome/height_variation.md
  plugins/mcreator-localization/help/fr_FR/biome/weight.md
  plugins/mcreator-localization/help/ru_RU/biome/base_height.md
  plugins/mcreator-localization/help/ru_RU/biome/coverage_estimate.md
  plugins/mcreator-localization/help/ru_RU/biome/gen_continentalness.md
  plugins/mcreator-localization/help/ru_RU/biome/gen_erosion.md
  plugins/mcreator-localization/help/ru_RU/biome/gen_humidity.md
  plugins/mcreator-localization/help/ru_RU/biome/gen_temperature.md
  plugins/mcreator-localization/help/ru_RU/biome/gen_weirdness.md
  plugins/mcreator-localization/help/ru_RU/biome/height_variation.md
  plugins/mcreator-localization/help/ru_RU/biome/raining_possibility.md
  plugins/mcreator-localization/help/ru_RU/biome/temperature.md
  plugins/mcreator-localization/help/ru_RU/biome/weight.md
  plugins/mcreator-localization/help/zh_CN/biome/base_height.md
  plugins/mcreator-localization/help/zh_CN/biome/height_variation.md
  plugins/mcreator-localization/help/zh_CN/biome/weight.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/fv38/BiomeGenParametersConverter.java
  src/main/java/net/mcreator/element/types/Biome.java
  src/main/java/net/mcreator/ui/component/JMinMaxSpinner.java
  src/main/java/net/mcreator/ui/modgui/BiomeGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: bug, new feature

#3342 Added height placement blocks
  plugins/generator-1.18.2/forge-1.18.2/features/height_provider_constant.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_height_range.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_height_triangular.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_height_uniform.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/vertical_anchor_above_bottom.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/vertical_anchor_absolute.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/vertical_anchor_below_top.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/height_provider_constant.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_height_range.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_height_triangular.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_height_uniform.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/vertical_anchor_above_bottom.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/vertical_anchor_absolute.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/vertical_anchor_below_top.java.ftl
  plugins/mcreator-core/features/$heightplacements.json
  plugins/mcreator-core/features/height_provider_constant.json
  plugins/mcreator-core/features/placement_height_range.json
  plugins/mcreator-core/features/placement_height_triangular.json
  plugins/mcreator-core/features/placement_height_uniform.json
  plugins/mcreator-core/features/placement_heightmap.json
  plugins/mcreator-core/features/vertical_anchor_above_bottom.json
  plugins/mcreator-core/features/vertical_anchor_absolute.json
  plugins/mcreator-core/features/vertical_anchor_below_top.json
  plugins/mcreator-localization/lang/texts.properties
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
Labels: new feature

#3370 Added some optional settings for data list selector fields
  plugins/mcreator-core/blockly/field_data_list_selector.js
  plugins/mcreator-core/procedures/advancement_isequalto.json
  plugins/mcreator-core/procedures/entity_add_achievement.json
  plugins/mcreator-core/procedures/entity_add_potion.json
  plugins/mcreator-core/procedures/entity_add_potion_advanced.json
  plugins/mcreator-core/procedures/entity_has_achievement.json
  plugins/mcreator-core/procedures/entity_haspotioneffect.json
  plugins/mcreator-core/procedures/entity_potioneffectlevel.json
  plugins/mcreator-core/procedures/entity_potioneffectremaining.json
  plugins/mcreator-core/procedures/entity_remove_specific_potion_effect.json
  plugins/mcreator-core/procedures/item_add_enhancement.json
  plugins/mcreator-core/procedures/item_get_enhancement.json
  plugins/mcreator-core/procedures/itemstack_has_enchantment.json
  plugins/mcreator-core/procedures/itemstack_remove_specific_enchantment.json
  plugins/mcreator-core/procedures/projectiles_fireball.json
  plugins/mcreator-core/procedures/projectiles_throwable.json
  plugins/mcreator-core/procedures/spawn_particle.json
  plugins/mcreator-core/procedures/spawn_particle_multi.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/test/java/net/mcreator/integration/generator/GTProcedureBlocks.java
Labels: new feature

#3411 Added some item stack related getters
  plugins/generator-1.18.2/forge-1.18.2/procedures/itemstack_get_max_stack_size.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/itemstack_is_damageable.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/itemstack_is_damaged.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/itemstack_is_stackable.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/itemstack_get_max_stack_size.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/itemstack_is_damageable.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/itemstack_is_damaged.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/itemstack_is_stackable.java.ftl
  plugins/mcreator-core/procedures/itemstack_get_max_stack_size.json
  plugins/mcreator-core/procedures/itemstack_is_damageable.json
  plugins/mcreator-core/procedures/itemstack_is_damaged.json
  plugins/mcreator-core/procedures/itemstack_is_stackable.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#2010 Added list templates support
  src/main/java/net/mcreator/generator/Generator.java
  src/main/java/net/mcreator/generator/GeneratorFile.java
  src/main/java/net/mcreator/generator/GeneratorTemplate.java
  src/main/java/net/mcreator/generator/GeneratorTemplatesList.java
  src/main/java/net/mcreator/generator/GeneratorTokens.java
  src/main/java/net/mcreator/generator/ListTemplate.java
  src/main/java/net/mcreator/generator/template/TemplateGenerator.java
  src/main/java/net/mcreator/generator/template/base/BaseDataModelProvider.java
  src/main/java/net/mcreator/ui/action/impl/workspace/RegenerateCodeAction.java
  src/main/java/net/mcreator/ui/modgui/ModElementGUI.java
  src/main/java/net/mcreator/ui/modgui/codeviewer/FileCodeViewer.java
  src/main/java/net/mcreator/ui/modgui/codeviewer/ModElementCodeViewer.java
  src/main/java/net/mcreator/ui/workspace/ModElementCodeDropdown.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
Labels: new feature

#3399 Added conditional placement blocks
  plugins/generator-1.18.2/forge-1.18.2/features/block_predicate_has_sturdy_face.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/block_predicate_inside_world.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/block_predicate_is_air.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/block_predicate_is_air_or_water.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/block_predicate_not.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/block_predicate_replaceable.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/block_predicate_solid.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/block_predicate_would_survive.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_block_predicate_filter.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_environment_scan.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_environment_scan_advanced.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/block_predicate_has_sturdy_face.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/block_predicate_inside_world.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/block_predicate_is_air.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/block_predicate_is_air_or_water.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/block_predicate_not.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/block_predicate_replaceable.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/block_predicate_solid.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/block_predicate_would_survive.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_block_predicate_filter.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_environment_scan.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_environment_scan_advanced.java.ftl
  plugins/mcreator-core/features/$blockpredicates.json
  plugins/mcreator-core/features/block_predicate_has_sturdy_face.json
  plugins/mcreator-core/features/block_predicate_inside_world.json
  plugins/mcreator-core/features/block_predicate_is_air.json
  plugins/mcreator-core/features/block_predicate_is_air_or_water.json
  plugins/mcreator-core/features/block_predicate_not.json
  plugins/mcreator-core/features/block_predicate_replaceable.json
  plugins/mcreator-core/features/block_predicate_solid.json
  plugins/mcreator-core/features/block_predicate_would_survive.json
  plugins/mcreator-core/features/placement_block_predicate_filter.json
  plugins/mcreator-core/features/placement_environment_scan.json
  plugins/mcreator-core/features/placement_environment_scan_advanced.json
  plugins/mcreator-localization/lang/texts.properties
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
Labels: new feature
