Repository MCreator/MCreator, pull requests merged in 2022-02, with the labels that each got.

#2393 Fixed issue with custom buckets, added missing tooltips
  plugins/mcreator-localization/help/default/block/disable_offset.md
  plugins/mcreator-localization/help/default/plant/custom_bounding_box.md
  plugins/mcreator-localization/help/fr_FR/block/disable_offset.md
  plugins/mcreator-localization/help/fr_FR/plant/custom_bounding_box.md
  plugins/mcreator-localization/help/ru_RU/block/custom_bounding_box.md
  plugins/mcreator-localization/help/ru_RU/block/disable_offset.md
  plugins/mcreator-localization/help/ru_RU/plant/custom_bounding_box.md
  src/main/java/net/mcreator/element/ModElementTypeLoader.java
  src/main/java/net/mcreator/generator/GeneratorWrapper.java
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
Labels: bug

#2408 Fix shadows in Custom GUI Text in 1.18 mods.
  plugins/generator-1.18.1/forge-1.18.1/templates/gui/gui_window.java.ftl
Labels: bug

#2396 Add a new line tool to the image-maker
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/MainMenuBar.java
  src/main/java/net/mcreator/ui/action/AcceleratorMap.java
  src/main/java/net/mcreator/ui/action/ActionRegistry.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/ToolPanel.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/action/LineToolAction.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/LineTool.java
Labels: new feature

#1768 Added context menu to workspace browser
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/io/FileIO.java
  src/main/java/net/mcreator/ui/FileOpener.java
  src/main/java/net/mcreator/ui/action/ActionRegistry.java
  src/main/java/net/mcreator/ui/browser/AddFileDropdown.java
  src/main/java/net/mcreator/ui/browser/WorkspaceFileBrowser.java
  src/main/java/net/mcreator/ui/browser/WorkspaceFileBrowserContextMenu.java
  src/main/java/net/mcreator/util/DesktopUtils.java
Labels: new feature

#2412 Improve usability of the image editor
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/DrawingTool.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/LineTool.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/ShapeTool.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/StampTool.java
Labels: bug, official

#2185 Added unsaved changes warning to mod element GUIs
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/preferences/PreferencesData.java
  src/main/java/net/mcreator/ui/component/JItemListField.java
  src/main/java/net/mcreator/ui/minecraft/JEntriesList.java
  src/main/java/net/mcreator/ui/modgui/ModElementChangedListener.java
  src/main/java/net/mcreator/ui/modgui/ModElementGUI.java
  src/main/java/net/mcreator/ui/modgui/codeviewer/ModElementCodeViewer.java
Labels: new feature
