Repository MCreator/MCreator, pull requests merged in 2022-01, with the labels that each got.

#2173 Added default models to combo boxes in mod element GUIs
  src/main/java/net/mcreator/ui/modgui/ArmorGUI.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/FoodGUI.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/main/java/net/mcreator/ui/modgui/RangedItemGUI.java
Labels: bug

#2131 use macOS menu bar
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/Launcher.java
  src/main/java/net/mcreator/preferences/PreferencesData.java
Labels: new feature

#2246 Loot tables can now update mod element code viewer
  src/main/java/net/mcreator/ui/datapack/loottable/JLootTablePool.java
  src/main/java/net/mcreator/ui/datapack/loottable/JLootTablePoolsList.java
  src/main/java/net/mcreator/ui/modgui/LootTableGUI.java
  src/main/java/net/mcreator/ui/modgui/codeviewer/ModElementCodeViewer.java
Labels: bug

#2184 Better Blockly selector for entities, biomes and sounds
  plugins/mcreator-core/blockly/field_data_list_selector.js
  plugins/mcreator-core/blockly/mcreator_extensions.js
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
Labels: bug, new feature

#2288 Couple translation fixes
  plugins/mcreator-localization/help/default/item/has_dispense_behavior.md
  plugins/mcreator-localization/help/fr_FR/item/has_dispense_behavior.md
  plugins/mcreator-localization/help/ru_RU/item/has_dispense_behavior.md
  plugins/mcreator-localization/lang/texts.properties
Labels: bug

#2293 Add textures for 1.17 step sounds
  plugins/mcreator-core/datalists/stepsounds.yaml
Labels: bug

#2309 Minor fix
  plugins/mcreator-localization/lang/texts.properties
Labels: bug

#2294 Fix custom map color for blocks
  plugins/generator-1.17.1/forge-1.17.1/templates/block/block.java.ftl
Labels: bug

#2295 Fix 2285
  plugins/generator-1.17.1/forge-1.17.1/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.18.1/forge-1.18.1/templates/livingentity/livingentity.java.ftl
Labels: bug

#2286 Zip archive entries are now sorted
  src/main/java/net/mcreator/io/zip/IZipFileAction.java
  src/main/java/net/mcreator/io/zip/ZipIO.java
  src/main/java/net/mcreator/ui/browser/WorkspaceFileBrowser.java
Labels: bug
