Repository MCreator/MCreator, pull requests merged in 2022-05, with the labels that each got.

#2699 Fixed parentheses issue with division
  src/main/java/net/mcreator/blockly/java/JavaKeywordsMap.java
Labels: bug

#2700 Fix #2692
  plugins/generator-1.18.2/forge-1.18.2/templates/block/oregen.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/fluid/fluidgen.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/plant/plantgen.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/structure.java.ftl
Labels: bug

#2709 Update splash.png for the next release
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official

#2720 Fix #2718
  src/main/java/net/mcreator/element/converter/fv28/FoodToItemConverter.java
Labels: bug

#2728 Added "Generate at any height" option for plants (1.18.x)
  plugins/generator-1.16.5/forge-1.16.5/plant.definition.yaml
  plugins/generator-1.18.2/forge-1.18.2/templates/plant/plantgen.java.ftl
  plugins/mcreator-localization/help/default/plant/generate_at_any_height.md
  plugins/mcreator-localization/help/fr_FR/plant/generate_at_any_height.md
  plugins/mcreator-localization/help/ru_RU/plant/generate_at_any_height.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: bug, new feature

#2733 Fix #2714
  plugins/mcreator-localization/help/default/biome/ground_block.md
  plugins/mcreator-localization/help/default/biome/underground_block.md
  plugins/mcreator-localization/help/ru_RU/biome/ground_block.md
  plugins/mcreator-localization/help/ru_RU/biome/underground_block.md
  plugins/mcreator-localization/lang/texts.properties
Labels: bug

#2731 Possibly fix #2724?
  plugins/generator-1.18.2/forge-1.18.2/templates/structure.java.ftl
Labels: bug

#2744 Fixed data list selector size issue (#2741)
  plugins/mcreator-core/blockly/field_data_list_selector.js
Labels: bug

#2516 Added pitch rotation support for custom blocks
  plugins/generator-1.16.5/forge-1.16.5/templates/block.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/json/block_states.json.ftl
  plugins/generator-1.16.5/forge-1.16.5/utils/boundingboxes.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/block/block.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/json/block_states.json.ftl
  plugins/generator-1.18.2/forge-1.18.2/utils/boundingboxes.java.ftl
  plugins/mcreator-localization/help/default/block/enable_pitch.md
  plugins/mcreator-localization/help/fr_FR/block/enable_pitch.md
  plugins/mcreator-localization/help/ru_RU/block/enable_pitch.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#2780 Fixed bounding boxes of blocks without pitch rotation
  plugins/generator-1.16.5/forge-1.16.5/utils/boundingboxes.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/utils/boundingboxes.java.ftl
Labels: bug

#2768 Data list selector refactoring
  plugins/mcreator-core/aitasks/attack_entity.json
  plugins/mcreator-core/aitasks/avoid_entity.json
  plugins/mcreator-core/aitasks/watch_closest_entity.json
  plugins/mcreator-core/blockly/field_data_list_selector.js
  plugins/mcreator-core/blockly/mcreator_extensions.js
  plugins/mcreator-core/jsontriggers/biome_entered.json
  plugins/mcreator-core/procedures/advancement_isequalto.json
  plugins/mcreator-core/procedures/entity_add_achievement.json
  plugins/mcreator-core/procedures/entity_add_potion.json
  plugins/mcreator-core/procedures/entity_add_potion_advanced.json
  plugins/mcreator-core/procedures/entity_has_achievement.json
  plugins/mcreator-core/procedures/entity_haspotioneffect.json
  plugins/mcreator-core/procedures/entity_potioneffectlevel.json
  plugins/mcreator-core/procedures/entity_potioneffectremaining.json
  plugins/mcreator-core/procedures/entity_remove_specific_potion_effect.json
  plugins/mcreator-core/procedures/item_add_enhancement.json
  plugins/mcreator-core/procedures/item_get_enhancement.json
  plugins/mcreator-core/procedures/itemstack_has_enchantment.json
  plugins/mcreator-core/procedures/itemstack_remove_specific_enchantment.json
  plugins/mcreator-core/procedures/logic_entity_compare.json
  plugins/mcreator-core/procedures/play_sound.json
  plugins/mcreator-core/procedures/spawn_entity.json
  plugins/mcreator-core/procedures/spawn_entity_with_rotation.json
  plugins/mcreator-core/procedures/spawn_entity_with_rotation_velocity.json
  plugins/mcreator-core/procedures/spawn_particle.json
  plugins/mcreator-core/procedures/spawn_particle_multi.json
  plugins/mcreator-core/procedures/world_data_biomeat.json
  plugins/mcreator-core/procedures/world_entity_inrange.json
  plugins/mcreator-core/procedures/world_entity_inrange_exists.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptTemplates.java
  src/main/java/net/mcreator/workspace/elements/VariableTypeLoader.java
  src/test/java/net/mcreator/integration/generator/GTProcedureBlocks.java
Labels: new feature

#2808 Added "spawnable" type to entity datalist
  plugins/mcreator-core/datalists/entities.yaml
  plugins/mcreator-core/procedures/spawn_entity.json
  plugins/mcreator-core/procedures/spawn_entity_with_rotation.json
  plugins/mcreator-core/procedures/spawn_entity_with_rotation_velocity.json
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/main/java/net/mcreator/ui/minecraft/spawntypes/JSpawnListEntry.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/generator/GTProcedureBlocks.java
Labels: new feature
