Repository MCreator/MCreator, pull requests merged in 2022-06, with the labels that each got.

#2865 Add a Pre generator loading event
  src/main/java/net/mcreator/element/ModElementTypeLoader.java
  src/main/java/net/mcreator/plugin/events/PreGeneratorsLoadingEvent.java
  src/main/java/net/mcreator/ui/MCreatorApplication.java
Labels: new feature

#2800 Blockstate related procedure blocks
  plugins/generator-1.16.5/forge-1.16.5/procedures/block_set_boolean_property.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/block_set_enum_property.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/block_set_integer_property.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/blockstate_get_boolean_property.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/blockstate_get_direction.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/blockstate_get_enum_property.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/blockstate_get_integer_property.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/blockstate_with_boolean_property.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/blockstate_with_direction.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/blockstate_with_enum_property.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/blockstate_with_integer_property.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/block_set_boolean_property.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/block_set_enum_property.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/block_set_integer_property.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/blockstate_get_boolean_property.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/blockstate_get_direction.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/blockstate_get_enum_property.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/blockstate_get_integer_property.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/blockstate_with_boolean_property.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/blockstate_with_direction.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/blockstate_with_enum_property.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/blockstate_with_integer_property.java.ftl
  plugins/mcreator-core/procedures/block_set_boolean_property.json
  plugins/mcreator-core/procedures/block_set_enum_property.json
  plugins/mcreator-core/procedures/block_set_integer_property.json
  plugins/mcreator-core/procedures/blockstate_get_boolean_property.json
  plugins/mcreator-core/procedures/blockstate_get_direction.json
  plugins/mcreator-core/procedures/blockstate_get_enum_property.json
  plugins/mcreator-core/procedures/blockstate_get_integer_property.json
  plugins/mcreator-core/procedures/blockstate_with_boolean_property.json
  plugins/mcreator-core/procedures/blockstate_with_direction.json
  plugins/mcreator-core/procedures/blockstate_with_enum_property.json
  plugins/mcreator-core/procedures/blockstate_with_integer_property.json
  plugins/mcreator-core/templates/ptpl/Check if water cauldron is full.ptpl
  plugins/mcreator-core/templates/ptpl/Increase age of wheat crop.ptpl
  plugins/mcreator-core/templates/ptpl/Place double plant.ptpl
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#2866 Add some UI events
  src/main/java/net/mcreator/plugin/events/ui/ModElementGUIEvent.java
  src/main/java/net/mcreator/plugin/events/ui/TabEvent.java
  src/main/java/net/mcreator/ui/MCreatorTabs.java
  src/main/java/net/mcreator/ui/modgui/ModElementGUI.java
Labels: new feature

#2875 Added transparency control to JColor
  src/main/java/net/mcreator/ui/component/JColor.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/FromTemplateDialog.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/NewImageDialog.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/NewLayerDialog.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/RecolorDialog.java
  src/main/java/net/mcreator/ui/dialogs/preferences/PreferencesDialog.java
  src/main/java/net/mcreator/ui/dialogs/tools/ArmorPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/MaterialPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/OrePackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/ToolPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/WoodPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/InputSlotDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/LabelDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/OutputSlotDialog.java
  src/main/java/net/mcreator/ui/modgui/BiomeGUI.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/DimensionGUI.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/main/java/net/mcreator/ui/modgui/PotionEffectGUI.java
  src/main/java/net/mcreator/ui/views/AnimationMakerView.java
  src/main/java/net/mcreator/ui/views/ArmorImageMakerView.java
Labels: bug

#2891 Re-added translation strings used by file dialogs
  plugins/mcreator-localization/lang/texts.properties
Labels: bug

#2892 Fix checkboxes having the wrong size
  plugins/generator-1.16.5/forge-1.16.5/templates/gui_window.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/gui/gui_window.java.ftl
Labels: bug

#2849 Fixed `JEntriesList`s not running all listeners at once
  src/main/java/net/mcreator/ui/minecraft/JEntriesList.java
  src/main/java/net/mcreator/ui/modgui/ModElementChangedListener.java
Labels: bug

#2914 Update the splash screen
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official

#2912 Allow custom data list entries to have multiple mappings
  plugins/generator-1.16.5/forge-1.16.5/mappings/entities.yaml
  plugins/generator-1.16.5/forge-1.16.5/mappings/projectiles.yaml
  plugins/generator-1.16.5/forge-1.16.5/procedures/spawn_entity.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/spawn_entity_with_rotation.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/spawn_entity_with_rotation_velocity.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/biome.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/json/tag.json.ftl
  plugins/generator-1.18.2/forge-1.18.2/mappings/entities.yaml
  plugins/generator-1.18.2/forge-1.18.2/mappings/projectiles.yaml
  plugins/generator-1.18.2/forge-1.18.2/procedures/spawn_entity.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/spawn_entity_with_rotation.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/spawn_entity_with_rotation_velocity.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/biome/biome.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/json/tag.json.ftl
  src/main/java/net/mcreator/generator/mapping/NameMapper.java
Labels: new feature

#2920 Small fixes
  src/main/java/net/mcreator/blockly/data/ToolboxBlock.java
  src/main/java/net/mcreator/ui/minecraft/SpawnableEntityListField.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/TagGUI.java
  src/test/java/net/mcreator/integration/generator/GTProcedureBlocks.java
Labels: bug

#2537 Added 4 new texture types
  plugins/generator-1.16.5/forge-1.16.5/generator.yaml
  plugins/generator-1.16.5/forge-1.16.5/templates/armor.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/bullet_renderer.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/gui_window.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/json/achievement.json.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/livingentity_renderer.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/templates/overlay.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/generator.yaml
  plugins/generator-1.18.2/forge-1.18.2/templates/armor.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/gui/gui_window.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/json/achievement.json.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/livingentity/livingentity_renderer.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/overlay.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/rangeditem/projectile_renderer.java.ftl
  plugins/generator-datapack-1.16.x/datapack-1.16.x/generator.yaml
  plugins/generator-datapack-1.16.x/datapack-1.16.x/templates/achievement.json.ftl
  plugins/generator-datapack-1.18.x/datapack-1.18.x/generator.yaml
  plugins/generator-datapack-1.18.x/datapack-1.18.x/templates/advancement.json.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/fv23/PotionToEffectConverter.java
  src/main/java/net/mcreator/element/converter/fv31/AdvancementTextureConverter.java
  src/main/java/net/mcreator/element/converter/fv31/ArmorTexturesConverter.java
  src/main/java/net/mcreator/element/converter/fv31/EffectTextureConverter.java
  src/main/java/net/mcreator/element/converter/fv31/EntityTexturesConverter.java
  src/main/java/net/mcreator/element/converter/fv31/GUITexturesConverter.java
  src/main/java/net/mcreator/element/converter/fv31/OverlayTexturesConverter.java
  src/main/java/net/mcreator/element/converter/fv31/ParticleTextureConverter.java
  src/main/java/net/mcreator/element/converter/fv31/RangedItemTextureConverter.java
  src/main/java/net/mcreator/element/parts/gui/Image.java
  src/main/java/net/mcreator/element/types/GUI.java
  src/main/java/net/mcreator/element/types/Overlay.java
  src/main/java/net/mcreator/element/types/Particle.java
  src/main/java/net/mcreator/element/types/PotionEffect.java
  src/main/java/net/mcreator/generator/Generator.java
  src/main/java/net/mcreator/minecraft/MinecraftImageGenerator.java
  src/main/java/net/mcreator/ui/MainMenuBar.java
  src/main/java/net/mcreator/ui/action/ActionRegistry.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/ImageDialog.java
  src/main/java/net/mcreator/ui/laf/renderer/WTextureComboBoxRenderer.java
  src/main/java/net/mcreator/ui/modgui/AchievementGUI.java
  src/main/java/net/mcreator/ui/modgui/ArmorGUI.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/main/java/net/mcreator/ui/modgui/OverlayGUI.java
  src/main/java/net/mcreator/ui/modgui/PaintingGUI.java
  src/main/java/net/mcreator/ui/modgui/ParticleGUI.java
  src/main/java/net/mcreator/ui/modgui/PotionEffectGUI.java
  src/main/java/net/mcreator/ui/modgui/RangedItemGUI.java
  src/main/java/net/mcreator/ui/views/editor/image/ImageMakerView.java
  src/main/java/net/mcreator/ui/workspace/resources/TextureType.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelTextures.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYG.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYGEditor.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature
