Repository MCreator/MCreator, pull requests merged in 2022-11, with the labels that each got.

#3262 FG bump to .47 to fix some bugs
  plugins/generator-1.19.2/forge-1.19.2/generator.yaml
Labels: bug

#3260 Fix #3257
  plugins/generator-1.19.2/forge-1.19.2/procedures/entity_execute_command.java.ftl
Labels: bug

#3265 Add new resource icons
  plugins/mcreator-themes/themes/default_dark/images/16px/importarmor.png
  plugins/mcreator-themes/themes/default_dark/images/16px/importeffect.png
  plugins/mcreator-themes/themes/default_dark/images/16px/importentity.png
  plugins/mcreator-themes/themes/default_dark/images/16px/importgui.png
  plugins/mcreator-themes/themes/default_dark/images/16px/importparticle.png
  plugins/mcreator-themes/themes/default_dark/images/16px/newarmor.png
  plugins/mcreator-themes/themes/default_dark/images/16px/setupvcs.png
  src/main/java/net/mcreator/ui/action/ActionRegistry.java
Labels: new feature, official

#3266 Update the VCS action icon
  src/main/java/net/mcreator/ui/action/impl/vcs/SetupOrSettingsVCSAction.java
  src/main/java/net/mcreator/ui/action/impl/vcs/SetupVCSAction.java
Labels: new feature, official

#3267 Rearrange toolbar
  plugins/mcreator-themes/themes/default_dark/images/16px/importentity.png
  src/main/java/net/mcreator/ui/MainToolBar.java
Labels: new feature, official

#3275 Make "Disable collision box" translatable
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
Labels: bug

#3278 Fixed broken interpolation in image editor when using custom backgrounds
  src/main/java/net/mcreator/ui/component/zoompane/JZoomport.java
Labels: bug

#3274 Accept item tags in input slot limitations
  plugins/generator-1.18.2/forge-1.18.2/templates/gui/gui_container.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/gui/gui_container.java.ftl
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/InputSlotDialog.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#3273 Add custom code snippet blocks to AI builder Blockly editor
  plugins/mcreator-core/aitasks/$othertasks.json
  plugins/mcreator-core/aitasks/break_blocks.json
  plugins/mcreator-core/aitasks/eat_grass.json
  plugins/mcreator-core/aitasks/restrict_sun.json
  src/main/java/net/mcreator/blockly/data/ExternalBlockLoader.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/main/resources/blockly/toolbox_ai_builder.xml
Labels: new feature

#3298 Alternative fix for #3285
  src/main/java/net/mcreator/util/XMLUtil.java
Labels: bug

#3307 Move FG to recommended version
  plugins/generator-1.19.2/forge-1.19.2/generator.yaml
Labels: official

#2759 Added procedure blocks list inputs/statements support
  src/main/java/net/mcreator/blockly/data/ToolboxBlock.java
  src/main/java/net/mcreator/generator/blockly/BlocklyBlockCodeGenerator.java
  src/test/java/net/mcreator/integration/generator/GTProcedureBlocks.java
Labels: new feature

#3314 Add a Stop riding entity procedure block
  plugins/generator-1.18.2/forge-1.18.2/procedures/entity_makestopriding.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/entity_makestopriding.java.ftl
  plugins/mcreator-core/procedures/entity_makestopriding.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#2528 "Feature" mod element
  plugins/generator-1.18.2/forge-1.18.2/feature.definition.yaml
  plugins/generator-1.18.2/forge-1.18.2/features/feature_lake.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/feature_simple_block.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_heightmap.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_in_square.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_rarity.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/mappings/features.yaml
  plugins/generator-1.18.2/forge-1.18.2/mappings/generationsteps.yaml
  plugins/generator-1.18.2/forge-1.18.2/templates/elementinits/features.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/feature.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/utils/mcitems.ftl
  plugins/generator-1.19.2/forge-1.19.2/feature.definition.yaml
  plugins/generator-1.19.2/forge-1.19.2/features/feature_lake.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_simple_block.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_heightmap.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_in_square.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_rarity.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/mappings/features.yaml
  plugins/generator-1.19.2/forge-1.19.2/mappings/generationsteps.yaml
  plugins/generator-1.19.2/forge-1.19.2/templates/feature/feature.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/json/feature_biome_modifier.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/utils/mcitems.ftl
  plugins/mcreator-core/blockly/block_mcitem.js
  plugins/mcreator-core/blockly/mcreator_blocks.js
  plugins/mcreator-core/datalists/generationsteps.yaml
  plugins/mcreator-core/features/$features.json
  plugins/mcreator-core/features/$placements.json
  plugins/mcreator-core/features/feature_lake.json
  plugins/mcreator-core/features/feature_simple_block.json
  plugins/mcreator-core/features/placement_heightmap.json
  plugins/mcreator-core/features/placement_in_square.json
  plugins/mcreator-core/features/placement_rarity.json
  plugins/mcreator-localization/help/default/feature/generation_condition.md
  plugins/mcreator-localization/help/default/feature/generation_stage.md
  plugins/mcreator-localization/help/default/feature/restrict_to_dimensions.md
  plugins/mcreator-localization/help/fr_FR/feature/generation_condition.md
  plugins/mcreator-localization/help/fr_FR/feature/generation_stage.md
  plugins/mcreator-localization/help/fr_FR/feature/restrict_to_dimensions.md
  plugins/mcreator-localization/help/ru_RU/feature/generation_condition.md
  plugins/mcreator-localization/help/ru_RU/feature/generation_stage.md
  plugins/mcreator-localization/help/ru_RU/feature/restrict_to_dimensions.md
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/mod_types/feature.png
  plugins/mcreator-themes/themes/default_light/images/mod_types/feature.png
  src/main/java/net/mcreator/blockly/data/BlocklyLoader.java
  src/main/java/net/mcreator/blockly/feature/BlocklyToFeature.java
  src/main/java/net/mcreator/blockly/java/BlocklyToJava.java
  src/main/java/net/mcreator/blockly/java/BlocklyToProcedure.java
  src/main/java/net/mcreator/element/ModElementType.java
  src/main/java/net/mcreator/element/ModElementTypeLoader.java
  src/main/java/net/mcreator/element/types/Feature.java
  src/main/java/net/mcreator/generator/GeneratorStats.java
  src/main/java/net/mcreator/ui/blockly/BlocklyEditorType.java
  src/main/java/net/mcreator/ui/dialogs/workspace/GeneratorSelector.java
  src/main/java/net/mcreator/ui/modgui/FeatureGUI.java
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
  src/test/java/net/mcreator/integration/generator/GeneratorsTest.java
Labels: new feature

#3324 Added some feature and placement blocks
  plugins/generator-1.18.2/forge-1.18.2/features/feature_block_pile.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/feature_huge_brown_mushroom.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/feature_huge_red_mushroom.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_biome_filter.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_block_survival_filter.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_surface_water_depth.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/mappings/features.yaml
  plugins/generator-1.19.2/forge-1.19.2/features/feature_block_pile.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_huge_brown_mushroom.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_huge_red_mushroom.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_biome_filter.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_block_survival_filter.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_surface_water_depth.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/mappings/features.yaml
  plugins/mcreator-core/features/feature_block_pile.json
  plugins/mcreator-core/features/feature_huge_brown_mushroom.json
  plugins/mcreator-core/features/feature_huge_red_mushroom.json
  plugins/mcreator-core/features/placement_biome_filter.json
  plugins/mcreator-core/features/placement_block_survival_filter.json
  plugins/mcreator-core/features/placement_surface_water_depth.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#3334 Added support for feature templates
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/java/ProcedureTemplateIO.java
  src/main/java/net/mcreator/ui/blockly/BlocklyEditorToolbar.java
  src/main/java/net/mcreator/ui/blockly/BlocklyPanel.java
  src/main/java/net/mcreator/ui/dialogs/preferences/PreferencesDialog.java
  src/main/java/net/mcreator/ui/modgui/FeatureGUI.java
Labels: new feature

#3280 Add slot interaction conditions for custom GUIs
  plugins/generator-1.18.2/forge-1.18.2/templates/gui/gui_container.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/utils/procedures.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/gui/gui_container.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/utils/procedures.java.ftl
  plugins/mcreator-localization/help/default/gui/slot_pickup_condition.md
  plugins/mcreator-localization/help/default/gui/slot_placement_condition.md
  plugins/mcreator-localization/help/fr_FR/gui/slot_pickup_condition.md
  plugins/mcreator-localization/help/fr_FR/gui/slot_placement_condition.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/fv37/SlotInteractionsConverter.java
  src/main/java/net/mcreator/element/parts/gui/InputSlot.java
  src/main/java/net/mcreator/element/parts/gui/OutputSlot.java
  src/main/java/net/mcreator/element/parts/gui/Slot.java
  src/main/java/net/mcreator/element/parts/procedure/LogicProcedure.java
  src/main/java/net/mcreator/element/parts/procedure/RetvalProcedure.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/InputSlotDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/OutputSlotDialog.java
  src/main/java/net/mcreator/ui/procedure/LogicProcedureSelector.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature
