Repository MCreator/MCreator, pull requests merged in 2022-10, with the labels that each got.

#3132 Add a new unmodifiable AI base system
  plugins/generator-1.18.2/forge-1.18.2/livingentity.definition.yaml
  plugins/generator-1.19.2/forge-1.19.2/generator.yaml
  plugins/generator-1.19.2/forge-1.19.2/livingentity.definition.yaml
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
Labels: bug, new feature

#3209 Update the splash screen
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official

#3210 Fix pixelated image panel
  src/main/java/net/mcreator/ui/component/ImagePanel.java
Labels: official

#3190 Add enchantment and item incompatiblity features
  plugins/generator-1.18.2/forge-1.18.2/templates/enchantment.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/enchantment.java.ftl
  plugins/mcreator-localization/help/default/enchantment/can_apply_to.md
  plugins/mcreator-localization/help/default/enchantment/compatible_enchantments.md
  plugins/mcreator-localization/help/fr_FR/enchantment/can_apply_to.md
  plugins/mcreator-localization/help/fr_FR/enchantment/compatible_enchantments.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Enchantment.java
  src/main/java/net/mcreator/ui/component/JItemListField.java
  src/main/java/net/mcreator/ui/minecraft/EnchantmentListField.java
  src/main/java/net/mcreator/ui/minecraft/MCItemListField.java
  src/main/java/net/mcreator/ui/modgui/EnchantmentGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#3254 Fix #3242
  plugins/generator-1.18.2/forge-1.18.2/utils/triggers.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/utils/triggers.java.ftl
  src/main/java/net/mcreator/ui/procedure/ProcedureSelector.java
Labels: bug

#3253 Fix #3251
  plugins/generator-1.19.2/forge-1.19.2/procedures/wait.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/modbase/mod.java.ftl
Labels: bug
