Repository MCreator/MCreator, pull requests merged in 2022-03, with the labels that each got.

#2455 Stricter checks on local variable names
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/modgui/ProcedureGUI.java
  src/main/java/net/mcreator/ui/validation/validators/JavaMemberNameValidator.java
Labels: bug

#2475 Fixed biomes not generating AT
  plugins/generator-1.18.2/forge-1.18.2/generator.yaml
Labels: bug

#2478 Fixed tree placement in custom biomes
  plugins/generator-1.18.2/forge-1.18.2/templates/biome/biome.java.ftl
Labels: bug

#2493 Bugfix for #2489
  plugins/generator-1.18.2/forge-1.18.2/templates/brewingrecipe.java.ftl
Labels: bug

#2006 Added 2 render conditions for custom entities
  plugins/generator-1.16.5/forge-1.16.5/templates/livingentity_renderer.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/livingentity/livingentity_renderer.java.ftl
  plugins/mcreator-localization/help/default/entity/condition_is_model_transparent.md
  plugins/mcreator-localization/help/default/entity/condition_is_shaking.md
  plugins/mcreator-localization/help/fr_FR/entity/condition_is_model_transparent.md
  plugins/mcreator-localization/help/fr_FR/entity/condition_is_shaking.md
  plugins/mcreator-localization/help/ru_RU/entity/condition_is_model_transparent.md
  plugins/mcreator-localization/help/ru_RU/entity/condition_is_shaking.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/main/java/net/mcreator/ui/minecraft/SoundSelector.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, on hold

#2504 Moved more Blockly dropdowns to list selectors, other small improvements
  plugins/mcreator-core/blockly/mcreator_blocks.js
  plugins/mcreator-core/blockly/mcreator_extensions.js
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/java/blocks/ProcedureCallBlock.java
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptTemplates.java
Labels: bug

#2510 Forge 1.18.2 registry system fixes
  plugins/generator-1.18.2/forge-1.18.2/templates/tool.java.ftl
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: bug

#2524 Fixed biome underwater block crashing tests
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: bug

#2451 Added some procedure blocks
  plugins/generator-1.16.5/forge-1.16.5/procedures/compare_blockstates.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/entity_look_angle_x.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/entity_look_angle_y.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/entity_look_angle_z.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/entity_xp_until_next_level.java.ftl
  plugins/generator-1.16.5/forge-1.16.5/procedures/item_nbt_copy.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/compare_blockstates.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/entity_look_angle_x.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/entity_look_angle_y.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/entity_look_angle_z.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/entity_xp_until_next_level.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/item_nbt_copy.java.ftl
  plugins/mcreator-core/procedures/compare_blockstates.json
  plugins/mcreator-core/procedures/entity_look_angle_x.json
  plugins/mcreator-core/procedures/entity_look_angle_y.json
  plugins/mcreator-core/procedures/entity_look_angle_z.json
  plugins/mcreator-core/procedures/entity_xp_until_next_level.json
  plugins/mcreator-core/procedures/item_nbt_copy.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#2534 Removed a biome option not implemented yet
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: bug
