Repository MCreator/MCreator, pull requests merged in 2023-02, with the labels that each got.

#3502 Added recursive exclusions/inclusions support to mod element GUI
  src/main/java/net/mcreator/ui/component/UnsupportedComponent.java
  src/main/java/net/mcreator/ui/modgui/ModElementGUI.java
Labels: new feature

#3532 Fixes to texture flipping on X axis
  src/main/java/net/mcreator/ui/minecraft/TextureHolder.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
Labels: bug

#3521 Added some feature blocks and templates
  plugins/generator-1.18.2/forge-1.18.2/features/block_predicate_true.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/feature_bamboo.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/feature_block_column_simple.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/feature_delta.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/feature_random_patch_simple.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/feature_replace_sphere.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/feature_seagrass.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_carving_mask.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_offset.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_surface_relative_threshold.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/mappings/features.yaml
  plugins/generator-1.19.2/forge-1.19.2/features/block_predicate_true.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_bamboo.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_block_column_simple.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_delta.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_random_patch_simple.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_replace_sphere.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_seagrass.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_carving_mask.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_offset.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_surface_relative_threshold.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/mappings/features.yaml
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-core/features/block_predicate_true.json
  plugins/mcreator-core/features/feature_bamboo.json
  plugins/mcreator-core/features/feature_block_column_simple.json
  plugins/mcreator-core/features/feature_delta.json
  plugins/mcreator-core/features/feature_random_patch_simple.json
  plugins/mcreator-core/features/feature_replace_sphere.json
  plugins/mcreator-core/features/feature_seagrass.json
  plugins/mcreator-core/features/placement_carving_mask.json
  plugins/mcreator-core/features/placement_offset.json
  plugins/mcreator-core/features/placement_surface_relative_threshold.json
  plugins/mcreator-core/templates/ftpl/Blackstone blob feature.ftpl
  plugins/mcreator-core/templates/ftpl/Delta feature.ftpl
  plugins/mcreator-core/templates/ftpl/Lily pad patch feature.ftpl
  plugins/mcreator-core/templates/ftpl/Seagrass feature.ftpl
  plugins/mcreator-core/templates/ftpl/Tall grass patch feature.ftpl
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#3539 Fixed feature tests skipping the "Has sturdy face" block predicate
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
Labels: bug

#3540 Improved (repeating input) tests
  plugins/mcreator-core/features/block_predicate_all_of.json
  plugins/mcreator-core/features/block_predicate_any_of.json
  plugins/mcreator-core/features/block_predicate_not.json
  plugins/mcreator-core/features/int_provider_clamped.json
  plugins/mcreator-core/procedures/compare_blockstates.json
  plugins/mcreator-core/procedures/compare_dimensionids.json
  plugins/mcreator-core/procedures/compare_directions.json
  plugins/mcreator-core/procedures/compare_entities.json
  plugins/mcreator-core/procedures/compare_mcblocks.json
  plugins/mcreator-core/procedures/compare_mcitems.json
  plugins/mcreator-core/procedures/item_nbt_copy.json
  plugins/mcreator-core/procedures/projectile_shoot_from_entity.json
  plugins/mcreator-core/procedures/projectile_shoot_from_pos.json
  src/main/java/net/mcreator/blockly/data/DynamicBlockLoader.java
  src/main/java/net/mcreator/blockly/data/ExternalBlockLoader.java
  src/main/java/net/mcreator/blockly/data/ToolboxBlock.java
  src/main/java/net/mcreator/generator/blockly/BlocklyBlockCodeGenerator.java
  src/main/java/net/mcreator/ui/blockly/BlocklyEditorToolbar.java
  src/test/java/net/mcreator/integration/generator/GTCommandArgBlocks.java
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
  src/test/java/net/mcreator/integration/generator/GTProcedureBlocks.java
Labels: bug

#3545 Fixed recent workspaces not updating properly
  src/main/java/net/mcreator/ui/MCreatorApplication.java
Labels: bug

#3552 Added the make entity pathfind to coords procedure
  plugins/generator-1.18.2/forge-1.18.2/procedures/entity_pathfind_to.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/entity_stop_navigation.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/entity_pathfind_to.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/entity_stop_navigation.java.ftl
  plugins/mcreator-core/procedures/entity_pathfind_to.json
  plugins/mcreator-core/procedures/entity_set_movement.json
  plugins/mcreator-core/procedures/entity_stop_navigation.json
  plugins/mcreator-core/procedures/move_entity.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#3558 Update splash screen
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official

#3550 Improve converter tests and fix converter
  plugins/generator-1.18.2/forge-1.18.2/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/livingentity/livingentity.java.ftl
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/v2022_2/LegacyShootArrowProcedureRemover.java
  src/test/java/net/mcreator/integration/WorkspaceConvertersTest.java
  src/test/resources/workspaces/test-2020.2.zip
  src/test/resources/workspaces/test-2022.2.zip
  src/test/resources/workspaces/test-2022.3.zip
Labels: bug

#3483 Added the entity model component to GUIs and overlays
  plugins/generator-1.18.2/forge-1.18.2/templates/gui/gui_window.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/overlay.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/gui/gui_window.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/overlay.java.ftl
  plugins/mcreator-localization/help/default/gui/entity_model.md
  plugins/mcreator-localization/help/default/gui/entity_model_display_condition.md
  plugins/mcreator-localization/help/default/gui/entity_model_follow_mouse.md
  plugins/mcreator-localization/help/default/gui/entity_model_rotation.md
  plugins/mcreator-localization/help/default/gui/entity_model_scale.md
  plugins/mcreator-localization/help/fr_FR/gui/entity_model.md
  plugins/mcreator-localization/help/fr_FR/gui/entity_model_display_condition.md
  plugins/mcreator-localization/help/fr_FR/gui/entity_model_scale.md
  plugins/mcreator-localization/help/ru_RU/gui/entity_model.md
  plugins/mcreator-localization/help/ru_RU/gui/entity_model_display_condition.md
  plugins/mcreator-localization/help/ru_RU/gui/entity_model_scale.md
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/32px/addmodel.png
  src/main/java/net/mcreator/element/parts/gui/EntityModel.java
  src/main/java/net/mcreator/element/parts/gui/GUIComponent.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/EntityModelDialog.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYG.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYGEditor.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/generator/GTSampleElements.java
  src/test/java/net/mcreator/integration/ui/ModElementUITest.java
Labels: new feature

#3551 Added "Block is in block list or tag" block predicate
  plugins/generator-1.18.2/forge-1.18.2/features/block_holderset_list.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/block_holderset_tag.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/block_predicate_matching_blocks.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/utils/mcitems.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/block_holderset_list.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/block_holderset_tag.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/block_predicate_matching_blocks.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/utils/mcitems.ftl
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-core/blockly/toolboxes/toolbox_feature.xml
  plugins/mcreator-core/features/block_holderset_list.json
  plugins/mcreator-core/features/block_holderset_tag.json
  plugins/mcreator-core/features/block_predicate_matching_blocks.json
  plugins/mcreator-core/templates/ftpl/Pumpkin patch feature.ftpl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/data/BlocklyLoader.java
  src/main/java/net/mcreator/generator/GeneratorWrapper.java
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
  src/test/java/net/mcreator/integration/generator/GTProcedureBlocks.java
Labels: new feature

#3572 Fix application loader
  build.gradle
  license/Foxtrot License.txt
  src/main/java/net/mcreator/ui/MCreator.java
  src/main/java/net/mcreator/ui/MCreatorApplication.java
  src/main/java/net/mcreator/ui/SplashScreen.java
  src/main/java/net/mcreator/ui/component/util/EDTUtils.java
  src/main/java/net/mcreator/util/TerribleModuleHacks.java
Labels: bug

#3548 Call loot table procedure block
  plugins/generator-1.18.2/forge-1.18.2/procedures/entity_loot_table_foreach.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/loot_table_foreach.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/procedures/world_loot_table_foreach.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/entity_loot_table_foreach.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/loot_table_foreach.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/world_loot_table_foreach.java.ftl
  plugins/mcreator-core/procedures/entity_loot_table_foreach.json
  plugins/mcreator-core/procedures/loot_table_foreach.json
  plugins/mcreator-core/procedures/world_loot_table_foreach.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#3566 Improve the splash screen
  src/main/java/net/mcreator/ui/SplashScreen.java
  src/main/java/net/mcreator/ui/component/SplashScreenPanel.java
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
  src/main/java/net/mcreator/util/image/ImageUtils.java
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official

#3578 Removed GUI Limitations
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYGEditor.java
Labels: bug

#3588 Create entity procedure block
  plugins/generator-1.18.2/forge-1.18.2/procedures/entity_create.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/entity_create.java.ftl
  plugins/mcreator-core/procedures/entity_create.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#3591 Fixed tests
  src/test/java/net/mcreator/integration/generator/GTProcedureBlocks.java
Labels: bug

#3598 Fixed tests
  plugins/mcreator-core/procedures/entity_create.json
Labels: bug

#3592 Added some feature templates
  plugins/mcreator-core/templates/ftpl/Brown mushroom patch feature.ftpl
  plugins/mcreator-core/templates/ftpl/Crimson fungus feature.ftpl
  plugins/mcreator-core/templates/ftpl/Forest rock feature.ftpl
  plugins/mcreator-core/templates/ftpl/Nether fire patch feature.ftpl
  plugins/mcreator-core/templates/ftpl/Placement - Check for solid face below.ftpl
  plugins/mcreator-core/templates/ftpl/Placement - Once every 5 chunks on the surface.ftpl
  plugins/mcreator-core/templates/ftpl/Placement - Repeated twice on the surface.ftpl
Labels: new feature
