Repository MCreator/MCreator, pull requests merged in 2023-05, with the labels that each got.

#3847 Fixed procedure selectors' enabling/disabling
  src/main/java/net/mcreator/ui/procedure/RetvalProcedureSelector.java
Labels: bug

#3823 Recent plugin changes
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/plugin/PluginLoader.java
  src/main/java/net/mcreator/plugin/PluginUpdateInfo.java
  src/main/java/net/mcreator/ui/dialogs/UpdatePluginDialog.java
Labels: new feature, community review

#3850 Added isRaided and isVillage procedure blocks
  plugins/generator-1.19.2/forge-1.19.2/procedures/world_data_israided.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/world_data_isvillage.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/world_data_israided.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/world_data_isvillage.java.ftl
  plugins/mcreator-core/procedures/world_data_israided.json
  plugins/mcreator-core/procedures/world_data_isvillage.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature, community review

#3854 Re-add RPC for aarch64
  lib/discord-rpc.jar
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/component/util/DiscordClient.java
Labels: community review

#3842 Support for adding custom vertical tabs to a workspace
  src/main/java/net/mcreator/ui/workspace/AbstractWorkspacePanel.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanelLocalizations.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanelVCS.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanelVariables.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelResources.java
Labels: new feature

#3657 Added ore features
  plugins/generator-1.19.2/forge-1.19.2/features/feature_ore.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_replace_single_block.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_scattered_ore.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/ore_target.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/rule_test_always_true.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/rule_test_block_match.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/rule_test_blockstate_match.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/rule_test_random_block_match.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/rule_test_random_blockstate_match.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/rule_test_tag_match.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/generator.yaml
  plugins/generator-1.19.2/forge-1.19.2/mappings/features.yaml
  plugins/generator-1.19.2/forge-1.19.2/templates/modbase/accesstransformer.cfg.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/feature_ore.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/feature_replace_single_block.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/feature_scattered_ore.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/ore_target.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/rule_test_always_true.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/rule_test_block_match.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/rule_test_blockstate_match.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/rule_test_random_block_match.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/rule_test_random_blockstate_match.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/rule_test_tag_match.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/generator.yaml
  plugins/generator-1.19.4/forge-1.19.4/mappings/features.yaml
  plugins/generator-1.19.4/forge-1.19.4/templates/modbase/accesstransformer.cfg.ftl
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-core/blockly/toolboxes/toolbox_feature.xml
  plugins/mcreator-core/features/feature_ore.json
  plugins/mcreator-core/features/feature_replace_single_block.json
  plugins/mcreator-core/features/feature_scattered_ore.json
  plugins/mcreator-core/features/ore_target.json
  plugins/mcreator-core/features/rule_test_always_true.json
  plugins/mcreator-core/features/rule_test_block_match.json
  plugins/mcreator-core/features/rule_test_blockstate_match.json
  plugins/mcreator-core/features/rule_test_random_block_match.json
  plugins/mcreator-core/features/rule_test_random_blockstate_match.json
  plugins/mcreator-core/features/rule_test_tag_match.json
  plugins/mcreator-core/templates/ftpl/Ore features - Ancient debris.ftpl
  plugins/mcreator-core/templates/ftpl/Ore features - Buried lapis ore.ftpl
  plugins/mcreator-core/templates/ftpl/Ore features - Iron ore.ftpl
  plugins/mcreator-core/templates/ftpl/Ore features - Nether quartz ore.ftpl
  plugins/mcreator-core/templates/ftpl/Ore features - Underground dirt blobs.ftpl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/data/BlocklyLoader.java
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
Labels: new feature

#3865 Pattern match fix
  plugins/generator-1.19.2/forge-1.19.2/procedures/entity_has_achievement.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/world_data_isday.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/world_data_israided.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/world_data_isvillage.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/advancement_isequalto.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/blockat_plant_type.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_check_creature_type.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_has_achievement.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_has_screen_open.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_haspotioneffect.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/item_can_smelt.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/world_data_is_block_powered.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/world_data_isday.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/world_data_israided.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/world_data_isvillage.java.ftl
Labels: bug

#3867 Maker tool recipe fixes
  src/main/java/net/mcreator/ui/dialogs/tools/ArmorPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/OrePackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/ToolPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/WoodPackMakerTool.java
Labels: bug

#3862 Workspace selector rework
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/impfile.png
  plugins/mcreator-themes/themes/default_dark/images/opnwrk.png
  plugins/mcreator-themes/themes/default_dark/images/vcsclone.png
  plugins/mcreator-themes/themes/default_light/images/impfile.png
  plugins/mcreator-themes/themes/default_light/images/opnwrk.png
  plugins/mcreator-themes/themes/default_light/images/vcsclone.png
  plugins/mcreator-themes/themes/matrix/images/impfile.png
  plugins/mcreator-themes/themes/matrix/images/opnwrk.png
  plugins/mcreator-themes/themes/matrix/images/vcsclone.png
  src/main/java/net/mcreator/ui/MCreatorApplication.java
  src/main/java/net/mcreator/ui/workspace/selector/RecentWorkspacesRenderer.java
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
Labels: official

#3586 Added button to generate bounding box from JSON model
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/component/TechnicalButton.java
  src/main/java/net/mcreator/ui/init/L10N.java
  src/main/java/net/mcreator/ui/minecraft/JEntriesList.java
  src/main/java/net/mcreator/ui/minecraft/boundingboxes/JBoundingBoxList.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/ModElementChangedListener.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
Labels: new feature

#3874 Improved progress dialog
  src/main/java/net/mcreator/ui/dialogs/ProgressDialog.java
  src/main/java/net/mcreator/ui/views/AnimationMakerView.java
Labels: official

#3878 Application loading event
  src/main/java/net/mcreator/plugin/events/WorkspaceSelectorLoadedEvent.java
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
Labels: new feature

#3883 Minor changes
  src/main/java/net/mcreator/generator/template/base/DefaultFreemarkerConfiguration.java
  src/main/java/net/mcreator/ui/modgui/RecipeGUI.java
Labels: new feature

#3869 Added weighted int provider, weighted and uniform height provider
  plugins/generator-1.19.2/forge-1.19.2/features/height_provider_uniform.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/height_provider_weighted.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/int_provider_weighted.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/height_provider_uniform.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/height_provider_weighted.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/int_provider_weighted.json.ftl
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-core/features/height_provider_uniform.json
  plugins/mcreator-core/features/height_provider_weighted.json
  plugins/mcreator-core/features/int_provider_weighted.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#3544 Get player spawn coordinates procedure blocks
  plugins/generator-1.19.2/forge-1.19.2/procedures/entity_get_spawn_x.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/entity_get_spawn_y.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/entity_get_spawn_z.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_get_spawn_x.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_get_spawn_y.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_get_spawn_z.java.ftl
  plugins/mcreator-core/procedures/entity_get_spawn_x.json
  plugins/mcreator-core/procedures/entity_get_spawn_y.json
  plugins/mcreator-core/procedures/entity_get_spawn_z.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#3672 Disable integrated igniter
  plugins/generator-1.19.2/forge-1.19.2/dimension.definition.yaml
  plugins/generator-1.19.2/forge-1.19.2/templates/elementinits/items.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/dimension.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/templates/elementinits/items.java.ftl
  plugins/mcreator-core/templates/ptpl/Make portal to a dimension using custom igniter item.ptpl
  plugins/mcreator-localization/help/default/dimension/enable_igniter.md
  plugins/mcreator-localization/help/fr_FR/dimension/enable_igniter.md
  plugins/mcreator-localization/help/ru_RU/dimension/enable_igniter.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Dimension.java
  src/main/java/net/mcreator/minecraft/MinecraftImageGenerator.java
  src/main/java/net/mcreator/ui/modgui/DimensionGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#3882 MacOS adhoc sign and AArch64 support
  platform/mac/mac.gradle
  platform/mac/mcreator.sh
  platform/mac/mcreator_aarch64
  platform/mac/mcreator_x64
Labels: bug
