Repository MCreator/MCreator, pull requests merged in 2023-07, with the labels that each got.

#3999 Change some blockitem entries
  plugins/generator-1.19.2/datapack-1.19.2/mappings/blocksitems.yaml
  plugins/generator-1.19.4/datapack-1.19.4/mappings/blocksitems.yaml
  plugins/generator-addon-1.20.x/addon-1.20.x/mappings/blocksitems.yaml
  plugins/mcreator-core/datalists/blocksitems.yaml
  plugins/mcreator-core/datalists/icons/CONCRETE.png
  plugins/mcreator-core/datalists/icons/CONCRETE_POWDER.png
Labels: community review

#4008 Fix #4003
  platform/mac/mac.gradle
Labels: bug, official

#3597 Image asset view
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/io/tree/FileNode.java
  src/main/java/net/mcreator/io/zip/ZipIO.java
  src/main/java/net/mcreator/ui/FileOpener.java
  src/main/java/net/mcreator/ui/ide/ProjectFileOpener.java
  src/main/java/net/mcreator/ui/views/editor/image/ImageMakerView.java
Labels: new feature

#3982 Added some advanced features
  plugins/generator-1.19.2/forge-1.19.2/features/feature_no_op.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_random_patch.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_simple_random_selector.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placed_feature_inline.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/mappings/features.yaml
  plugins/generator-1.19.2/forge-1.19.2/utils/mcelements.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/feature_no_op.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/feature_random_patch.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/feature_simple_random_selector.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/placed_feature_inline.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/mappings/features.yaml
  plugins/generator-1.19.4/forge-1.19.4/utils/mcelements.ftl
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-core/blockly/toolboxes/toolbox_feature.xml
  plugins/mcreator-core/features/feature_no_op.json
  plugins/mcreator-core/features/feature_random_patch.json
  plugins/mcreator-core/features/feature_simple_random_selector.json
  plugins/mcreator-core/features/placed_feature_inline.json
  plugins/mcreator-core/features/placement_biome_filter.json
  plugins/mcreator-core/templates/ftpl/Plant features - Cactus patch.ftpl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/data/BlocklyLoader.java
  src/main/java/net/mcreator/generator/blockly/BlocklyBlockCodeGenerator.java
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
Labels: new feature

#4027 Property data changes
  src/main/java/net/mcreator/ui/minecraft/states/PropertyData.java
Labels: bug

#4020 Fix feature's basetype on Fabric
  src/main/java/net/mcreator/element/types/Feature.java
Labels: bug

#4050 Fix #4035
  plugins/generator-1.19.2/forge-1.19.2/procedures/gui_clear_slot.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/gui_damage_item.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/gui_get_amount_inslot.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/gui_get_item_inslot.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/gui_remove_items.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/gui_set_items.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/gui_clear_slot.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/gui_damage_item.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/gui_get_amount_inslot.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/gui_get_item_inslot.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/gui_remove_items.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/gui_set_items.java.ftl
  plugins/generator-1.20.1-ref/forge-1.19.4/procedures/gui_clear_slot.java.ftl
  plugins/generator-1.20.1-ref/forge-1.19.4/procedures/gui_damage_item.java.ftl
  plugins/generator-1.20.1-ref/forge-1.19.4/procedures/gui_get_amount_inslot.java.ftl
  plugins/generator-1.20.1-ref/forge-1.19.4/procedures/gui_get_item_inslot.java.ftl
  plugins/generator-1.20.1-ref/forge-1.19.4/procedures/gui_remove_items.java.ftl
  plugins/generator-1.20.1-ref/forge-1.19.4/procedures/gui_set_items.java.ftl
Labels: bug

#4089 Proper application exit
  src/main/java/net/mcreator/ui/MCreatorApplication.java
Labels: bug
