Repository MCreator/MCreator, pull requests merged in 2023-08, with the labels that each got.

#4070 Improve broken GE detection
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Fluid.java
  src/main/java/net/mcreator/element/types/GameRule.java
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/element/types/KeyBinding.java
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/main/java/net/mcreator/element/types/LootTable.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/element/types/RangedItem.java
  src/main/java/net/mcreator/element/types/Recipe.java
  src/main/java/net/mcreator/element/types/Tag.java
  src/main/java/net/mcreator/element/types/Tool.java
  src/main/java/net/mcreator/ui/action/impl/workspace/RegenerateCodeAction.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
  src/main/java/net/mcreator/workspace/elements/ModElementManager.java
  src/main/java/net/mcreator/workspace/misc/WorkspaceInfo.java
  src/test/java/net/mcreator/integration/WorkspaceConvertersTest.java
Labels: bug, official, community review

#4129 Fix #4051
  plugins/generator-1.19.2/forge-1.19.2/templates/gui/gui_window.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/gui/gui_window.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/gui/gui_window.java.ftl
Labels: bug

#4135 Fix #4134
  plugins/generator-1.19.2/forge-1.19.2/templates/particle.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/particle.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/particle.java.ftl
Labels: bug

#4145 Missing block models
  plugins/mcreator-localization/help/default/block/model.md
Labels: bug

#4147 Fix #4081
  plugins/generator-1.19.4/forge-1.19.4/templates/item/item.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/musicdisc.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/tool.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/utils/triggers.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/item/item.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/musicdisc.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/tool.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/utils/triggers.java.ftl
  plugins/mcreator-localization/help/default/item/when_stopped_using.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/MusicDisc.java
  src/main/java/net/mcreator/element/types/Tool.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/main/java/net/mcreator/ui/modgui/MusicDiscGUI.java
  src/main/java/net/mcreator/ui/modgui/ToolGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: bug, community review

#4009 New DamageSource-related triggers
  plugins/generator-1.19.4/forge-1.19.4/triggers/entity_blocks.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/triggers/entity_uses_totem.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/triggers/entity_blocks.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/triggers/entity_uses_totem.java.ftl
  plugins/mcreator-core/triggers/entity_blocks.json
  plugins/mcreator-core/triggers/entity_uses_totem.json
  plugins/mcreator-localization/lang/texts.properties
Labels: community review

#4155 Fixed missing step sound icons
  plugins/mcreator-core/datalists/stepsounds.yaml
Labels: bug

#4165 Bugfix - Added missing sound selection title
  plugins/mcreator-localization/lang/texts.properties
Labels: bug

#4161 Non-transparent blockly
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/styles/blockly.css
  plugins/mcreator-themes/themes/matrix/styles/blockly.css
  plugins/mcreator-themes/themes/midnight/styles/blockly.css
  src/main/java/net/mcreator/preferences/data/BlocklySection.java
  src/main/java/net/mcreator/ui/blockly/BlocklyPanel.java
  src/main/resources/blockly/css/mcreator_blockly.css
  src/main/resources/blockly/css/mcreator_blockly_transparent.css
  src/main/resources/blockly/css/mcreator_blockly_unixfix.css
Labels: official

#4159 Merge static and double plant generation types
  plugins/generator-1.19.4/forge-1.19.4/templates/plant/placed_plantgen.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/plant/placed_plantgen.json.ftl
  plugins/mcreator-localization/help/default/plant/generation_type.md
  plugins/mcreator-localization/help/default/plant/static_generation_type.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2023_3/PlantGenerationTypeConverter.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: community review

#4176 Revert back to bright splash screen
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official

#4181 Fix generator stats problem with plugins
  src/main/java/net/mcreator/ui/dialogs/workspace/GeneratorSelector.java
  src/main/java/net/mcreator/ui/init/L10N.java
Labels: bug, official
