Repository MCreator/MCreator, pull requests merged in 2023-01, with the labels that each got.

#3426 Templates generation fixes
  src/main/java/net/mcreator/generator/Generator.java
  src/main/java/net/mcreator/generator/ListTemplate.java
  src/main/java/net/mcreator/generator/template/TemplateExpressionParser.java
Labels: bug

#3421 Changed tabbed pane colors to make scroll buttons visible
  src/main/java/net/mcreator/ui/dialogs/TextureMappingDialog.java
  src/main/java/net/mcreator/ui/laf/MCreatorTheme.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanelLocalizations.java
Labels: bug

#3316 Add custom armor item model support
  plugins/generator-1.18.2/forge-1.18.2/armor.definition.yaml
  plugins/generator-1.18.2/forge-1.18.2/templates/json/item.json.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/json/item_cmodel.json.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/json/item_cmodel_obj.json.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/json/tool.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/armor.definition.yaml
  plugins/generator-1.19.2/forge-1.19.2/templates/json/item.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/json/item_cmodel.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/json/item_cmodel_obj.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/json/tool.json.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Armor.java
  src/main/java/net/mcreator/ui/modgui/ArmorGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#3431 Templates generation fixes
  src/main/java/net/mcreator/generator/Generator.java
Labels: bug

#3434 Added int providers and count placements
  plugins/generator-1.18.2/forge-1.18.2/features/int_provider_biased_to_bottom.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/int_provider_clamped.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/int_provider_clamped_normal.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/int_provider_constant.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/int_provider_uniform.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_count.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_count_on_every_layer.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_noise_based_count.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/placement_noise_threshold_count.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/int_provider_biased_to_bottom.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/int_provider_clamped.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/int_provider_clamped_normal.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/int_provider_constant.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/int_provider_uniform.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_count.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_count_on_every_layer.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_noise_based_count.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/placement_noise_threshold_count.json.ftl
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-core/features/$intproviders.json
  plugins/mcreator-core/features/int_provider_biased_to_bottom.json
  plugins/mcreator-core/features/int_provider_clamped.json
  plugins/mcreator-core/features/int_provider_clamped_normal.json
  plugins/mcreator-core/features/int_provider_constant.json
  plugins/mcreator-core/features/int_provider_uniform.json
  plugins/mcreator-core/features/placement_count.json
  plugins/mcreator-core/features/placement_count_on_every_layer.json
  plugins/mcreator-core/features/placement_noise_based_count.json
  plugins/mcreator-core/features/placement_noise_threshold_count.json
  plugins/mcreator-localization/lang/texts.properties
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
Labels: new feature

#3443 List templates targeting the same file were still replacing each other
  src/main/java/net/mcreator/generator/Generator.java
  src/main/java/net/mcreator/generator/GeneratorTemplatesList.java
  src/main/java/net/mcreator/generator/ListTemplate.java
  src/main/java/net/mcreator/ui/workspace/ModElementCodeDropdown.java
Labels: bug

#3365 Added Item Harvest Level Procedure
  plugins/generator-1.18.2/forge-1.18.2/procedures/item_get_harvest_level.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/item_get_harvest_level.java.ftl
  plugins/mcreator-core/procedures/item_get_harvest_level.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#3412 Added bone meal properties to blocks and plants
  plugins/generator-1.18.2/forge-1.18.2/templates/block/block.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/templates/plant/plant.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/utils/triggers.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/block/block.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/plant/plant.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/utils/triggers.java.ftl
  plugins/mcreator-localization/help/default/block/bonemeal_success_condition.md
  plugins/mcreator-localization/help/default/block/bonemeal_target_condition.md
  plugins/mcreator-localization/help/default/block/is_bonemealable.md
  plugins/mcreator-localization/help/default/block/on_bonemeal_success.md
  plugins/mcreator-localization/help/fr_FR/block/bonemeal_success_condition.md
  plugins/mcreator-localization/help/fr_FR/block/bonemeal_target_condition.md
  plugins/mcreator-localization/help/fr_FR/block/is_bonemealable.md
  plugins/mcreator-localization/help/fr_FR/block/on_bonemeal_success.md
  plugins/mcreator-localization/help/ru_RU/block/bonemeal_success_condition.md
  plugins/mcreator-localization/help/ru_RU/block/bonemeal_target_condition.md
  plugins/mcreator-localization/help/ru_RU/block/is_bonemealable.md
  plugins/mcreator-localization/help/ru_RU/block/on_bonemeal_success.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/generator/GTSampleElements.java
  src/test/java/net/mcreator/integration/ui/ModElementUITest.java
Labels: new feature

#3413 Added some feature blocks
  plugins/generator-1.18.2/forge-1.18.2/features/feature_coral_claw.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/feature_coral_mushroom.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/feature_coral_tree.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/feature_forest_rock.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/feature_huge_fungus.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/height_provider_biased_to_bottom.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/height_provider_trapezoid.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/height_provider_very_biased_to_bottom.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/mappings/features.yaml
  plugins/generator-1.19.2/forge-1.19.2/features/feature_coral_claw.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_coral_mushroom.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_coral_tree.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_forest_rock.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/feature_huge_fungus.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/height_provider_biased_to_bottom.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/height_provider_trapezoid.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/height_provider_very_biased_to_bottom.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/mappings/features.yaml
  plugins/mcreator-core/features/feature_coral_claw.json
  plugins/mcreator-core/features/feature_coral_mushroom.json
  plugins/mcreator-core/features/feature_coral_tree.json
  plugins/mcreator-core/features/feature_forest_rock.json
  plugins/mcreator-core/features/feature_huge_fungus.json
  plugins/mcreator-core/features/height_provider_biased_to_bottom.json
  plugins/mcreator-core/features/height_provider_trapezoid.json
  plugins/mcreator-core/features/height_provider_very_biased_to_bottom.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#3461 Added new events for Java plugins
  src/main/java/net/mcreator/plugin/events/ui/ModElementGUIEvent.java
  src/main/java/net/mcreator/plugin/events/ui/PreferencesDialogEvent.java
  src/main/java/net/mcreator/plugin/events/ui/TabEvent.java
  src/main/java/net/mcreator/plugin/events/workspace/MCreatorLoadedEvent.java
  src/main/java/net/mcreator/plugin/events/workspace/WorkspaceRefactoringEvent.java
  src/main/java/net/mcreator/plugin/events/workspace/WorkspaceSavedEvent.java
  src/main/java/net/mcreator/ui/MCreator.java
  src/main/java/net/mcreator/ui/action/impl/workspace/WorkspaceSettingsAction.java
  src/main/java/net/mcreator/ui/modgui/ModElementGUI.java
  src/main/java/net/mcreator/workspace/WorkspaceFileManager.java
Labels: new feature

#3465 Minor feature improvements
  plugins/mcreator-core/blockly/toolboxes/toolbox_feature.xml
  plugins/mcreator-core/features/$blockpredicates.json
  plugins/mcreator-core/features/$features.json
  plugins/mcreator-core/features/$heightplacements.json
  plugins/mcreator-core/features/$intproviders.json
  plugins/mcreator-core/features/$placements.json
  plugins/mcreator-core/features/placement_biome_filter.json
  plugins/mcreator-core/features/placement_block_survival_filter.json
  plugins/mcreator-core/features/placement_heightmap.json
  plugins/mcreator-core/features/placement_rarity.json
  plugins/mcreator-core/features/placement_surface_water_depth.json
  src/main/java/net/mcreator/blockly/data/BlocklyLoader.java
  src/main/java/net/mcreator/blockly/data/ToolboxType.java
  src/main/java/net/mcreator/ui/modgui/FeatureGUI.java
Labels: new feature

#3462 Moved the "Provided MCItems" logic to GeneratableElement
  plugins/generator-1.18.2/forge-1.18.2/templates/elementinits/items.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/elementinits/items.java.ftl
  plugins/mcreator-themes/themes/default_dark/images/spawnegg.png
  src/main/java/net/mcreator/element/ModElementType.java
  src/main/java/net/mcreator/element/ModElementTypeLoader.java
  src/main/java/net/mcreator/element/RecipeType.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/fv15/DimensionPortalSelectedFixer.java
  src/main/java/net/mcreator/element/converter/fv19/FluidBucketSelectedFixer.java
  src/main/java/net/mcreator/element/types/Armor.java
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Dimension.java
  src/main/java/net/mcreator/element/types/Fluid.java
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/main/java/net/mcreator/element/types/MusicDisc.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/element/types/RangedItem.java
  src/main/java/net/mcreator/element/types/Tool.java
  src/main/java/net/mcreator/element/types/interfaces/IItem.java
  src/main/java/net/mcreator/element/types/interfaces/IMCItemProvider.java
  src/main/java/net/mcreator/generator/GeneratorWrapper.java
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/minecraft/MCItem.java
  src/main/java/net/mcreator/minecraft/MinecraftImageGenerator.java
  src/main/java/net/mcreator/ui/dialogs/tools/ArmorPackMakerTool.java
  src/main/java/net/mcreator/ui/init/TiledImageCache.java
  src/main/java/net/mcreator/ui/modgui/ArmorGUI.java
  src/main/java/net/mcreator/ui/modgui/DimensionGUI.java
  src/main/java/net/mcreator/ui/modgui/FluidGUI.java
  src/main/java/net/mcreator/workspace/elements/ModElement.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: bug, new feature

#3476 Fix #3467
  plugins/generator-1.18.2/forge-1.18.2/templates/item/item.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/item/item.java.ftl
Labels: bug

#3481 Fixed mod element conversion method calling itself
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/v2021_2/BooleanGameRulesConverter.java
  src/main/java/net/mcreator/element/parts/procedure/Procedure.java
  src/main/java/net/mcreator/generator/Generator.java
  src/main/java/net/mcreator/ui/action/impl/workspace/RegenerateCodeAction.java
  src/main/java/net/mcreator/ui/dialogs/ElementOrderEditor.java
  src/main/java/net/mcreator/ui/dialogs/tools/ArmorPackMakerTool.java
  src/main/java/net/mcreator/ui/modgui/GameRuleGUI.java
  src/main/java/net/mcreator/ui/modgui/ModElementGUI.java
  src/main/java/net/mcreator/workspace/ShareableZIPManager.java
  src/main/java/net/mcreator/workspace/Workspace.java
  src/main/java/net/mcreator/workspace/elements/ModElement.java
  src/main/java/net/mcreator/workspace/elements/ModElementManager.java
  src/main/java/net/mcreator/workspace/misc/WorkspaceInfo.java
Labels: bug

#3451 "Any of" and "All of" block predicates
  plugins/generator-1.18.2/forge-1.18.2/features/block_predicate_all_of.java.ftl
  plugins/generator-1.18.2/forge-1.18.2/features/block_predicate_any_of.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/block_predicate_all_of.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/block_predicate_any_of.json.ftl
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-core/features/block_predicate_all_of.json
  plugins/mcreator-core/features/block_predicate_any_of.json
  plugins/mcreator-localization/lang/texts.properties
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
Labels: new feature

#3466 Does entity have a selected screen open procedure
  plugins/generator-1.18.2/forge-1.18.2/procedures/entity_has_screen_open.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/entity_has_screen_open.java.ftl
  plugins/mcreator-core/procedures/entity_has_screen_open.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#3509 Tests for FV converters
  src/main/java/net/mcreator/workspace/Workspace.java
  src/test/java/net/mcreator/integration/WorkspaceConvertersTest.java
  src/test/resources/workspaces/test-2019.5.zip
  src/test/resources/workspaces/test-2020.2.zip
  src/test/resources/workspaces/test-2021.3.zip
  src/test/resources/workspaces/test-2022.2.zip
Labels: official

#3478 Small QOL features to the workspace selector
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/MCreatorApplication.java
  src/main/java/net/mcreator/ui/action/impl/workspace/WorkspaceSettingsAction.java
  src/main/java/net/mcreator/ui/workspace/selector/RecentWorkspaceEntry.java
  src/main/java/net/mcreator/ui/workspace/selector/RecentWorkspacesRenderer.java
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
Labels: new feature
