Repository MCreator/MCreator, pull requests merged in 2023-04, with the labels that each got.

#3744 Fixed local and remote commits confusion
  src/main/java/net/mcreator/ui/vcs/MCreatorWorkspaceSyncHandler.java
  src/main/java/net/mcreator/ui/vcs/MergeHandleComponent.java
Labels: bug

#3745 Fixed #3738
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/InputSlotDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/LabelDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/OutputSlotDialog.java
  src/main/java/net/mcreator/ui/procedure/LogicProcedureSelector.java
  src/main/java/net/mcreator/ui/procedure/NumberProcedureSelector.java
  src/main/java/net/mcreator/ui/procedure/RetvalProcedureSelector.java
  src/main/java/net/mcreator/ui/procedure/StringProcedureSelector.java
Labels: bug

#3753 Fixed 1.19.4 ore generation ignoring dimension/generation condition
  plugins/generator-1.19.4/forge-1.19.4/templates/block/configured_oregen.json.ftl
Labels: bug

#3764 Add 1.19.4 textures
  plugins/mcreator-core/datalists/blocksitems.yaml
  plugins/mcreator-core/datalists/icons/DECORATED_POT.png
  plugins/mcreator-core/datalists/icons/ENDER_DRAGON_SPAWN_EGG.png
  plugins/mcreator-core/datalists/icons/IRON_GOLEM_SPAWN_EGG.png
  plugins/mcreator-core/datalists/icons/SNOW_GOLEM_SPAWN_EGG.png
  plugins/mcreator-core/datalists/icons/SUSPICIOUS_SAND.png
  plugins/mcreator-core/datalists/icons/WITHER_SPAWN_EGG.png
Labels: new feature, official

#3784 [1.19.4] Ported remaining entity data procedures
  plugins/generator-1.18.2/forge-1.18.2/procedures/entity_submerged_height.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/procedures/entity_submerged_height.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_canusecommand.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_check_creature_type.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_get_scoreboard_score.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_haspotioneffect.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_name.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_nbt_logic_get.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_nbt_num_get.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_nbt_text_get.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_potioneffectlevel.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_potioneffectremaining.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_registry_name.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_size_height.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_size_width.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_submerged_height.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/itementity_to_mcitem.java.ftl
Labels: bug

#3821 Legacy generator switch bug fix
  plugins/generator-1.19.4/forge-1.19.4/generator.yaml
  src/main/java/net/mcreator/element/parts/procedure/Procedure.java
  src/main/java/net/mcreator/generator/GeneratorTokens.java
  src/main/java/net/mcreator/generator/GeneratorUtils.java
  src/main/java/net/mcreator/generator/setup/WorkspaceGeneratorSetup.java
  src/main/java/net/mcreator/generator/setup/folders/AbstractFolderStructure.java
  src/main/java/net/mcreator/generator/setup/folders/CurrentFolderStructure.java
  src/main/java/net/mcreator/generator/setup/folders/Pre1193FolderStructure.java
  src/main/java/net/mcreator/workspace/Workspace.java
Labels: bug, community review

#3612 Added (simple) geode feature block
  plugins/generator-1.19.2/forge-1.19.2/features/feature_geode_simple.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/mappings/features.yaml
  plugins/generator-1.19.4/forge-1.19.4/features/feature_geode_simple.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/mappings/features.yaml
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-core/features/feature_geode_simple.json
  plugins/mcreator-core/templates/ftpl/Geode feature.ftpl
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#3668 Compact substring procedure block
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/toolboxes/toolbox_procedure.xml
  src/main/java/net/mcreator/blockly/java/blocks/TextSubstring.java
Labels: new feature
