Repository MCreator/MCreator, pull requests merged in 2023-11, with the labels that each got.

#3500 Search usages system backend
  src/main/java/net/mcreator/element/ModElementType.java
  src/main/java/net/mcreator/element/parts/gui/Image.java
  src/main/java/net/mcreator/element/parts/gui/ImageButton.java
  src/main/java/net/mcreator/element/parts/procedure/Procedure.java
  src/main/java/net/mcreator/element/types/Achievement.java
  src/main/java/net/mcreator/element/types/Armor.java
  src/main/java/net/mcreator/element/types/Biome.java
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Dimension.java
  src/main/java/net/mcreator/element/types/Enchantment.java
  src/main/java/net/mcreator/element/types/Feature.java
  src/main/java/net/mcreator/element/types/Fluid.java
  src/main/java/net/mcreator/element/types/GUI.java
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/main/java/net/mcreator/element/types/LootTable.java
  src/main/java/net/mcreator/element/types/MusicDisc.java
  src/main/java/net/mcreator/element/types/Overlay.java
  src/main/java/net/mcreator/element/types/Painting.java
  src/main/java/net/mcreator/element/types/Particle.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/element/types/Potion.java
  src/main/java/net/mcreator/element/types/PotionEffect.java
  src/main/java/net/mcreator/element/types/Projectile.java
  src/main/java/net/mcreator/element/types/Recipe.java
  src/main/java/net/mcreator/element/types/Structure.java
  src/main/java/net/mcreator/element/types/Tag.java
  src/main/java/net/mcreator/element/types/Tool.java
  src/main/java/net/mcreator/element/types/VillagerProfession.java
  src/main/java/net/mcreator/element/types/VillagerTrade.java
  src/main/java/net/mcreator/ui/modgui/ProcedureGUI.java
  src/main/java/net/mcreator/workspace/references/ModElementReference.java
  src/main/java/net/mcreator/workspace/references/ReferencesFinder.java
  src/main/java/net/mcreator/workspace/references/ResourceReference.java
  src/main/java/net/mcreator/workspace/references/TextureReference.java
  src/main/java/net/mcreator/workspace/resources/Model.java
  src/main/java/net/mcreator/workspace/resources/TexturedModel.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/workspace/ReferencesFinderTest.java
Labels: new feature, community review

#4355 Fix #4354
  src/main/java/net/mcreator/element/converter/v2023_4/RangedItemToProjectileAndItemConverter.java
Labels: bug

#4348 Preload workspace in the foreground
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/MCreator.java
  src/main/java/net/mcreator/ui/component/BlockingGlassPane.java
Labels: official, community review

#4300 Search usages system frontend
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/dialogs/SearchUsagesDialog.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
  src/test/java/net/mcreator/integration/ui/DialogsTest.java
Labels: new feature

#4331 Update JDK to Adoptium 17.0.9+9
  .github/workflows/deploy.yml
  .github/workflows/documentation.yml
  .github/workflows/test.yml
  platform/setup.gradle
Labels: official

#4360 Search usages system frontend (pt. II)
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/workspace/WorkspacePanelLocalizations.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanelVariables.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelModels.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelSounds.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelStructures.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelTextures.java
Labels: new feature, community review

#4347 Fix #4345
  src/main/java/net/mcreator/ui/MCreator.java
  src/main/java/net/mcreator/ui/action/impl/workspace/RegenerateCodeAction.java
  src/main/java/net/mcreator/ui/action/impl/workspace/WorkspaceSettingsAction.java
  src/main/java/net/mcreator/ui/dialogs/tools/ArmorPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/InjectTagsTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/MaterialPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/OrePackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/ToolPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/WoodPackMakerTool.java
  src/main/java/net/mcreator/ui/gradle/GradleConsole.java
  src/main/java/net/mcreator/ui/laf/renderer/elementlist/DetailsIconModListRender.java
  src/main/java/net/mcreator/ui/laf/renderer/elementlist/LargeIconModListRender.java
  src/main/java/net/mcreator/ui/laf/renderer/elementlist/ListIconModListRender.java
  src/main/java/net/mcreator/ui/laf/renderer/elementlist/MediumIconModListRender.java
  src/main/java/net/mcreator/ui/laf/renderer/elementlist/SmallIconModListRender.java
  src/main/java/net/mcreator/ui/laf/renderer/elementlist/TilesModListRender.java
  src/main/java/net/mcreator/ui/views/editor/image/ImageMakerView.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
  src/main/java/net/mcreator/ui/workspace/resources/ResourceFilterModel.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelModels.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelScreenshots.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelSounds.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelStructures.java
Labels: bug, official, community review

#2007 Added custom entity data parameters
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_data_integer_get.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_data_integer_set.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_data_logic_get.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_data_logic_set.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_data_string_get.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_data_string_set.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/entity_data_integer_get.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/entity_data_integer_set.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/entity_data_logic_get.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/entity_data_logic_set.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/entity_data_string_get.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/entity_data_string_set.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/livingentity/livingentity.java.ftl
  plugins/mcreator-core/blockly/js/field_data_list_selector.js
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-core/procedures/entity_data_integer_get.json
  plugins/mcreator-core/procedures/entity_data_integer_set.json
  plugins/mcreator-core/procedures/entity_data_logic_get.json
  plugins/mcreator-core/procedures/entity_data_logic_set.json
  plugins/mcreator-core/procedures/entity_data_string_get.json
  plugins/mcreator-core/procedures/entity_data_string_set.json
  plugins/mcreator-localization/help/default/entity/data_default_value.md
  plugins/mcreator-localization/help/default/entity/data_name.md
  plugins/mcreator-localization/help/default/entity/data_type.md
  plugins/mcreator-localization/help/default/entity/entity_data.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/main/java/net/mcreator/ui/minecraft/states/PropertyDataWithValue.java
  src/main/java/net/mcreator/ui/minecraft/states/entity/JEntityDataEntry.java
  src/main/java/net/mcreator/ui/minecraft/states/entity/JEntityDataList.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/generator/BlocklyTestUtil.java
Labels: new feature, community review

#4380 Optimised recipe JSON
  plugins/generator-1.19.4/datapack-1.19.4/templates/recipe/crafting.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/recipe/crafting.json.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/templates/recipe/crafting.json.ftl
  src/main/java/net/mcreator/element/types/Recipe.java
Labels: community review

#4376 Damage type mod element
  plugins/generator-1.19.4/datapack-1.19.4/damagetype.definition.yaml
  plugins/generator-1.19.4/datapack-1.19.4/templates/damagetype.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/damagetype.definition.yaml
  plugins/generator-1.20.1/datapack-1.20.1/damagetype.definition.yaml
  plugins/generator-1.20.1/datapack-1.20.1/templates/damagetype.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/damagetype.definition.yaml
  plugins/mcreator-localization/help/default/damagetype/effects.md
  plugins/mcreator-localization/help/default/damagetype/exhaustion.md
  plugins/mcreator-localization/help/default/damagetype/item_death_message.md
  plugins/mcreator-localization/help/default/damagetype/normal_death_message.md
  plugins/mcreator-localization/help/default/damagetype/player_death_message.md
  plugins/mcreator-localization/help/default/damagetype/scaling.md
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/mod_types/damagetype.png
  plugins/mcreator-themes/themes/default_light/images/mod_types/damagetype.png
  src/main/java/net/mcreator/element/ModElementType.java
  src/main/java/net/mcreator/element/ModElementTypeLoader.java
  src/main/java/net/mcreator/element/types/DamageType.java
  src/main/java/net/mcreator/ui/modgui/DamageTypeGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review

#4389 Fix 4388
  plugins/generator-1.19.4/forge-1.19.4/procedures/team_add_entity.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/team_get_entity_team.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/team_add_entity.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/team_get_entity_team.java.ftl
Labels: bug

#4379 Proper "blocks_ignore" structure processor
  plugins/generator-1.19.4/datapack-1.19.4/templates/structure/template_pool.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/structure/template_pool.json.ftl
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2023_4/StructureIgnoredBlocksConverter.java
  src/main/java/net/mcreator/element/types/Structure.java
  src/main/java/net/mcreator/ui/modgui/StructureGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review, changes FV

#3986 Scalable entities
  plugins/generator-1.19.4/forge-1.19.4/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/livingentity/livingentity_renderer.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/livingentity/livingentity_renderer.java.ftl
  plugins/mcreator-localization/help/default/entity/bounding_box_scale.md
  plugins/mcreator-localization/help/default/entity/visual_scale.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#4387 Added support for custom damage types in procedures
  plugins/generator-1.19.4/forge-1.19.4/mappings/damagesources.yaml
  plugins/generator-1.20.1/forge-1.20.1/mappings/damagesources.yaml
  plugins/mcreator-core/procedures/damagesource_from_type.json
  plugins/mcreator-core/procedures/damagesource_from_type_cause.json
  plugins/mcreator-core/procedures/damagesource_from_type_cause_directcause.json
  plugins/mcreator-core/procedures/damagesource_isequalto.json
Labels: new feature

#4394 Bug report template Improvement
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: community review

#4401 Added data lists to combo box initializers in structure GUI
  src/main/java/net/mcreator/ui/modgui/FeatureGUI.java
  src/main/java/net/mcreator/ui/modgui/StructureGUI.java
Labels: bug

#4375 Add a Replace selected texture button
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelTextures.java
Labels: new feature

#4333 Main hand and use item procedure blocks
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_check_main_hand.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_get_use_item.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_get_use_item_ticks.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/entity_check_main_hand.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/entity_get_use_item.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/entity_get_use_item_ticks.java.ftl
  plugins/mcreator-core/procedures/entity_check_main_hand.json
  plugins/mcreator-core/procedures/entity_get_use_item.json
  plugins/mcreator-core/procedures/entity_get_use_item_ticks.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature, community review

#4406 Mandatory "processors" template pool option
  plugins/generator-1.19.4/datapack-1.19.4/templates/structure/template_pool.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/structure/template_pool.json.ftl
Labels: bug

#4403 Added support for damage type tags
  plugins/generator-1.19.4/datapack-1.19.4/mappings/damagesources.yaml
  plugins/generator-1.19.4/datapack-1.19.4/templates/tag.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/mappings/damagesources.yaml
  plugins/generator-1.19.4/forge-1.19.4/procedures/damagesource_is_tagged_in.java.ftl
  plugins/generator-1.20.1/datapack-1.20.1/mappings/damagesources.yaml
  plugins/generator-1.20.1/datapack-1.20.1/templates/tag.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/mappings/damagesources.yaml
  plugins/generator-1.20.1/forge-1.20.1/procedures/damagesource_is_tagged_in.java.ftl
  plugins/mcreator-core/procedures/damagesource_is_tagged_in.json
  plugins/mcreator-localization/help/default/tag/type.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/parts/DamageTypeEntry.java
  src/main/java/net/mcreator/element/types/Tag.java
  src/main/java/net/mcreator/ui/dialogs/AddTagDialog.java
  src/main/java/net/mcreator/ui/dialogs/tools/InjectTagsTool.java
  src/main/java/net/mcreator/ui/minecraft/DamageTypeListField.java
  src/main/java/net/mcreator/ui/modgui/TagGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#4402 Added Music Disc Rarity
  plugins/generator-1.19.4/forge-1.19.4/templates/musicdisc.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/musicdisc.java.ftl
  src/main/java/net/mcreator/element/types/MusicDisc.java
  src/main/java/net/mcreator/ui/modgui/MusicDiscGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review
