Repository MCreator/MCreator, pull requests merged in 2023-10, with the labels that each got.

#4273 Converter to convert all existing structures to features
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2023_4/StructureDimensionRestrictionConverter.java
  src/main/java/net/mcreator/element/converter/v2023_4/StructureToFeatureConverter.java
Labels: community review, changes FV

#4187 Added some damage source procedures
  plugins/generator-1.19.4/forge-1.19.4/procedures/damagesource_from_type_cause.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/damagesource_from_type_cause_directcause.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/damagesource_get_direct_entity.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/damagesource_get_entity.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/damagesource_get_exhaustion.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/damagesource_is_cause_creative.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/damagesource_is_indirect.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/procedures/damagesource_scales_with_difficulty.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/damagesource_from_type_cause.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/damagesource_from_type_cause_directcause.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/damagesource_get_direct_entity.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/damagesource_get_entity.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/damagesource_get_exhaustion.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/damagesource_is_cause_creative.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/damagesource_is_indirect.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/damagesource_scales_with_difficulty.java.ftl
  plugins/mcreator-core/procedures/$damagesources.json
  plugins/mcreator-core/procedures/damagesource_from_type.json
  plugins/mcreator-core/procedures/damagesource_from_type_cause.json
  plugins/mcreator-core/procedures/damagesource_from_type_cause_directcause.json
  plugins/mcreator-core/procedures/damagesource_get_direct_entity.json
  plugins/mcreator-core/procedures/damagesource_get_entity.json
  plugins/mcreator-core/procedures/damagesource_get_exhaustion.json
  plugins/mcreator-core/procedures/damagesource_is_cause_creative.json
  plugins/mcreator-core/procedures/damagesource_is_indirect.json
  plugins/mcreator-core/procedures/damagesource_scales_with_difficulty.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature, community review

#3995 Added client-side commands and server type parameter for commands
  plugins/generator-1.19.4/forge-1.19.4/cmdargs/_call_procedure.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/cmdargs/_old_command.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/command.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/cmdargs/_call_procedure.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/cmdargs/_old_command.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/command.java.ftl
  plugins/mcreator-localization/help/default/command/type.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Command.java
  src/main/java/net/mcreator/ui/modgui/CommandGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/generator/GTCommandArgBlocks.java
Labels: new feature, community review

#4291 Alternative procedures toolbox layout
  plugins/mcreator-core/procedures/$blockactions.json
  plugins/mcreator-core/procedures/$blockdata.json
  plugins/mcreator-core/procedures/$blockprocedures.json
  plugins/mcreator-core/procedures/$energyandfluid.json
  plugins/mcreator-core/procedures/$entitydata.json
  plugins/mcreator-core/procedures/$entitymanagement.json
  plugins/mcreator-core/procedures/$entityprocedures.json
  plugins/mcreator-core/procedures/$playerdata.json
  plugins/mcreator-core/procedures/$playermanagement.json
  plugins/mcreator-core/procedures/$playerprocedures.json
  plugins/mcreator-core/procedures/$worlddata.json
  plugins/mcreator-core/procedures/$worldmanagement.json
  plugins/mcreator-core/procedures/$worldprocedures.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/data/ExternalBlockLoader.java
Labels: community review

#4168 Add support for tags in breedable items for living entities
  plugins/generator-1.19.4/forge-1.19.4/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/livingentity/livingentity.java.ftl
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/generator/GTAITaskBlocks.java
Labels: new feature

#4241 Anchor points for GUI components in overlays
  plugins/generator-1.19.4/forge-1.19.4/templates/overlay.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/overlay.java.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2023_4/OverlayComponentAnchorPointAdder.java
  src/main/java/net/mcreator/element/parts/gui/EntityModel.java
  src/main/java/net/mcreator/element/parts/gui/GUIComponent.java
  src/main/java/net/mcreator/element/parts/gui/Image.java
  src/main/java/net/mcreator/element/parts/gui/Label.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/EntityModelDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/ImageDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/LabelDialog.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYG.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, changes FV

#3512 Added shields to the tool element
  plugins/generator-1.19.4/forge-1.19.4/templates/elementinits/items.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/json/item_model_blocking.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/tool.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/tool.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/items.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/json/item_model_blocking.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/tool.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/tool.definition.yaml
  plugins/mcreator-localization/help/default/tool/shield_blocking_model.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Tool.java
  src/main/java/net/mcreator/ui/init/BlockItemIcons.java
  src/main/java/net/mcreator/ui/modgui/ToolGUI.java
  src/main/java/net/mcreator/workspace/misc/WorkspaceInfo.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#4311 Fix GUI components layout
  plugins/generator-1.19.4/forge-1.19.4/templates/gui/gui_container.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/gui/gui_window.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/gui/gui_container.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/gui/gui_window.java.ftl
  src/main/java/net/mcreator/element/parts/gui/GUIComponent.java
  src/main/java/net/mcreator/element/types/GUI.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYG.java
Labels: bug, community review

#4310 Add a general ResourceFilterModel class
  src/main/java/net/mcreator/ui/workspace/resources/ResourceFilterModel.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelModels.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelScreenshots.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelSounds.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelStructures.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelTextures.java
Labels: community review

#4031 Inlined WorkspaceInfo prompts
  plugins/generator-1.19.4/datapack-1.19.4/biome.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/biome.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/block.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/feature.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/generator.yaml
  plugins/generator-1.19.4/forge-1.19.4/itemextension.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/templates/elementinits/items.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/elementinits/tabs.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/elementinits/villagertrades.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/modbase/accesstransformer.cfg.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/modbase/mod.java.ftl
  plugins/generator-1.20.1/datapack-1.20.1/biome.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/biome.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/block.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/feature.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/generator.yaml
  plugins/generator-1.20.1/forge-1.20.1/itemextension.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/items.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/tabs.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/villagertrades.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/modbase/accesstransformer.cfg.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/modbase/mod.java.ftl
  src/main/java/net/mcreator/workspace/misc/WorkspaceInfo.java
Labels: community review

#4274 True structure mod element
  plugins/generator-1.19.4/datapack-1.19.4/structure.definition.yaml
  plugins/generator-1.19.4/datapack-1.19.4/templates/structure/structure.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/templates/structure/structure_set.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/templates/structure/template_pool.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/structure.definition.yaml
  plugins/generator-1.20.1/datapack-1.20.1/templates/structure/structure.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/structure/structure_set.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/structure/template_pool.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/structure.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/json/structure_feature_biome_modifier.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/structure/configured_structure.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/structure/placed_structure.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/structure/structure.java.ftl
  plugins/mcreator-localization/help/default/structure/biomes_to_spawn.md
  plugins/mcreator-localization/help/default/structure/condition.md
  plugins/mcreator-localization/help/default/structure/generation_step.md
  plugins/mcreator-localization/help/default/structure/group_size.md
  plugins/mcreator-localization/help/default/structure/height_offset.md
  plugins/mcreator-localization/help/default/structure/on_generated.md
  plugins/mcreator-localization/help/default/structure/probability.md
  plugins/mcreator-localization/help/default/structure/projection.md
  plugins/mcreator-localization/help/default/structure/random_rotation.md
  plugins/mcreator-localization/help/default/structure/separation_spacing.md
  plugins/mcreator-localization/help/default/structure/spawn_location.md
  plugins/mcreator-localization/help/default/structure/terrain_adaptation.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/ModElementTypeLoader.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2023_4/StructureDimensionRestrictionConverter.java
  src/main/java/net/mcreator/element/converter/v2023_4/StructureToFeatureConverter.java
  src/main/java/net/mcreator/element/types/Structure.java
  src/main/java/net/mcreator/generator/template/TemplateHelper.java
  src/main/java/net/mcreator/ui/modgui/StructureGUI.java
  src/main/java/net/mcreator/ui/modgui/StructureGenGUI.java
  src/main/java/net/mcreator/ui/validation/CompoundValidator.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review, changes FV

#4323 Add None/Unknown datalist entry
  plugins/generator-1.19.4/forge-1.19.4/mappings/keybuttons.yaml
  plugins/generator-1.20.1/forge-1.20.1/mappings/keybuttons.yaml
  plugins/mcreator-core/datalists/keybuttons.yaml
Labels: new feature

#4231 Add breathe underwater and is pushed by fluids conditions
  plugins/generator-1.19.4/forge-1.19.4/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/livingentity/livingentity.java.ftl
  plugins/mcreator-localization/help/default/entity/condition_can_breathe_underwater.md
  plugins/mcreator-localization/help/default/entity/condition_fluids_can_push.md
  plugins/mcreator-localization/help/default/entity/water_entity.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2023_4/WaterEntitiesConverter.java
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review, changes FV

#4326 Create proper DMG "installer" for macOS
  .github/workflows/deploy.yml
  platform/mac/diskimage.png
  platform/mac/mac.gradle
  platform/mac/volume.icns
Labels: community review

#4344 Prevent cases like #4342
  src/main/java/net/mcreator/ui/modgui/FunctionGUI.java
  src/main/java/net/mcreator/ui/modgui/LootTableGUI.java
  src/main/java/net/mcreator/ui/modgui/RecipeGUI.java
Labels: bug
