Repository MCreator/MCreator, pull requests merged in 2023-06, with the labels that each got.

#3913 FG update
  plugins/generator-1.19.4/forge-1.19.4/generator.yaml
  plugins/generator-1.19.4/forge-1.19.4/templates/modbase/accesstransformer.cfg.ftl
Labels: official

#3929 Fix server creative mode malfunction
  plugins/generator-1.19.2/forge-1.19.2/workspacebase/run/server.properties
  plugins/generator-1.19.4/forge-1.19.4/workspacebase/run/server.properties
Labels: bug, community review

#3930 RB 1.19.4 FG
  plugins/generator-1.19.4/forge-1.19.4/generator.yaml
Labels: official

#3928 BugFix - Dimension lighter still generate its RegistryObject
  plugins/generator-1.19.2/forge-1.19.2/dimension.definition.yaml
  plugins/generator-1.19.2/forge-1.19.2/templates/elementinits/items.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/dimension.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/templates/elementinits/items.java.ftl
  src/main/java/net/mcreator/element/types/Dimension.java
  src/main/java/net/mcreator/ui/modgui/DimensionGUI.java
Labels: bug, community review

#3933 Update splash screen
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: new feature, official

#3942 Improved "Make portal" procedure template
  plugins/mcreator-core/templates/ptpl/Make portal to a dimension using custom igniter item.ptpl
Labels: bug

#3956 2023.3
  .github/workflows/deploy.yml
  .github/workflows/documentation.yml
  .github/workflows/test.yml
  platform/setup.gradle
  src/main/java/net/mcreator/blockly/datapack/blocks/MCItemBlock.java
  src/main/java/net/mcreator/element/types/Feature.java
  src/main/resources/mcreator.conf
Labels: official

#3968 Fix NBTEditorView performance
  src/main/java/net/mcreator/ui/views/NBTEditorView.java
Labels: bug

#3966 Workaround for #3964
  src/main/java/net/mcreator/ui/modgui/ModElementGUI.java
Labels: bug

#3954 Map color improvements
  plugins/generator-1.19.2/forge-1.19.2/mappings/mapcolors.yaml
  plugins/generator-1.19.4/forge-1.19.4/mappings/mapcolors.yaml
  plugins/mcreator-core/datalists/mapcolors.yaml
  plugins/mcreator-localization/help/default/block/color_on_map.md
  plugins/mcreator-localization/help/fr_FR/block/color_on_map.md
  plugins/mcreator-localization/help/ru_RU/block/color_on_map.md
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/FluidGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
Labels: bug, new feature

#3909 Added some blockstate provider feature blocks
  plugins/generator-1.19.2/forge-1.19.2/features/state_provider_randomized_int.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/features/state_provider_weighted.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/state_provider_randomized_int.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/state_provider_weighted.json.ftl
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-core/features/block_predicate_would_survive.json
  plugins/mcreator-core/features/feature_block_column_simple.json
  plugins/mcreator-core/features/feature_block_pile.json
  plugins/mcreator-core/features/feature_delta.json
  plugins/mcreator-core/features/feature_forest_rock.json
  plugins/mcreator-core/features/feature_geode_simple.json
  plugins/mcreator-core/features/feature_huge_brown_mushroom.json
  plugins/mcreator-core/features/feature_huge_fungus.json
  plugins/mcreator-core/features/feature_huge_red_mushroom.json
  plugins/mcreator-core/features/feature_lake.json
  plugins/mcreator-core/features/feature_random_patch_simple.json
  plugins/mcreator-core/features/feature_replace_sphere.json
  plugins/mcreator-core/features/feature_simple_block.json
  plugins/mcreator-core/features/ore_target.json
  plugins/mcreator-core/features/placement_block_survival_filter.json
  plugins/mcreator-core/features/rule_test_blockstate_match.json
  plugins/mcreator-core/features/rule_test_random_blockstate_match.json
  plugins/mcreator-core/features/state_provider_randomized_int.json
  plugins/mcreator-core/features/state_provider_weighted.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/resources/blockly/res/b_input.png
  src/main/resources/blockly/res/bsp.png
  src/main/resources/blockly/res/bsp_input.png
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
Labels: new feature

#3769 New DamageSource dependency
  plugins/generator-1.19.2/forge-1.19.2/mappings/types.yaml
  plugins/generator-1.19.2/forge-1.19.2/procedures/damagesource_isequalto.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/procedure.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/triggers/entity_attacked.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/triggers/entity_dies.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/triggers/entity_pre_hurt.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/mappings/types.yaml
  plugins/generator-1.19.4/forge-1.19.4/procedures/damagesource_isequalto.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/procedure.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/triggers/entity_attacked.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/triggers/entity_dies.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/triggers/entity_pre_hurt.java.ftl
  plugins/mcreator-core/procedures/damagesource_isequalto.json
  plugins/mcreator-core/triggers/entity_attacked.json
  plugins/mcreator-core/triggers/entity_dies.json
  plugins/mcreator-core/triggers/entity_pre_hurt.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/data/Dependency.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
Labels: community review

#2000 Added support for custom item properties
  plugins/generator-1.19.2/forge-1.19.2/item.definition.yaml
  plugins/generator-1.19.2/forge-1.19.2/mappings/itemproperties.yaml
  plugins/generator-1.19.2/forge-1.19.2/templates/elementinits/items.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/json/item.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/json/item_cmodel.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/json/item_cmodel_obj.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/json/tool.json.ftl
  plugins/generator-1.19.2/forge-1.19.2/utils/procedures.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/item.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/mappings/itemproperties.yaml
  plugins/generator-1.19.4/forge-1.19.4/templates/elementinits/items.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/json/item.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/json/item_cmodel.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/json/item_cmodel_obj.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/json/tool.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/utils/procedures.java.ftl
  plugins/mcreator-core/datalists/itemproperties.yaml
  plugins/mcreator-core/templates/ptpl/Item property - return 1 if condition executes and 0 otherwise.ptpl
  plugins/mcreator-localization/help/default/common/state_definition.md
  plugins/mcreator-localization/help/default/item/custom_property_name.md
  plugins/mcreator-localization/help/default/item/custom_property_value.md
  plugins/mcreator-localization/help/default/item/custom_states.md
  plugins/mcreator-localization/help/fr_FR/common/state_definition.md
  plugins/mcreator-localization/help/fr_FR/item/custom_property_name.md
  plugins/mcreator-localization/help/fr_FR/item/custom_property_value.md
  plugins/mcreator-localization/help/fr_FR/item/custom_states.md
  plugins/mcreator-localization/help/ru_RU/common/state_definition.md
  plugins/mcreator-localization/help/ru_RU/item/custom_property_name.md
  plugins/mcreator-localization/help/ru_RU/item/custom_property_value.md
  plugins/mcreator-localization/help/ru_RU/item/custom_states.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/generator/template/TemplateGenerator.java
  src/main/java/net/mcreator/ui/dialogs/StateEditorDialog.java
  src/main/java/net/mcreator/ui/dialogs/workspace/GeneratorSelector.java
  src/main/java/net/mcreator/ui/minecraft/JEntriesList.java
  src/main/java/net/mcreator/ui/minecraft/states/JStateLabel.java
  src/main/java/net/mcreator/ui/minecraft/states/PropertyData.java
  src/main/java/net/mcreator/ui/minecraft/states/StateMap.java
  src/main/java/net/mcreator/ui/minecraft/states/item/JItemPropertiesListEntry.java
  src/main/java/net/mcreator/ui/minecraft/states/item/JItemPropertiesStatesList.java
  src/main/java/net/mcreator/ui/minecraft/states/item/JItemStatesListEntry.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/main/java/net/mcreator/ui/modgui/ProcedureGUI.java
  src/main/java/net/mcreator/ui/procedure/ProcedureSelector.java
  src/main/java/net/mcreator/workspace/misc/WorkspaceInfo.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/generator/GTSampleElements.java
  src/test/java/net/mcreator/integration/ui/DialogsTest.java
  src/test/java/net/mcreator/integration/ui/ModElementUITest.java
Labels: new feature

#3984 Blockly panel holder
  src/main/java/net/mcreator/ui/blockly/BlocklyPanel.java
  src/main/java/net/mcreator/ui/modgui/AchievementGUI.java
  src/main/java/net/mcreator/ui/modgui/CommandGUI.java
  src/main/java/net/mcreator/ui/modgui/FeatureGUI.java
  src/main/java/net/mcreator/ui/modgui/IBlocklyPanelHolder.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/main/java/net/mcreator/ui/modgui/ProcedureGUI.java
Labels: community review

#3518 Add support for item and block tags in some item list fields
  plugins/generator-1.19.2/forge-1.19.2/templates/block/oregen.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/enchantment.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/tool.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/utils/mcitems.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/block/configured_oregen.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/enchantment.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/tool.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/utils/mcitems.ftl
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/dialogs/MCItemSelectorDialog.java
  src/main/java/net/mcreator/ui/minecraft/MCItemListField.java
  src/main/java/net/mcreator/ui/modgui/ArmorGUI.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/EnchantmentGUI.java
  src/main/java/net/mcreator/ui/modgui/ToolGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#3962 Pass slot ID to procedures
  plugins/generator-1.19.2/forge-1.19.2/templates/gui/gui_container.java.ftl
  plugins/generator-1.19.2/forge-1.19.2/templates/gui/gui_msg_slot.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/gui/gui_container.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/gui/gui_msg_slot.java.ftl
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/InputSlotDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/OutputSlotDialog.java
Labels: community review
