Repository MCreator/MCreator, pull requests merged in 2023-09, with the labels that each got.

#4217 Bump to 2023.4
  src/main/resources/mcreator.conf
  src/test/resources/workspaces/test-2023.3.zip
Labels: official

#4196 Biome tags support for features and entities
  plugins/generator-1.19.4/datapack-1.19.4/mappings/biomes.yaml
  plugins/generator-1.20.1/datapack-1.20.1/mappings/biomes.yaml
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/18px/addtag.png
  src/main/java/net/mcreator/ui/component/JItemListField.java
  src/main/java/net/mcreator/ui/dialogs/AddTagDialog.java
  src/main/java/net/mcreator/ui/dialogs/MCItemSelectorDialog.java
  src/main/java/net/mcreator/ui/minecraft/BiomeListField.java
  src/main/java/net/mcreator/ui/minecraft/MCItemListField.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/FeatureGUI.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/main/java/net/mcreator/ui/modgui/StructureGenGUI.java
  src/main/java/net/mcreator/ui/modgui/TagGUI.java
  src/main/java/net/mcreator/ui/validation/validators/ItemListFieldSingleTagValidator.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: official

#3666 Add an undecorated (component) checkbox (Plain Text Button component)
  plugins/generator-1.19.4/forge-1.19.4/templates/gui/gui_window.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/gui/gui_window.java.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/parts/gui/Button.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/ButtonDialog.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review

#4227 Removed feature dimension restrictions
  plugins/generator-1.19.4/forge-1.19.4/block.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/plant.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/templates/block/configured_oregen.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/block/oregen.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/feature/feature.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/plant/configured_plantgen.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/plant/plantgen.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/structure/structure.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/block.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/plant.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/block/configured_oregen.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/block/oregen.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/feature/feature.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/plant/configured_plantgen.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/plant/plantgen.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/structure/structure.java.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/block.definition.yaml
  plugins/mcreator-localization/help/default/common/generate_feature.md
  plugins/mcreator-localization/help/default/common/spawn_world_types.md
  plugins/mcreator-localization/help/default/feature/restrict_to_dimensions.md
  plugins/mcreator-localization/help/default/structure/spawn_world_types.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2023_1/FluidGenToFeatureConverter.java
  src/main/java/net/mcreator/element/converter/v2023_4/BlockFeatureDimensionRestrictionConverter.java
  src/main/java/net/mcreator/element/converter/v2023_4/BlockGenerationConditionRemover.java
  src/main/java/net/mcreator/element/converter/v2023_4/FeatureDimensionRestrictionConverter.java
  src/main/java/net/mcreator/element/converter/v2023_4/PlantGenerationConditionRemover.java
  src/main/java/net/mcreator/element/converter/v2023_4/StructureDimensionRestrictionConverter.java
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Feature.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/element/types/Structure.java
  src/main/java/net/mcreator/ui/dialogs/tools/InjectTagsTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/OrePackMakerTool.java
  src/main/java/net/mcreator/ui/minecraft/DimensionListField.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/FeatureGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/main/java/net/mcreator/ui/modgui/StructureGenGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
Labels: community review

#3901 Added 4 new AI tasks
  plugins/generator-1.19.4/forge-1.19.4/aitasks/climb_powder_snow.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/aitasks/find_and_move_to_air.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/aitasks/follow_boat.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/aitasks/try_and_find_water.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/aitasks/climb_powder_snow.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/aitasks/find_and_move_to_air.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/aitasks/follow_boat.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/aitasks/try_and_find_water.java.ftl
  plugins/mcreator-core/aitasks/climb_powder_snow.json
  plugins/mcreator-core/aitasks/find_and_move_to_air.json
  plugins/mcreator-core/aitasks/follow_boat.json
  plugins/mcreator-core/aitasks/try_and_find_water.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#4186 Blockly accessibility settings
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/BlocklyBlockUtil.java
  src/main/java/net/mcreator/preferences/data/BlocklySection.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptTemplates.java
  src/main/java/net/mcreator/ui/blockly/BlocklyPanel.java
  src/main/resources/blockly/js/mcreator_blockly.js
Labels: community review

#4142 Added some tree features
  plugins/generator-1.19.4/forge-1.19.4/features/feature_tree_simple.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/root_placer_none.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/tree_decorator_beehive.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/tree_decorator_cocoa.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/tree_decorator_leave_vine.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/tree_decorator_trunk_vine.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/mappings/features.yaml
  plugins/generator-1.19.4/forge-1.19.4/templates/modbase/accesstransformer.cfg.ftl
  plugins/generator-1.19.4/forge-1.19.4/utils/trees.ftl
  plugins/generator-1.20.1/forge-1.20.1/features/feature_tree_simple.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/features/root_placer_none.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/features/tree_decorator_beehive.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/features/tree_decorator_cocoa.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/features/tree_decorator_leave_vine.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/features/tree_decorator_trunk_vine.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/mappings/features.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/modbase/accesstransformer.cfg.ftl
  plugins/generator-1.20.1/forge-1.20.1/utils/trees.ftl
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-core/blockly/toolboxes/toolbox_feature.xml
  plugins/mcreator-core/features/feature_tree_simple.json
  plugins/mcreator-core/features/root_placer_none.json
  plugins/mcreator-core/features/tree_decorator_beehive.json
  plugins/mcreator-core/features/tree_decorator_cocoa.json
  plugins/mcreator-core/features/tree_decorator_leave_vine.json
  plugins/mcreator-core/features/tree_decorator_trunk_vine.json
  plugins/mcreator-core/templates/ftpl/Placement - Tree repeated 4 times on the surface.ftpl
  plugins/mcreator-core/templates/ftpl/Tree features - Acacia tree.ftpl
  plugins/mcreator-core/templates/ftpl/Tree features - Birch tree with beehive.ftpl
  plugins/mcreator-core/templates/ftpl/Tree features - Dark oak tree.ftpl
  plugins/mcreator-core/templates/ftpl/Tree features - Jungle bush.ftpl
  plugins/mcreator-core/templates/ftpl/Tree features - Jungle tree.ftpl
  plugins/mcreator-core/templates/ftpl/Tree features - Mega jungle tree.ftpl
  plugins/mcreator-core/templates/ftpl/Tree features - Oak tree.ftpl
  plugins/mcreator-core/templates/ftpl/Tree features - Swamp trees with placement.ftpl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/data/BlocklyLoader.java
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
Labels: new feature, community review

#4232 Tag references in tags ME
  plugins/generator-1.19.4/datapack-1.19.4/jsontriggers/_mcitemblock.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/mappings/entities.yaml
  plugins/generator-1.19.4/datapack-1.19.4/templates/advancement.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/templates/loottable.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/templates/recipe/blasting.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/templates/recipe/campfire_cooking.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/templates/recipe/crafting.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/templates/recipe/smelting.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/templates/recipe/smithing.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/templates/recipe/smoking.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/templates/recipe/stonecutting.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/templates/tag.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/utils/mcitems.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/block_holderset_list.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/rule_test_block_match.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/features/rule_test_random_block_match.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/json/advancement.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/json/carvertag.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/utils/mcitems.ftl
  plugins/generator-1.20.1/datapack-1.20.1/jsontriggers/_mcitemblock.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/mappings/entities.yaml
  plugins/generator-1.20.1/datapack-1.20.1/templates/advancement.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/loottable.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/recipe/blasting.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/recipe/campfire_cooking.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/recipe/crafting.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/recipe/smelting.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/recipe/smithing.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/recipe/smoking.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/recipe/stonecutting.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/tag.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/utils/mcitems.ftl
  plugins/generator-1.20.1/forge-1.20.1/features/block_holderset_list.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/features/rule_test_block_match.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/features/rule_test_random_block_match.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/json/advancement.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/json/carvertag.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/utils/mcitems.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/templates/biome.json.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/templates/block/block_custom_loot.json.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/templates/block/block_ore_feature.json.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/templates/entity/entity_custom_loot.json.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/templates/loottable.json.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/templates/recipe/blasting.json.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/templates/recipe/campfire_cooking.json.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/templates/recipe/crafting.json.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/templates/recipe/smelting.json.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/templates/recipe/smoking.json.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/templates/recipe/stonecutting.json.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/utils/mcitems.ftl
  src/main/java/net/mcreator/ui/minecraft/SpawnableEntityListField.java
  src/main/java/net/mcreator/ui/modgui/TagGUI.java
Labels: community review

#4229 Another Entity Procedure
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_set_invisible.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/entity_set_invisible.java.ftl
  plugins/mcreator-core/procedures/entity_set_invisible.json
  plugins/mcreator-localization/lang/texts.properties
Labels: community review

#4236 Add custom nested Blockly categories support
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/data/ExternalBlockLoader.java
  src/main/java/net/mcreator/blockly/data/ToolboxCategory.java
  src/main/java/net/mcreator/preferences/data/BlocklySection.java
Labels: new feature, community review

#4249 Support for hidden templates
  plugins/generator-1.19.4/datapack-1.19.4/biome.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/biome.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/block.definition.yaml
  plugins/generator-1.20.1/datapack-1.20.1/biome.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/biome.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/block.definition.yaml
  src/main/java/net/mcreator/generator/Generator.java
  src/main/java/net/mcreator/generator/GeneratorTemplate.java
  src/main/java/net/mcreator/ui/action/impl/workspace/RegenerateCodeAction.java
  src/main/java/net/mcreator/ui/workspace/ModElementCodeDropdown.java
Labels: community review

#3686 Procedure-generated special informations
  plugins/generator-1.19.4/forge-1.19.4/templates/armor.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/block/block.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/dimension/portaltrigger.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/fluid/fluidbucket.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/item/item.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/musicdisc.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/plant/plant.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/rangeditem/rangeditem.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/tool.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/utils/triggers.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/armor.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/block/block.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/dimension/portaltrigger.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/fluid/fluidbucket.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/item/item.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/musicdisc.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/plant/plant.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/rangeditem/rangeditem.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/tool.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/utils/triggers.java.ftl
  plugins/mcreator-localization/help/default/block/special_information.md
  plugins/mcreator-localization/help/default/item/special_information.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2022_1/FoodToItemConverter.java
  src/main/java/net/mcreator/element/converter/v2023_4/SpecialInformationConverter.java
  src/main/java/net/mcreator/element/parts/procedure/RetvalProcedure.java
  src/main/java/net/mcreator/element/parts/procedure/StringListProcedure.java
  src/main/java/net/mcreator/element/types/Armor.java
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Dimension.java
  src/main/java/net/mcreator/element/types/Fluid.java
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/element/types/MusicDisc.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/element/types/RangedItem.java
  src/main/java/net/mcreator/element/types/Tool.java
  src/main/java/net/mcreator/ui/modgui/ArmorGUI.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/DimensionGUI.java
  src/main/java/net/mcreator/ui/modgui/FluidGUI.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/main/java/net/mcreator/ui/modgui/MusicDiscGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/main/java/net/mcreator/ui/modgui/RangedItemGUI.java
  src/main/java/net/mcreator/ui/modgui/ToolGUI.java
  src/main/java/net/mcreator/ui/procedure/StringListProcedureSelector.java
  src/main/java/net/mcreator/util/StringUtils.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/generator/GTSampleElements.java
Labels: new feature, community review

#4244 Simple entries list
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/component/TechnicalButton.java
  src/main/java/net/mcreator/ui/component/entries/JEntriesList.java
  src/main/java/net/mcreator/ui/component/entries/JSimpleEntriesList.java
  src/main/java/net/mcreator/ui/component/entries/JSimpleListEntry.java
  src/main/java/net/mcreator/ui/component/entries/JSingleEntriesList.java
  src/main/java/net/mcreator/ui/minecraft/boundingboxes/JBoundingBoxEntry.java
  src/main/java/net/mcreator/ui/minecraft/boundingboxes/JBoundingBoxList.java
  src/main/java/net/mcreator/ui/minecraft/loottable/JLootTableEntry.java
  src/main/java/net/mcreator/ui/minecraft/loottable/JLootTablePool.java
  src/main/java/net/mcreator/ui/minecraft/loottable/JLootTablePoolsList.java
  src/main/java/net/mcreator/ui/minecraft/potions/JPotionList.java
  src/main/java/net/mcreator/ui/minecraft/potions/JPotionListEntry.java
  src/main/java/net/mcreator/ui/minecraft/spawntypes/JSpawnEntriesList.java
  src/main/java/net/mcreator/ui/minecraft/spawntypes/JSpawnListEntry.java
  src/main/java/net/mcreator/ui/minecraft/states/item/JItemPropertiesStatesList.java
  src/main/java/net/mcreator/ui/minecraft/villagers/JVillagerTradeProfession.java
  src/main/java/net/mcreator/ui/minecraft/villagers/JVillagerTradeProfessionsList.java
  src/main/java/net/mcreator/ui/modgui/BiomeGUI.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/LootTableGUI.java
  src/main/java/net/mcreator/ui/modgui/ModElementChangedListener.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/main/java/net/mcreator/ui/modgui/PotionGUI.java
  src/main/java/net/mcreator/ui/modgui/VillagerTradeGUI.java
Labels: bug, community review

#4247 Added NBT structure feature block
  plugins/generator-1.19.4/forge-1.19.4/feature.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/features/feature_custom_structure.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/mappings/features.yaml
  plugins/generator-1.19.4/forge-1.19.4/templates/feature/structure_feature.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/feature/structure_feature_configuration.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/json/feature/configured_feature.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/modbase/mod.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/utils/mcelements.ftl
  plugins/generator-1.20.1/forge-1.20.1/feature.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/features/feature_custom_structure.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/mappings/features.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/feature/structure_feature.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/feature/structure_feature_configuration.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/json/feature/configured_feature.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/modbase/mod.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/utils/mcelements.ftl
  plugins/mcreator-core/features/feature_custom_structure.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Feature.java
  src/main/java/net/mcreator/ui/validation/validators/JavaMemberNameValidator.java
  src/main/java/net/mcreator/workspace/misc/WorkspaceInfo.java
Labels: new feature

#4255 Add creative tabs to tool packs
  src/main/java/net/mcreator/ui/dialogs/tools/ArmorPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/OrePackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/ToolPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/WoodPackMakerTool.java
Labels: bug

#4252 Changes on glow conditions
  plugins/generator-1.19.4/forge-1.19.4/templates/item/item.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/musicdisc.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/rangeditem/rangeditem.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/tool.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/utils/triggers.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/item/item.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/musicdisc.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/rangeditem/rangeditem.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/tool.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/utils/triggers.java.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/item.definition.yaml
  plugins/generator-addon-1.20.x/addon-1.20.x/templates/item.json.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/templates/tool.json.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/tool.definition.yaml
  plugins/mcreator-localization/help/default/item/condition_glow.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2022_1/FoodToItemConverter.java
  src/main/java/net/mcreator/element/converter/v2023_4/ItemHasGlowConverter.java
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/element/types/MusicDisc.java
  src/main/java/net/mcreator/element/types/RangedItem.java
  src/main/java/net/mcreator/element/types/Tool.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/main/java/net/mcreator/ui/modgui/MusicDiscGUI.java
  src/main/java/net/mcreator/ui/modgui/RangedItemGUI.java
  src/main/java/net/mcreator/ui/modgui/ToolGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: community review

#4263 Improvements to the "mods.toml" file
  plugins/generator-1.19.4/forge-1.19.4/templates/modbase/mods.toml.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/modbase/mods.toml.ftl
Labels: bug

#4248 Tag type indicator and custom type suggestions
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/dialogs/AddTagDialog.java
  src/main/java/net/mcreator/ui/dialogs/MCItemSelectorDialog.java
  src/main/java/net/mcreator/ui/minecraft/BiomeListField.java
  src/main/java/net/mcreator/ui/minecraft/MCItemListField.java
  src/main/java/net/mcreator/ui/minecraft/SpawnableEntityListField.java
  src/main/java/net/mcreator/ui/modgui/TagGUI.java
Labels: community review
