Repository MCreator/MCreator, pull requests merged in 2024-04, with the labels that each got.

#4739 Vectorize ▷ icon
  plugins/mcreator-themes/themes/default_dark/images/16px/subpath.png
  plugins/mcreator-themes/themes/default_dark/images/16px/subpath.svg
Labels: official

#4746 Prevent flow control block from being used in wait block
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-localization/lang/texts.properties
Labels: bug

#4755 Fix #4751
  plugins/generator-1.20.1/datapack-1.20.1/utils/mcitems.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/block/configured_oregen.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/gui/gui_container.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/utils/mcitems.ftl
  plugins/generator-1.20.4/datapack-1.20.4/utils/mcitems.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/block/configured_oregen.json.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/gui/gui_container.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/utils/mcitems.ftl
  plugins/generator-addon-1.20.x/addon-1.20.x/utils/mcitems.ftl
Labels: bug

#4762 Fix #4757
  src/main/java/net/mcreator/ui/dialogs/ProgressDialog.java
Labels: bug

#4768 Fix #4760
  plugins/generator-1.20.1/forge-1.20.1/procedures/team_get_entity_team.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/team_get_entity_team.java.ftl
Labels: bug

#4771 Fix #4766
  plugins/generator-1.20.1/forge-1.20.1/templates/item/item.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/item/item.java.ftl
Labels: bug

#4778 Fix #4777
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/itemhandler_get_slot.java.ftl
Labels: bug, community review

#4767 Fix #4765
  plugins/generator-1.20.1/forge-1.20.1/templates/item/item.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/utils/triggers.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/item/item.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/utils/triggers.java.ftl
Labels: bug, community review

#4763 Fix #4759
  plugins/generator-1.20.1/forge-1.20.1/block.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/block/block.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/block.definition.yaml
  plugins/generator-1.20.4/neoforge-1.20.4/templates/block/block.java.ftl
  plugins/mcreator-localization/help/default/block/harvest_level.md
  plugins/mcreator-localization/help/default/tool/harvest_level.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
Labels: bug

#4775 Plugin version handling improvement
  src/main/java/net/mcreator/plugin/Plugin.java
  src/main/java/net/mcreator/plugin/PluginLoader.java
Labels: new feature, community review

#4783 Alternative fix for #4724 because original fix (#4730) introduced #4781
  plugins/generator-1.20.1/forge-1.20.1/procedures/world_data_dimensionid.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/feature/feature.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/world_data_dimensionid.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/feature/feature.java.ftl
Labels: bug, community review
