Repository MCreator/MCreator, pull requests merged in 2024-06, with the labels that each got.

#4874 Check for null cell bounds in ME list
  src/main/java/net/mcreator/ui/component/JSelectableListMouseListenerWithDND.java
Labels: bug

#4715 Added "Place feature at" procedure blocks
  plugins/generator-1.20.1/datapack-1.20.1/mappings/configuredfeatures.yaml
  plugins/generator-1.20.1/forge-1.20.1/procedures/world_place_feature.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/world_place_feature_with_result.java.ftl
  plugins/generator-1.20.4/datapack-1.20.4/mappings/configuredfeatures.yaml
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/world_place_feature.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/world_place_feature_with_result.java.ftl
  plugins/mcreator-core/datalists/configuredfeatures.yaml
  plugins/mcreator-core/procedures/world_place_feature.json
  plugins/mcreator-core/procedures/world_place_feature_with_result.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/BaseType.java
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Feature.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/test/java/net/mcreator/integration/generator/BlocklyTestUtil.java
Labels: new feature

#4876 [1.20.6] Ported tool ME
  plugins/generator-1.20.1/forge-1.20.1/templates/tool.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/tool.java.ftl
  plugins/generator-1.20.6/neoforge-1.20.6/templates/elementinits/items.java.ftl
  plugins/generator-1.20.6/neoforge-1.20.6/templates/json/handheld_rod.json.ftl
  plugins/generator-1.20.6/neoforge-1.20.6/templates/json/item_model_blocking.json.ftl
  plugins/generator-1.20.6/neoforge-1.20.6/templates/tool.java.ftl
  plugins/generator-1.20.6/neoforge-1.20.6/tool.definition.yaml
  plugins/generator-1.20.6/neoforge-1.20.6/utils/triggers.java.ftl
  plugins/mcreator-localization/help/default/tool/blocks_drop_tier.md
  plugins/mcreator-localization/help/default/tool/event_additional_drop_condition.md
  plugins/mcreator-localization/help/default/tool/harvest_level.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2024_2/ToolHarvestLevelConverter.java
  src/main/java/net/mcreator/element/types/Tool.java
  src/main/java/net/mcreator/ui/dialogs/tools/ToolPackMakerTool.java
  src/main/java/net/mcreator/ui/modgui/ToolGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: community review, changes FV

#4887 Bigger side tabs using JTabbedPane
  src/main/java/net/mcreator/ui/MCreator.java
  src/main/java/net/mcreator/ui/component/VerticalTabButton.java
  src/main/java/net/mcreator/ui/laf/themes/Theme.java
  src/main/java/net/mcreator/ui/workspace/AbstractWorkspacePanel.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanelLocalizations.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanelTags.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanelVariables.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelResources.java
Labels: community review

#4886 [1.20.6] Ported plant ME
  plugins/generator-1.20.6/neoforge-1.20.6/plant.definition.yaml
  plugins/generator-1.20.6/neoforge-1.20.6/templates/json/plant_double_bottom.json.ftl
  plugins/generator-1.20.6/neoforge-1.20.6/templates/json/plant_item.json.ftl
  plugins/generator-1.20.6/neoforge-1.20.6/templates/plant/configured_plantgen.json.ftl
  plugins/generator-1.20.6/neoforge-1.20.6/templates/plant/placed_plantgen.json.ftl
  plugins/generator-1.20.6/neoforge-1.20.6/templates/plant/plant.java.ftl
  plugins/generator-1.20.6/neoforge-1.20.6/templates/plant/plantblockentity.java.ftl
Labels: community review

#4892 2024.2 splash
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official

#4854 [Bugfix] One can't place item frames on certain custom blocks with block base
  plugins/generator-1.20.1/forge-1.20.1/templates/block/block.java.ftl
  plugins/generator-1.20.6/neoforge-1.20.6/templates/block/block.java.ftl
Labels: bug, community review

#4896 Color palettes in image editor
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/MCreatorTabs.java
  src/main/java/net/mcreator/ui/views/editor/image/ImageMakerView.java
  src/main/java/net/mcreator/ui/views/editor/image/color/ListEditPanel.java
  src/main/java/net/mcreator/ui/views/editor/image/color/PalettePanel.java
  src/main/java/net/mcreator/ui/views/editor/image/color/palette/ColorCellRenderer.java
  src/main/java/net/mcreator/ui/views/editor/image/color/palette/ColorPalette.java
  src/main/java/net/mcreator/ui/views/editor/image/color/palette/ColorPalettePanel.java
  src/main/java/net/mcreator/ui/views/editor/image/color/palettes/PaletteCellRenderer.java
  src/main/java/net/mcreator/ui/views/editor/image/color/palettes/PaletteListPanel.java
Labels: community review

#4904 Some Forgotten help tips
  plugins/mcreator-localization/help/default/biome/dead_bushes_per_chunk.md
  plugins/mcreator-localization/help/default/biome/generate_lakes.md
Labels: bug

#4907 Add missing 1.20.6 textures
  plugins/mcreator-core/datalists/icons/ARMADILLO_SCUTE.png
  plugins/mcreator-core/datalists/icons/ARMADILLO_SPAWN_EGG.png
  plugins/mcreator-core/datalists/icons/HEAVY_CORE.png
  plugins/mcreator-core/datalists/icons/VAULT.png
  plugins/mcreator-core/datalists/icons/WOLF_ARMOR.png
Labels: new feature, official

#4813 Added "Matching fluid" block predicate and fluid spring feature
  plugins/generator-1.20.1/datapack-1.20.1/features/block_predicate_matching_fluids.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_spring.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/mappings/features.yaml
  plugins/generator-1.20.1/datapack-1.20.1/mappings/fluids.yaml
  plugins/generator-1.20.1/forge-1.20.1/mappings/fluids.yaml
  plugins/generator-1.20.6/datapack-1.20.6/features/block_predicate_matching_fluids.json.ftl
  plugins/generator-1.20.6/datapack-1.20.6/features/feature_spring.json.ftl
  plugins/generator-1.20.6/datapack-1.20.6/mappings/features.yaml
  plugins/generator-1.20.6/datapack-1.20.6/mappings/fluids.yaml
  plugins/generator-1.20.6/neoforge-1.20.6/mappings/fluids.yaml
  plugins/mcreator-core/features/block_predicate_matching_fluids.json
  plugins/mcreator-core/features/feature_spring.json
  plugins/mcreator-core/templates/ftpl/Spring features - Buried Nether lava spring.ftpl
  plugins/mcreator-core/templates/ftpl/Spring features - Overworld lava spring.ftpl
  plugins/mcreator-core/templates/ftpl/Spring features - Water spring.ftpl
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature, community review

#4909 Added support for structure start height
  plugins/generator-1.20.1/datapack-1.20.1/templates/structure/structure.json.ftl
  plugins/generator-1.20.6/datapack-1.20.6/templates/structure/structure.json.ftl
  plugins/mcreator-localization/help/default/structure/start_height.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Structure.java
  src/main/java/net/mcreator/ui/modgui/StructureGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: community review

#4864 Reworked PotionEffect category
  plugins/generator-1.20.1/forge-1.20.1/templates/potioneffect.java.ftl
  plugins/generator-1.20.6/neoforge-1.20.6/templates/potioneffect.java.ftl
  plugins/mcreator-localization/help/default/potioneffect/bad.md
  plugins/mcreator-localization/help/default/potioneffect/benefitical.md
  plugins/mcreator-localization/help/default/potioneffect/category.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2024_2/PotionEffectCategoryConverter.java
  src/main/java/net/mcreator/element/types/PotionEffect.java
  src/main/java/net/mcreator/ui/modgui/PotionEffectGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: changes FV
