Repository MCreator/MCreator, pull requests merged in 2024-02, with the labels that each got.

#4607 Fix itemstack dependency misuse by item special information trigger
  plugins/generator-1.19.4/forge-1.19.4/utils/triggers.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/utils/triggers.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/utils/triggers.java.ftl
Labels: bug

#4588 SVG support in MCreator
  build.gradle
  license/jsvg License.txt
  plugins/mcreator-themes/themes/default_dark/images/16px/loading.gif
  plugins/mcreator-themes/themes/default_dark/images/16px/next.png
  plugins/mcreator-themes/themes/default_dark/images/16px/previous.png
  plugins/mcreator-themes/themes/default_dark/images/donate.png
  plugins/mcreator-themes/themes/default_dark/images/donate.svg
  plugins/mcreator-themes/themes/default_dark/images/info.png
  plugins/mcreator-themes/themes/default_dark/images/info.svg
  plugins/mcreator-themes/themes/default_dark/images/next.png
  plugins/mcreator-themes/themes/default_dark/images/next.svg
  plugins/mcreator-themes/themes/default_dark/images/previous.png
  plugins/mcreator-themes/themes/default_dark/images/previous.svg
  plugins/mcreator-themes/themes/default_dark/images/settings.png
  plugins/mcreator-themes/themes/default_dark/images/settings.svg
  plugins/mcreator-themes/themes/default_dark/images/social.png
  plugins/mcreator-themes/themes/default_light/images/16px/loading.gif
  plugins/mcreator-themes/themes/matrix/images/16px/loading.gif
  src/main/java/net/mcreator/generator/GeneratorFileTasks.java
  src/main/java/net/mcreator/minecraft/MinecraftImageGenerator.java
  src/main/java/net/mcreator/ui/MCreator.java
  src/main/java/net/mcreator/ui/MainMenuBar.java
  src/main/java/net/mcreator/ui/SplashScreen.java
  src/main/java/net/mcreator/ui/StatusBar.java
  src/main/java/net/mcreator/ui/action/impl/AboutAction.java
  src/main/java/net/mcreator/ui/component/SocialButtons.java
  src/main/java/net/mcreator/ui/component/SplashScreenPanel.java
  src/main/java/net/mcreator/ui/component/SquareLoaderIcon.java
  src/main/java/net/mcreator/ui/dialogs/MCreatorDialog.java
  src/main/java/net/mcreator/ui/dialogs/ProgressDialog.java
  src/main/java/net/mcreator/ui/init/AppIcon.java
  src/main/java/net/mcreator/ui/init/UIRES.java
  src/main/java/net/mcreator/ui/views/AnimationMakerView.java
  src/main/java/net/mcreator/ui/views/editor/image/layer/Layer.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/StampTool.java
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
  src/main/java/net/mcreator/util/GifUtil.java
  src/main/java/net/mcreator/util/image/ImageUtils.java
  src/main/java/net/mcreator/util/image/svg/CustomColorsPaintParser.java
  src/main/java/net/mcreator/util/image/svg/SVGProcessor.java
  src/main/resources/net/mcreator/ui/res/icon.svg
  src/main/resources/net/mcreator/ui/res/icon_eap.svg
  src/main/resources/net/mcreator/ui/res/logo.png
  src/main/resources/net/mcreator/ui/res/logo.svg
  src/main/resources/net/mcreator/ui/res/pylo.png
  src/main/resources/net/mcreator/ui/res/pylo.svg
  src/main/resources/net/mcreator/ui/res/social/fb.svg
  src/main/resources/net/mcreator/ui/res/social/gh.svg
  src/main/resources/net/mcreator/ui/res/social/ig.svg
  src/main/resources/net/mcreator/ui/res/social/rd.svg
  src/main/resources/net/mcreator/ui/res/social/tw.svg
  src/main/resources/net/mcreator/ui/res/social/yt.svg
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official, community review

#4619 Fix default values for pack makers
  src/main/java/net/mcreator/ui/dialogs/tools/ArmorPackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/ToolPackMakerTool.java
  src/main/java/net/mcreator/ui/modgui/ArmorGUI.java
Labels: bug, community review

#4628 Ported villager profession ME to NF 1.20.4
  plugins/generator-1.20.4/neoforge-1.20.4/templates/elementinits/villagerprofessions.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/json/villagerprofessions_poi_tag.json.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/modbase/mod.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/profession_hat.mcmeta.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/villagerprofession.definition.yaml
Labels: community review

#4627 Ported tool ME to NF 1.20.4
  plugins/generator-1.20.4/neoforge-1.20.4/templates/json/handheld_rod.json.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/json/item_model_blocking.json.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/tool.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/tool.definition.yaml
  plugins/generator-1.20.4/neoforge-1.20.4/utils/triggers.java.ftl
  plugins/generator-reference-1.20.1/ref-forge-1.20.1/utils/triggers.java.ftl
Labels: community review

#4651 Fix world dependency misuse by flight attack AI task conditions
  plugins/generator-1.19.4/forge-1.19.4/aitasks/attack_fly.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/aitasks/attack_fly.java.ftl
  plugins/generator-reference-1.20.1/ref-forge-1.20.1/aitasks/attack_fly.java.ftl
Labels: bug

#4652 1.19.4 way of getting level
  plugins/generator-1.19.4/forge-1.19.4/aitasks/attack_fly.java.ftl
Labels: bug

#4662 Improve some triggers, add missing dependency
  plugins/generator-1.20.1/forge-1.20.1/utils/triggers.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/utils/triggers.java.ftl
Labels: bug
