Repository MCreator/MCreator, pull requests merged in 2024-09, with the labels that each got.

#4906 Added 2 new player related global triggers
  plugins/generator-1.20.1/forge-1.20.1/triggers/player_left_click_air.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/triggers/player_right_click_empty_hand.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/triggers/player_left_click_air.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/triggers/player_right_click_empty_hand.java.ftl
  plugins/mcreator-core/triggers/player_left_click_air.json
  plugins/mcreator-core/triggers/player_right_click_empty_hand.json
  plugins/mcreator-localization/lang/texts.properties
Labels: community review

#4931 Place Schematic Improvement
  plugins/generator-1.20.1/forge-1.20.1/procedures/place_schematic.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/place_schematic.java.ftl
  plugins/mcreator-core/procedures/place_schematic.json
Labels: new feature

#5015 Added option to disable ranged item ammo requirement
  plugins/generator-1.20.1/forge-1.20.1/templates/item/item.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/item/item.java.ftl
  plugins/mcreator-localization/help/default/item/projectile_disable_ammo_check.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/converter/v2023_4/RangedItemToProjectileAndItemConverter.java
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: community review

#4927 [UX] Add a right-click menu in recentWorkspaceSelector
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
Labels: community review

#5034 Added a procedure to get potion as projectile
  plugins/generator-1.20.1/forge-1.20.1/procedures/projectiles_potion.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/projectiles_potion.java.ftl
  plugins/mcreator-core/procedures/projectiles_potion.json
  plugins/mcreator-localization/lang/texts.properties
Labels: community review

#5045 Projectile Hitbox
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/entities.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/elementinits/entities.java.ftl
  plugins/mcreator-localization/help/default/projectile/bounding_box.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Projectile.java
  src/main/java/net/mcreator/ui/modgui/ProjectileGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#4988 Block state properties 1/3 - Logic/integer properties
  plugins/generator-1.20.1/forge-1.20.1/block.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/block/block.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/utils/mcitems.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/block.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/block.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/utils/mcitems.ftl
  plugins/mcreator-localization/help/default/block/block_states.md
  plugins/mcreator-localization/help/default/block/custom_property_default_value.md
  plugins/mcreator-localization/help/default/block/custom_property_name.md
  plugins/mcreator-localization/help/default/block/custom_property_type.md
  plugins/mcreator-localization/help/default/block/custom_property_values.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/ui/dialogs/AddBlockPropertyDialog.java
  src/main/java/net/mcreator/ui/minecraft/states/block/JBlockPropertiesListEntry.java
  src/main/java/net/mcreator/ui/minecraft/states/block/JBlockPropertiesStatesList.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/ui/DialogsTest.java
Labels: new feature, community review

#5036 Added some terrain features
  plugins/generator-1.20.1/datapack-1.20.1/features/block_column_layer.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/features/disk_rule.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_block_column.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_disk.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_disk_simple.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_underwater_magma.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/mappings/features.yaml
  plugins/generator-1.21.1/datapack-1.21.1/features/block_column_layer.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/features/disk_rule.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/features/feature_block_column.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/features/feature_disk.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/features/feature_disk_simple.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/features/feature_underwater_magma.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/mappings/features.yaml
  plugins/mcreator-core/blockly/js/int_provider_validators.js
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/js/simple_repeating_input_mixins.js
  plugins/mcreator-core/features/block_column_layer.json
  plugins/mcreator-core/features/disk_rule.json
  plugins/mcreator-core/features/feature_block_column.json
  plugins/mcreator-core/features/feature_disk.json
  plugins/mcreator-core/features/feature_disk_simple.json
  plugins/mcreator-core/features/feature_underwater_magma.json
  plugins/mcreator-core/templates/ftpl/Misc features - Disk of clay.ftpl
  plugins/mcreator-core/templates/ftpl/Misc features - Disk of sand.ftpl
  plugins/mcreator-core/templates/ftpl/Misc features - Underwater magma.ftpl
  plugins/mcreator-core/templates/ftpl/Plant features - Cave vine.ftpl
  plugins/mcreator-localization/lang/texts.properties
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
Labels: new feature, community review

#5065 Block state properties 2/3 - Enum properties
  plugins/generator-1.20.1/forge-1.20.1/templates/block/block.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/block.java.ftl
  plugins/mcreator-localization/help/default/block/custom_property_type.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/component/JStringListField.java
  src/main/java/net/mcreator/ui/dialogs/AddBlockPropertyDialog.java
  src/main/java/net/mcreator/ui/minecraft/states/block/JBlockPropertiesListEntry.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review

#5069 Fix enum block property tests
  plugins/generator-1.20.1/forge-1.20.1/templates/block/block.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/block.java.ftl
Labels: bug

#5022 Added the attribute mod element
  plugins/generator-1.20.1/forge-1.20.1/attribute.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/mappings/attributes.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/attributes.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/modbase/mod.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/attribute.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/mappings/attributes.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/elementinits/attributes.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/modbase/mod.java.ftl
  plugins/mcreator-core/procedures/entity_get_attribute_base_value.json
  plugins/mcreator-core/procedures/entity_get_attribute_value.json
  plugins/mcreator-core/procedures/entity_has_attribute.json
  plugins/mcreator-core/procedures/entity_set_attribute_base_value.json
  plugins/mcreator-localization/help/default/attribute/add_to_all_entities.md
  plugins/mcreator-localization/help/default/attribute/add_to_players.md
  plugins/mcreator-localization/help/default/attribute/default_value.md
  plugins/mcreator-localization/help/default/attribute/entities.md
  plugins/mcreator-localization/help/default/attribute/min_max_value.md
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/mod_types/attribute.png
  plugins/mcreator-themes/themes/default_light/images/mod_types/attribute.png
  src/main/java/net/mcreator/element/ModElementType.java
  src/main/java/net/mcreator/element/ModElementTypeLoader.java
  src/main/java/net/mcreator/element/types/Attribute.java
  src/main/java/net/mcreator/ui/modgui/AttributeGUI.java
  src/main/java/net/mcreator/ui/validation/validators/ConditionalItemListFieldValidator.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: community review

#5040 Added some remaining features
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_random_selector.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_root_system.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_vegetation_patch.json
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_waterlogged_vegetation_patch.json
  plugins/generator-1.20.1/datapack-1.20.1/mappings/features.yaml
  plugins/generator-1.21.1/datapack-1.21.1/features/feature_random_selector.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/features/feature_root_system.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/features/feature_vegetation_patch.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/features/feature_waterlogged_vegetation_patch.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/mappings/features.yaml
  plugins/mcreator-core/blockly/js/int_provider_validators.js
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-core/blockly/js/simple_repeating_input_mixins.js
  plugins/mcreator-core/features/feature_random_selector.json
  plugins/mcreator-core/features/feature_root_system.json
  plugins/mcreator-core/features/feature_vegetation_patch.json
  plugins/mcreator-core/features/feature_waterlogged_vegetation_patch.json
  plugins/mcreator-core/templates/ftpl/Misc features - Clay pool with dripleaf.ftpl
  plugins/mcreator-core/templates/ftpl/Misc features - Rooted azalea tree.ftpl
  plugins/mcreator-core/templates/ftpl/Plant features - Ceiling moss patch.ftpl
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature, community review

#5082 Fix wrong vegetation feature files in 1.20.1
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_vegetation_patch.json
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_vegetation_patch.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_waterlogged_vegetation_patch.json
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_waterlogged_vegetation_patch.json.ftl
Labels: bug
