Repository MCreator/MCreator, pull requests merged in 2024-08, with the labels that each got.

#4968 MCreator 2024.3 kick-off
  .github/workflows/deploy.yml
  .github/workflows/documentation.yml
  .github/workflows/test.yml
  build.gradle
  platform/setup.gradle
  plugins/generator-1.20.6/neoforge-1.20.6/generator.yaml
  plugins/generator-1.20.6/neoforge-1.20.6/workspacebase/build.gradle
  src/main/resources/mcreator.conf
  src/test/resources/workspaces/test-2024.2.zip
Labels: official

#4972 FlatLaf 3.5.x
  build.gradle
  src/main/java/net/mcreator/ui/laf/themes/ThemeManager.java
Labels: bug, community review

#4996 2024.3 splash screen
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official

#4912 "Global" setting for flood fill tool
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/FloodFillTool.java
Labels: new feature

#5001 [1.21.1] Enchantment ME
  plugins/generator-1.20.1/forge-1.20.1/mappings/enchantmenttypes.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/enchantment.java.ftl
  plugins/generator-1.20.6/neoforge-1.20.6/mappings/enchantmenttypes.yaml
  plugins/generator-1.20.6/neoforge-1.20.6/templates/enchantment.java.ftl
  plugins/generator-1.21.1/datapack-1.21.1/enchantment.definition.yaml
  plugins/generator-1.21.1/datapack-1.21.1/templates/enchantment.json.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/enchantment.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/mappings/enchantmenttypes.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/modbase/mod.java.ftl
  plugins/mcreator-core/datalists/enchantmenttypes.yaml
  plugins/mcreator-localization/help/default/enchantment/allowed_on_books.md
  plugins/mcreator-localization/help/default/enchantment/anvil_cost.md
  plugins/mcreator-localization/help/default/enchantment/can_apply_to.md
  plugins/mcreator-localization/help/default/enchantment/compatible_enchantments.md
  plugins/mcreator-localization/help/default/enchantment/curse.md
  plugins/mcreator-localization/help/default/enchantment/incompatible_enchantments.md
  plugins/mcreator-localization/help/default/enchantment/rarity.md
  plugins/mcreator-localization/help/default/enchantment/supported_items.md
  plugins/mcreator-localization/help/default/enchantment/supported_slots.md
  plugins/mcreator-localization/help/default/enchantment/type.md
  plugins/mcreator-localization/help/default/enchantment/weight.md
  plugins/mcreator-localization/lang/texts.properties
  plugins/ref-generator-1.20.6/neoforge-1.20.6/enchantment.definition.yaml
  plugins/ref-generator-1.20.6/neoforge-1.20.6/templates/enchantment.java.ftl
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2024_3/EnchantmentDefinitionConverter.java
  src/main/java/net/mcreator/element/types/Enchantment.java
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/minecraft/EnchantmentListField.java
  src/main/java/net/mcreator/ui/minecraft/MCItemListField.java
  src/main/java/net/mcreator/ui/modgui/EnchantmentGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: community review

#4916 Added "Existing feature" feature block
  plugins/generator-1.20.1/datapack-1.20.1/feature.definition.yaml
  plugins/generator-1.20.1/datapack-1.20.1/features/configured_feature_reference.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/feature/placed_feature.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/utils/mcelements.ftl
  plugins/generator-1.20.1/forge-1.20.1/feature.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/utils/mcelements.ftl
  plugins/generator-1.21.1/datapack-1.21.1/feature.definition.yaml
  plugins/generator-1.21.1/datapack-1.21.1/features/configured_feature_reference.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/templates/feature/placed_feature.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/utils/mcelements.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/feature.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/utils/mcelements.ftl
  plugins/mcreator-core/features/configured_feature_reference.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Feature.java
  src/main/java/net/mcreator/ui/modgui/FeatureGUI.java
Labels: new feature, community review

#4921 Entity Push Procedure
  plugins/generator-1.20.1/forge-1.20.1/procedures/entity_push.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/entity_push.java.ftl
  plugins/mcreator-core/procedures/entity_push.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature, community review
