Repository MCreator/MCreator, pull requests merged in 2024-10, with the labels that each got.

#5108 Fix malfunctioning custom block property name validator
  src/main/java/net/mcreator/ui/dialogs/AddBlockPropertyDialog.java
Labels: bug

#5129 Fix #5128
  src/main/java/net/mcreator/ui/browser/WorkspaceFileBrowser.java
Labels: bug

#5127 Fix #5119
  plugins/generator-1.20.1/forge-1.20.1/templates/item/item.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/item/item.java.ftl
Labels: bug, community review

#5131 Fix #5130
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/world_place_feature.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/world_place_feature_with_result.java.ftl
Labels: bug

#5117 Fix #5113
  plugins/generator-1.20.1/forge-1.20.1/templates/projectile/projectile.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/projectile/projectile.java.ftl
  plugins/mcreator-localization/help/default/projectile/bounding_box.md
Labels: bug, community review

#5105 2024.4 kick-off
  src/main/resources/mcreator.conf
  src/test/resources/workspaces/test-2024.3.zip
Labels: official

#5146 2024.4 splash screen
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official

#5149 Fix #5147
  src/main/java/net/mcreator/blockly/java/blocks/TextIndexOfBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/TextLengthBlock.java
Labels: bug

#5052 Added Sprite component for GUI and Overlay
  plugins/generator-1.20.1/forge-1.20.1/templates/gui/gui_window.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/overlay.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/gui/gui_window.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/overlay.java.ftl
  plugins/mcreator-localization/help/default/gui/sprite_count.md
  plugins/mcreator-localization/help/default/gui/sprite_display_condition.md
  plugins/mcreator-localization/help/default/gui/sprite_index.md
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/wysiwyg_editor/addsprite.png
  src/main/java/net/mcreator/element/parts/gui/GUIComponent.java
  src/main/java/net/mcreator/element/parts/gui/Sprite.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/SpriteDialog.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYGEditor.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: community review

#5153 Twice value on Dimensions/Datapack field inclusions
  plugins/generator-1.20.1/datapack-1.20.1/dimension.definition.yaml
  plugins/generator-1.21.1/datapack-1.21.1/dimension.definition.yaml
Labels: bug

#5089 Infinite effects for potion mod element
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/potions.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/elementinits/potions.java.ftl
  plugins/mcreator-localization/help/default/potion/infinite.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Potion.java
  src/main/java/net/mcreator/ui/minecraft/potions/JPotionListEntry.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review

#5141 Vanilla entity model animations
  plugins/generator-1.20.1/forge-1.20.1/generator.yaml
  plugins/generator-1.20.1/forge-1.20.1/mappings/animations.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/javamodel.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/livingentity/livingentity_renderer.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/generator.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/mappings/animations.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/javamodel.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/livingentity/livingentity_renderer.java.ftl
  plugins/mcreator-core/datalists/animations.yaml
  plugins/mcreator-localization/help/default/entity/animation.md
  plugins/mcreator-localization/help/default/entity/animation_amplitude.md
  plugins/mcreator-localization/help/default/entity/animation_speed.md
  plugins/mcreator-localization/help/default/entity/animation_walking.md
  plugins/mcreator-localization/help/default/entity/condition_animation.md
  plugins/mcreator-localization/help/default/entity/model_animations.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/parts/Animation.java
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/minecraft/entityanimations/JEntityAnimationList.java
  src/main/java/net/mcreator/ui/minecraft/entityanimations/JEntityAnimationListEntry.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review

#5148 Multiline dynamic special information support
  plugins/generator-1.20.1/forge-1.20.1/utils/triggers.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/utils/triggers.java.ftl
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/toolboxes/toolbox_procedure.xml
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/java/BlocklyToJava.java
  src/main/java/net/mcreator/blockly/java/blocks/TextNewLineBlock.java
Labels: new feature

#5145 Translatable static special information support
  plugins/generator-1.20.1/forge-1.20.1/armor.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/block.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/dimension.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/fluid.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/item.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/musicdisc.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/plant.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/armor.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/block/block.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/dimension/portaltrigger.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/fluid/fluidbucket.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/item/item.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/musicdisc.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/plant/plant.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/tool.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/tool.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/utils/triggers.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/armor.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/block.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/dimension.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/fluid.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/item.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/musicdisc.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/plant.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/armor.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/block.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/dimension/portaltrigger.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/fluid/fluidbucket.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/item/item.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/musicdisc.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/plant/plant.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/tool.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/tool.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/utils/triggers.java.ftl
  src/main/java/net/mcreator/element/types/Armor.java
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Dimension.java
  src/main/java/net/mcreator/element/types/Fluid.java
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/element/types/MusicDisc.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/element/types/Tool.java
  src/main/java/net/mcreator/element/types/interfaces/ISpecialInfoHolder.java
  src/main/java/net/mcreator/generator/LocalizationUtils.java
Labels: new feature, community review
