Repository MCreator/MCreator, pull requests merged in 2024-11, with the labels that each got.

#5094 Added some fluid visual settings
  plugins/generator-1.20.1/forge-1.20.1/templates/fluid/fluidtype.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/fluid/fluidtype.java.ftl
  plugins/mcreator-localization/help/default/fluid/fog_color.md
  plugins/mcreator-localization/help/default/fluid/fog_end_distance.md
  plugins/mcreator-localization/help/default/fluid/fog_start_distance.md
  plugins/mcreator-localization/help/default/fluid/has_fog.md
  plugins/mcreator-localization/help/default/fluid/render_overlay_texture.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Fluid.java
  src/main/java/net/mcreator/ui/modgui/FluidGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review

#5142 Custom Java model animations
  plugins/generator-1.20.1/forge-1.20.1/generator.yaml
  plugins/generator-1.20.1/forge-1.20.1/mappings/animations.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/javaanimation.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/generator.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/mappings/animations.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/javaanimation.java.ftl
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/16px/importjavamodelanimation.png
  plugins/mcreator-themes/themes/default_dark/images/model/javaanimation.png
  src/main/java/net/mcreator/element/parts/Animation.java
  src/main/java/net/mcreator/generator/GeneratorFileTasks.java
  src/main/java/net/mcreator/generator/GeneratorStats.java
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/MainMenuBar.java
  src/main/java/net/mcreator/ui/MainToolBar.java
  src/main/java/net/mcreator/ui/action/ActionRegistry.java
  src/main/java/net/mcreator/ui/action/impl/workspace/resources/AnimationImportActions.java
  src/main/java/net/mcreator/ui/action/impl/workspace/resources/ModelImportActions.java
  src/main/java/net/mcreator/ui/dialogs/workspace/GeneratorSelector.java
  src/main/java/net/mcreator/ui/minecraft/entityanimations/JEntityAnimationListEntry.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelAnimations.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelResources.java
  src/main/java/net/mcreator/workspace/WorkspaceFolderManager.java
  src/main/java/net/mcreator/workspace/references/ReferencesFinder.java
  src/main/java/net/mcreator/workspace/resources/Animation.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review

#5064 Added lock button for screen components
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/18px/lock.svg
  src/main/java/net/mcreator/element/parts/gui/GUIComponent.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYG.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYGEditor.java
Labels: new feature, community review

#5165 Merge music disc ME into item ME
  plugins/generator-1.20.1/forge-1.20.1/item.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/musicdisc.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/item/item.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/musicdisc.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/item.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/musicdisc.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/item/item.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/json/musicdisc.json.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/musicdisc.java.ftl
  plugins/mcreator-localization/help/default/item/musicdisc.md
  plugins/mcreator-localization/help/default/item/musicdisc_analog_output.md
  plugins/mcreator-localization/help/default/item/musicdisc_description.md
  plugins/mcreator-localization/help/default/item/musicdisc_length.md
  plugins/mcreator-localization/help/default/item/musicdisc_music.md
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/mod_types/musicdisc.png
  plugins/mcreator-themes/themes/default_light/images/mod_types/musicdisc.png
  plugins/mcreator-themes/themes/matrix/images/mod_types/musicdisc.png
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/ModElementType.java
  src/main/java/net/mcreator/element/ModElementTypeLoader.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2023_4/ItemHasGlowConverter.java
  src/main/java/net/mcreator/element/converter/v2024_4/MusicDiscToItemConverter.java
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/element/types/MusicDisc.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/main/java/net/mcreator/ui/modgui/MusicDiscGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review, changes FV

#5168 Single entry selector
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/component/JSingleEntrySelector.java
  src/main/java/net/mcreator/ui/minecraft/SingleModElementSelector.java
  src/main/java/net/mcreator/ui/modgui/AchievementGUI.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/main/java/net/mcreator/ui/modgui/ModElementChangedListener.java
Labels: new feature

#5169 #5168 follow-up
  plugins/generator-1.20.1/datapack-1.20.1/templates/advancement.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/block/blockentity.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.21.1/datapack-1.21.1/templates/advancement.json.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/blockentity.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/elementinits/entities.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/livingentity/livingentity.java.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2024_4/AdvancementFunctionConverter.java
  src/main/java/net/mcreator/element/converter/v2024_4/NoGUISelectedConverter.java
  src/main/java/net/mcreator/element/types/Achievement.java
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: changes FV

#5158 Split biome fog and air colors
  plugins/generator-1.20.1/datapack-1.20.1/templates/biome/biome.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/templates/biome/biome.json.ftl
  plugins/mcreator-localization/help/default/biome/fog_color.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2024_4/BiomeFogColorConverter.java
  src/main/java/net/mcreator/element/types/Biome.java
  src/main/java/net/mcreator/ui/modgui/BiomeGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review, changes FV

#5174 Fix deleted tabs' ordering not being removed
  src/main/java/net/mcreator/workspace/misc/CreativeTabsOrder.java
Labels: bug

#5096 Add "Is entity aggressive" procedure block
  plugins/generator-1.20.1/forge-1.20.1/procedures/entity_isaggressive.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/entity_isaggressive.java.ftl
  plugins/mcreator-core/procedures/entity_isaggressive.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#5155 Attribute modifiers for potion effects
  plugins/generator-1.20.1/forge-1.20.1/templates/potioneffect.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/potioneffect.java.ftl
  plugins/mcreator-localization/help/default/potioneffect/amount.md
  plugins/mcreator-localization/help/default/potioneffect/attribute.md
  plugins/mcreator-localization/help/default/potioneffect/modifiers.md
  plugins/mcreator-localization/help/default/potioneffect/operation.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/parts/AttributeEntry.java
  src/main/java/net/mcreator/element/types/PotionEffect.java
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/minecraft/attributemodifiers/JAttributeModifierEntry.java
  src/main/java/net/mcreator/ui/minecraft/attributemodifiers/JAttributeModifierList.java
  src/main/java/net/mcreator/ui/modgui/PotionEffectGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review

#5179 Minor fixes
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/FluidGUI.java
  src/main/java/net/mcreator/ui/procedure/RetvalProcedureSelector.java
Labels: bug

#5088 Block state properties 3/3 - External properties
  plugins/generator-1.20.1/forge-1.20.1/mappings/blockstateproperties.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/block/block.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/mappings/blockstateproperties.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/block.java.ftl
  plugins/mcreator-core/datalists/blockstateproperties.yaml
  plugins/mcreator-localization/help/default/block/block_states.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/dialogs/AddBlockPropertyDialog.java
  src/main/java/net/mcreator/ui/minecraft/states/block/BlockStatePropertyUtils.java
  src/main/java/net/mcreator/ui/minecraft/states/block/JBlockPropertiesListEntry.java
  src/main/java/net/mcreator/ui/minecraft/states/block/JBlockPropertiesStatesList.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/ui/DialogsTest.java
Labels: new feature, community review

#5166 Sapling plant type
  plugins/generator-1.20.1/forge-1.20.1/plant.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/plant/placed_plantgen.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/plant/plant.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/plant/treegrower.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/plant.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/plant/placed_plantgen.json.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/plant/plant.java.ftl
  plugins/mcreator-localization/help/default/plant/flower_trees.md
  plugins/mcreator-localization/help/default/plant/mega_trees.md
  plugins/mcreator-localization/help/default/plant/plant_type.md
  plugins/mcreator-localization/help/default/plant/secondary_tree_chance.md
  plugins/mcreator-localization/help/default/plant/trees.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/parts/ConfiguredFeatureEntry.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/ui/minecraft/SingleConfiguredFeatureField.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review

#5175 Added some dimension settings
  plugins/generator-1.20.1/datapack-1.20.1/dimension.definition.yaml
  plugins/generator-1.20.1/datapack-1.20.1/templates/dimension/dimension_type.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/dimension.definition.yaml
  plugins/generator-1.21.1/datapack-1.21.1/templates/dimension/dimension_type.json.ftl
  plugins/mcreator-localization/help/default/dimension/coordinate_scale.md
  plugins/mcreator-localization/help/default/dimension/fixed_time_value.md
  plugins/mcreator-localization/help/default/dimension/has_fixed_time.md
  plugins/mcreator-localization/help/default/dimension/infiniburn_tag.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Dimension.java
  src/main/java/net/mcreator/ui/modgui/DimensionGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review

#5186 Improved mappings for fluids
  plugins/generator-1.20.1/datapack-1.20.1/features/block_predicate_matching_fluids.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_spring.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/mappings/fluids.yaml
  plugins/generator-1.20.1/forge-1.20.1/procedures/block_fluidtank_check_fill.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/block_fluidtank_fill.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/block/blockentity.java.ftl
  plugins/generator-1.21.1/datapack-1.21.1/features/block_predicate_matching_fluids.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/features/feature_spring.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/mappings/fluids.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/block_fluidtank_check_fill.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/block_fluidtank_fill.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/blockentity.java.ftl
  src/main/java/net/mcreator/generator/mapping/NameMapper.java
Labels: community review

#5188 Minor dimension GUI changes
  plugins/mcreator-localization/help/default/dimension/can_respawn.md
  plugins/mcreator-localization/help/default/dimension/can_use_respawn_anchor.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/modgui/DimensionGUI.java
Labels: community review

#5178 Allow custom creative tabs to be reordered
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/tabs.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/elementinits/tabs.java.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/dialogs/ElementOrderEditor.java
  src/main/java/net/mcreator/workspace/misc/CreativeTabsOrder.java
  src/main/java/net/mcreator/workspace/misc/WorkspaceInfo.java
Labels: new feature, community review

#5191 Added "Get specific light level" procedure block
  plugins/generator-1.20.1/forge-1.20.1/procedures/world_data_light_level_specific.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/world_data_light_level_specific.java.ftl
  plugins/mcreator-core/procedures/world_data_light_level_specific.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature, community review

#5195 1.21.1 data pack generator test client support
  plugins/generator-1.21.1/datapack-1.21.1/generator.yaml
  plugins/generator-1.21.1/datapack-1.21.1/workspace.gitignore
  plugins/generator-1.21.1/datapack-1.21.1/workspacebase/build.gradle
  plugins/generator-1.21.1/datapack-1.21.1/workspacebase/gradle.properties
  plugins/generator-1.21.1/datapack-1.21.1/workspacebase/packloader/build.gradle
  plugins/generator-1.21.1/datapack-1.21.1/workspacebase/packloader/settings.gradle
  plugins/generator-1.21.1/datapack-1.21.1/workspacebase/packloader/src/main/java/net/mcreator/packloader/PackLoaderMod.java
  plugins/generator-1.21.1/datapack-1.21.1/workspacebase/packloader/src/main/resources/META-INF/neoforge.mods.toml
  plugins/generator-1.21.1/datapack-1.21.1/workspacebase/settings.gradle
Labels: community review

#5198 Retain user workspace state
  src/main/java/net/mcreator/preferences/data/HiddenSection.java
  src/main/java/net/mcreator/ui/MCreator.java
  src/main/java/net/mcreator/ui/browser/WorkspaceFileBrowser.java
  src/main/java/net/mcreator/ui/component/tree/SerializableTreeExpansionState.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
  src/main/java/net/mcreator/workspace/IWorkspaceProvider.java
  src/main/java/net/mcreator/workspace/Workspace.java
  src/main/java/net/mcreator/workspace/settings/user/WorkspaceUserSettings.java
  src/main/java/net/mcreator/workspace/settings/user/WorkspaceUserSettingsManager.java
Labels: community review

#5193 Performance monitor
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/java/monitoring/JMXMonitorClient.java
  src/main/java/net/mcreator/java/monitoring/JMXMonitorEventListener.java
  src/main/java/net/mcreator/preferences/data/GradleSection.java
  src/main/java/net/mcreator/ui/action/impl/gradle/DebugClientAction.java
  src/main/java/net/mcreator/ui/action/impl/gradle/RunClientAction.java
  src/main/java/net/mcreator/ui/action/impl/gradle/RunServerAction.java
  src/main/java/net/mcreator/ui/component/SimpleLineChart.java
  src/main/java/net/mcreator/ui/gradle/GradleConsole.java
Labels: new feature, community review

#5190 "Is waterloggable" setting for plants
  plugins/generator-1.20.1/forge-1.20.1/templates/plant/plant.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/plant/plant.java.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review
