Repository MCreator/MCreator, pull requests merged in 2024-01, with the labels that each got.

#4480 Fix incorrect max value for spruce foliage radius
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-localization/lang/texts.properties
Labels: bug

#4487 Fix item states not applying to ranged models
  plugins/generator-1.19.4/forge-1.19.4/templates/json/rangeditem.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/json/rangeditem.json.ftl
Labels: bug

#4486 Make project browser try to detect folders in libraries' contents
  src/main/java/net/mcreator/ui/browser/WorkspaceFileBrowser.java
  src/main/java/net/mcreator/ui/component/JFileBreadCrumb.java
  src/main/java/net/mcreator/ui/laf/FileIcons.java
Labels: bug

#4482 cp437 support for ZIP files
  src/main/java/net/mcreator/io/zip/ZipIO.java
  src/main/java/net/mcreator/java/ClassFinder.java
  src/main/java/net/mcreator/java/ImportTreeBuilder.java
  src/main/java/net/mcreator/java/JModLibraryInfo.java
Labels: bug

#4481 A system to detect if opened workspace requires plugins
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/ModElementTypeLoader.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/ui/MCreatorApplication.java
  src/main/java/net/mcreator/workspace/MissingWorkspacePluginsException.java
  src/main/java/net/mcreator/workspace/ShareableZIPManager.java
  src/main/java/net/mcreator/workspace/Workspace.java
  src/main/java/net/mcreator/workspace/WorkspaceUtils.java
  src/main/java/net/mcreator/workspace/elements/VariableElement.java
Labels: bug, new feature

#4489 Generator system improvements
  plugins/generator-1.19.4/forge-1.19.4/templates/block/mineable_tag.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/elementinits/biomes.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/elementinits/tabs.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/block/mineable_tag.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/biomes.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/tabs.java.ftl
  src/main/java/net/mcreator/generator/Generator.java
  src/main/java/net/mcreator/generator/GeneratorFileTasks.java
  src/main/java/net/mcreator/io/writer/ClassWriter.java
  src/main/java/net/mcreator/io/writer/JSONWriter.java
  src/main/java/net/mcreator/ui/browser/action/NewClassAction.java
Labels: community review

#4496 Split tree features category into "Trees" and "Roots and decorators"
  plugins/mcreator-core/blockly/toolboxes/toolbox_feature.xml
  plugins/mcreator-core/features/root_placer_none.json
  plugins/mcreator-core/features/tree_decorator_alter_ground.json
  plugins/mcreator-core/features/tree_decorator_beehive.json
  plugins/mcreator-core/features/tree_decorator_cocoa.json
  plugins/mcreator-core/features/tree_decorator_leave_vine.json
  plugins/mcreator-core/features/tree_decorator_trunk_vine.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/data/BlocklyLoader.java
Labels: new feature

#4500 Fix repeating field extension always assigning the empty string to new fields
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
Labels: bug

#4469 Require version list for plugins instead of version range
  plugins/generator-1.19.4/plugin.json
  plugins/generator-1.20.1/plugin.json
  plugins/generator-addon-1.20.x/plugin.json
  plugins/mcreator-core/plugin.json
  plugins/mcreator-link/plugin.json
  plugins/mcreator-localization/plugin.json
  plugins/mcreator-themes/plugin.json
  src/main/java/net/mcreator/plugin/Plugin.java
  src/main/java/net/mcreator/plugin/PluginLoader.java
Labels: official, community review

#4492 Remove "Deal custom damage" procedure block
  plugins/generator-1.19.4/forge-1.19.4/procedures/entity_deal_custom_damage.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/entity_deal_custom_damage.java.ftl
  plugins/mcreator-core/procedures/entity_deal_custom_damage.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2024_1/ProcedureCustomDamageRemover.java
Labels: community review, changes FV

#4509 Fixed light sources not affecting entity model layers
  plugins/generator-1.19.4/forge-1.19.4/templates/livingentity/livingentity_renderer.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/livingentity/livingentity_renderer.java.ftl
Labels: bug

#4504 Autotags system
  plugins/generator-1.19.4/datapack-1.19.4/biome.definition.yaml
  plugins/generator-1.19.4/datapack-1.19.4/templates/biome/biometag.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/biome.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/block.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/dimension.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/musicdisc.definition.yaml
  plugins/generator-1.19.4/forge-1.19.4/templates/block/mineable_tag.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/json/carvertag.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/json/musicdisctag.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/biome.definition.yaml
  plugins/generator-1.20.1/datapack-1.20.1/templates/biome/biometag.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/biome.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/block.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/dimension.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/musicdisc.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/block/mineable_tag.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/json/carvertag.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/json/musicdisctag.json.ftl
  src/main/java/net/mcreator/element/types/Biome.java
  src/main/java/net/mcreator/element/types/Dimension.java
  src/main/java/net/mcreator/generator/Generator.java
  src/main/java/net/mcreator/generator/TagsUtils.java
  src/main/java/net/mcreator/workspace/elements/TagElement.java
Labels: new feature, community review

#4515 Require correct macOS architecture
  platform/mac/Info.plist
Labels: bug

#4339 Multiple advancement triggers
  plugins/generator-1.19.4/datapack-1.19.4/jsontriggers/biome_entered.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/jsontriggers/block_placed.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/jsontriggers/custom_trigger.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/jsontriggers/dimension_entered.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/jsontriggers/dimension_left.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/jsontriggers/item_consumed.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/jsontriggers/item_damaged.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/jsontriggers/item_in_inventory.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/jsontriggers/tick.json.ftl
  plugins/generator-1.19.4/datapack-1.19.4/templates/advancement.json.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/json/advancement.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/jsontriggers/biome_entered.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/jsontriggers/block_placed.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/jsontriggers/custom_trigger.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/jsontriggers/dimension_entered.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/jsontriggers/dimension_left.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/jsontriggers/item_consumed.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/jsontriggers/item_damaged.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/jsontriggers/item_in_inventory.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/jsontriggers/tick.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/advancement.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/json/advancement.json.ftl
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/jsontriggers/biome_entered.json
  plugins/mcreator-core/jsontriggers/block_placed.json
  plugins/mcreator-core/jsontriggers/custom_trigger.json
  plugins/mcreator-core/jsontriggers/dimension_entered.json
  plugins/mcreator-core/jsontriggers/dimension_left.json
  plugins/mcreator-core/jsontriggers/item_consumed.json
  plugins/mcreator-core/jsontriggers/item_damaged.json
  plugins/mcreator-core/jsontriggers/item_in_inventory.json
  plugins/mcreator-core/jsontriggers/tick.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/datapack/BlocklyToJSONTrigger.java
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2020_1/AchievementFixer.java
  src/main/java/net/mcreator/element/converter/v2024_1/AdvancementTriggerInverter.java
  src/main/java/net/mcreator/element/types/Achievement.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review, changes FV

#4522 Move direction mappings to datapacks
  plugins/generator-1.19.4/datapack-1.19.4/mappings/directions.yaml
  plugins/generator-1.20.1/datapack-1.20.1/mappings/directions.yaml
Labels: bug

#4524 Fix attack damage offsets
  plugins/generator-1.19.4/forge-1.19.4/templates/item/item.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/tool.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/item/item.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/tool.java.ftl
Labels: bug, community review

#4530 Fix #4529
  plugins/generator-1.19.4/forge-1.19.4/templates/elementinits/entities.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/entities.java.ftl
Labels: bug

#4510 Make build on mod element save off by default
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/preferences/data/GradleSection.java
  src/main/java/net/mcreator/ui/modgui/ModElementGUI.java
Labels: community review
