Repository MCreator/MCreator, pull requests merged in 2024-03, with the labels that each got.

#4658 Improvements to the missing features detection system
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/MCreatorApplication.java
  src/main/java/net/mcreator/ui/dialogs/workspace/WorkspaceDialogs.java
  src/main/java/net/mcreator/workspace/MissingGeneratorFeaturesException.java
  src/main/java/net/mcreator/workspace/ShareableZIPManager.java
  src/main/java/net/mcreator/workspace/Workspace.java
  src/main/java/net/mcreator/workspace/WorkspaceUtils.java
Labels: community review

#4653 Remove option to lock mod base files + user code blocks system
  plugins/generator-1.19.4/forge-1.19.4/generator.yaml
  plugins/generator-1.19.4/forge-1.19.4/templates/elementinits/blocks.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/elementinits/items.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/modbase/mod.java.ftl
  plugins/generator-1.19.4/forge-1.19.4/templates/modbase/mods.toml.ftl
  plugins/generator-1.20.1/forge-1.20.1/generator.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/blocks.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/items.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/modbase/mod.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/modbase/mods.toml.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/generator.yaml
  plugins/generator-1.20.4/neoforge-1.20.4/templates/elementinits/blocks.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/elementinits/items.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/modbase/mod.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/modbase/mods.toml.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/generator/Generator.java
  src/main/java/net/mcreator/generator/GeneratorTemplate.java
  src/main/java/net/mcreator/generator/usercode/UserCodeProcessor.java
  src/main/java/net/mcreator/ui/action/impl/workspace/RegenerateCodeAction.java
  src/main/java/net/mcreator/ui/dialogs/workspace/WorkspaceDialogs.java
  src/main/java/net/mcreator/workspace/settings/WorkspaceSettings.java
Labels: community review

#4671 Minor tag fixes
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/dialogs/AddTagDialog.java
  src/main/java/net/mcreator/ui/dialogs/NewTagDialog.java
Labels: bug

#4674 Added tabs to the common tags dialog
  src/main/java/net/mcreator/ui/dialogs/AddCommonTagsDialog.java
Labels: new feature

#4677 Fix #4676
  plugins/generator-1.20.4/neoforge-1.20.4/livingentity.definition.yaml
  plugins/generator-1.20.4/neoforge-1.20.4/plant.definition.yaml
Labels: bug

#4678 Improve recursive regeneration of procedures
  src/main/java/net/mcreator/ui/modgui/ProcedureGUI.java
Labels: bug

#4686 Fix unknown file types using image icon
  src/main/java/net/mcreator/ui/laf/FileIcons.java
Labels: bug

#4690 Codesigning for macOS
  .github/workflows/deploy.yml
  platform/mac/entitlements.plist
  platform/mac/mac.gradle
Labels: official

#4666 Move block dropping logic to loot tables
  plugins/generator-1.20.1/forge-1.20.1/block.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/plant.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/block/block.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/json/block_loot_table.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/plant/plant.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/block.definition.yaml
  plugins/generator-1.20.4/neoforge-1.20.4/plant.definition.yaml
  plugins/generator-1.20.4/neoforge-1.20.4/templates/block/block.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/json/block_loot_table.json.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/plant/plant.java.ftl
  plugins/mcreator-localization/help/default/block/use_loot_table_for_drops.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Plant.java
Labels: community review

#4697 Fix: notarization fails on macOS with new LAF
  platform/mac/mac.gradle
Labels: bug

#4408 Added Portal Igniter rarity
  plugins/generator-1.20.1/forge-1.20.1/templates/dimension/portaltrigger.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/dimension/portaltrigger.java.ftl
  src/main/java/net/mcreator/element/types/Dimension.java
  src/main/java/net/mcreator/ui/modgui/DimensionGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#4698 Minor UI fixes
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/java/blocks/EntityIteratorDependencyBlock.java
  src/main/java/net/mcreator/ui/views/AnimationMakerView.java
Labels: bug

#4705 2024.1 splash screen
  src/main/java/net/mcreator/ui/SplashScreen.java
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official

#4702 Add warning to Climb on top of powder snow
  plugins/mcreator-core/aitasks/climb_powder_snow.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/dialogs/AddCommonTagsDialog.java
Labels: bug

#4634 Codesigning for Windows
  .github/workflows/deploy.yml
  platform/windows/lib/jsign LICENSE.txt
  platform/windows/lib/jsign-6.0.jar
  platform/windows/mcreator.bat
  platform/windows/windows.gradle
Labels: official

#4700 Debugger system
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/toolboxes/toolbox_procedure.xml
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/16px/any.png
  plugins/mcreator-themes/themes/default_dark/images/16px/breakpoint.png
  plugins/mcreator-themes/themes/default_dark/images/16px/breakpoint_na.png
  plugins/mcreator-themes/themes/default_dark/images/16px/debug_resume.png
  plugins/mcreator-themes/themes/default_dark/images/16px/debug_step_into.png
  plugins/mcreator-themes/themes/default_dark/images/16px/debug_step_out.png
  plugins/mcreator-themes/themes/default_dark/images/16px/debug_step_over.png
  plugins/mcreator-themes/themes/default_dark/images/16px/debugclient.png
  src/main/java/net/mcreator/blockly/java/BlocklyToJava.java
  src/main/java/net/mcreator/blockly/java/blocks/DebugMarkerBlock.java
  src/main/java/net/mcreator/gradle/GradleUtils.java
  src/main/java/net/mcreator/java/ClassFinder.java
  src/main/java/net/mcreator/java/debug/Breakpoint.java
  src/main/java/net/mcreator/java/debug/JVMDebugClient.java
  src/main/java/net/mcreator/java/debug/JVMEventListener.java
  src/main/java/net/mcreator/ui/MCreator.java
  src/main/java/net/mcreator/ui/MainMenuBar.java
  src/main/java/net/mcreator/ui/MainToolBar.java
  src/main/java/net/mcreator/ui/action/AcceleratorMap.java
  src/main/java/net/mcreator/ui/action/ActionRegistry.java
  src/main/java/net/mcreator/ui/action/impl/gradle/DebugClientAction.java
  src/main/java/net/mcreator/ui/action/impl/gradle/RunServerAction.java
  src/main/java/net/mcreator/ui/component/JAdaptiveSplitPane.java
  src/main/java/net/mcreator/ui/debug/DebugFramesView.java
  src/main/java/net/mcreator/ui/debug/DebugMarker.java
  src/main/java/net/mcreator/ui/debug/DebugMarkersHandler.java
  src/main/java/net/mcreator/ui/debug/DebugPanel.java
  src/main/java/net/mcreator/ui/debug/DebugThreadView.java
  src/main/java/net/mcreator/ui/gradle/GradleConsole.java
  src/main/java/net/mcreator/ui/ide/CodeEditorView.java
  src/main/java/net/mcreator/ui/ide/debug/BreakpointHandler.java
  src/main/java/net/mcreator/ui/ide/debug/GutterBreakpointInfo.java
Labels: official, community review

#4711 Fix dimension type files
  plugins/generator-1.20.1/datapack-1.20.1/templates/dimension/dimension_type.json.ftl
  plugins/generator-1.20.4/datapack-1.20.4/templates/dimension/dimension_type.json.ftl
Labels: bug

#4363 Allow choosing mod element folder on creation
  src/main/java/net/mcreator/ui/dialogs/NewModElementDialog.java
  src/main/java/net/mcreator/ui/modgui/ModElementGUI.java
  src/main/java/net/mcreator/ui/procedure/ProcedureSelector.java
  src/main/java/net/mcreator/ui/procedure/RetvalProcedureSelector.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
  src/main/java/net/mcreator/ui/workspace/breadcrumb/WorkspaceFolderBreadcrumb.java
Labels: community review

#4710 Minor improvement for combo boxes
  src/main/java/net/mcreator/ui/modgui/ModElementChangedListener.java
Labels: bug

#4400 Jigsaw structures support
  plugins/generator-1.20.1/datapack-1.20.1/structure.definition.yaml
  plugins/generator-1.20.1/datapack-1.20.1/templates/structure/structure.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/structure/template_pool.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/structure.definition.yaml
  plugins/generator-1.20.4/datapack-1.20.4/structure.definition.yaml
  plugins/generator-1.20.4/datapack-1.20.4/templates/structure/structure.json.ftl
  plugins/generator-1.20.4/datapack-1.20.4/templates/structure/template_pool.json.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/structure.definition.yaml
  plugins/mcreator-localization/help/default/structure/jigsaw_fallback_pool.md
  plugins/mcreator-localization/help/default/structure/jigsaw_max_distance_from_center.md
  plugins/mcreator-localization/help/default/structure/jigsaw_pool_name.md
  plugins/mcreator-localization/help/default/structure/jigsaw_pools.md
  plugins/mcreator-localization/help/default/structure/jigsaw_size.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Structure.java
  src/main/java/net/mcreator/ui/minecraft/jigsaw/JJigsawPart.java
  src/main/java/net/mcreator/ui/minecraft/jigsaw/JJigsawPool.java
  src/main/java/net/mcreator/ui/minecraft/jigsaw/JJigsawPoolsList.java
  src/main/java/net/mcreator/ui/modgui/StructureGUI.java
  src/main/java/net/mcreator/ui/validation/validators/ResourceLocationValidator.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
  src/test/java/net/mcreator/integration/workspace/ReferencesFinderTest.java
Labels: new feature, community review

#4722 Fix missing 1.20.4 datapack mappings
  plugins/generator-1.20.4/datapack-1.20.4/mappings/achievements.yaml
  plugins/generator-1.20.4/datapack-1.20.4/mappings/particles.yaml
Labels: bug

#4721 Added variable-specific messages to some procedure blocks
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptTemplates.java
Labels: new feature

#4502 Added remaining trees and decorators
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_tree_azalea.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_tree_cherry.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/features/feature_tree_mangrove.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/features/root_placer_mangrove.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/features/tree_decorator_attached_to_leaves.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/mappings/features.yaml
  plugins/generator-1.20.1/datapack-1.20.1/utils/trees.ftl
  plugins/generator-1.20.4/datapack-1.20.4/features/feature_tree_azalea.json.ftl
  plugins/generator-1.20.4/datapack-1.20.4/features/feature_tree_cherry.json.ftl
  plugins/generator-1.20.4/datapack-1.20.4/features/feature_tree_mangrove.json.ftl
  plugins/generator-1.20.4/datapack-1.20.4/features/root_placer_mangrove.json.ftl
  plugins/generator-1.20.4/datapack-1.20.4/features/tree_decorator_attached_to_leaves.json.ftl
  plugins/generator-1.20.4/datapack-1.20.4/mappings/features.yaml
  plugins/generator-1.20.4/datapack-1.20.4/utils/trees.ftl
  plugins/mcreator-core/blockly/js/int_provider_validators.js
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/js/simple_repeating_input_mixins.js
  plugins/mcreator-core/features/feature_tree_azalea.json
  plugins/mcreator-core/features/feature_tree_cherry.json
  plugins/mcreator-core/features/feature_tree_mangrove.json
  plugins/mcreator-core/features/root_placer_mangrove.json
  plugins/mcreator-core/features/tree_decorator_attached_to_leaves.json
  plugins/mcreator-core/templates/ftpl/Tree features - Azalea tree.ftpl
  plugins/mcreator-core/templates/ftpl/Tree features - Cherry tree with beehive.ftpl
  plugins/mcreator-core/templates/ftpl/Tree features - Mangrove tree (without propagules).ftpl
  plugins/mcreator-core/templates/ftpl/Tree features - Tall mangrove tree (without propagules).ftpl
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#4725 18px Icon Vectorization
  plugins/mcreator-themes/themes/default_dark/images/18px/add.png
  plugins/mcreator-themes/themes/default_dark/images/18px/add.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/add_new.png
  plugins/mcreator-themes/themes/default_dark/images/18px/add_new.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/addtag.png
  plugins/mcreator-themes/themes/default_dark/images/18px/addtag.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/down.png
  plugins/mcreator-themes/themes/default_dark/images/18px/down.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/duplicate.png
  plugins/mcreator-themes/themes/default_dark/images/18px/duplicate.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/edit.png
  plugins/mcreator-themes/themes/default_dark/images/18px/edit.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/export.png
  plugins/mcreator-themes/themes/default_dark/images/18px/export.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/import.png
  plugins/mcreator-themes/themes/default_dark/images/18px/import.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/info.png
  plugins/mcreator-themes/themes/default_dark/images/18px/info.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/merge.png
  plugins/mcreator-themes/themes/default_dark/images/18px/merge.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/move.png
  plugins/mcreator-themes/themes/default_dark/images/18px/move.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/ok.png
  plugins/mcreator-themes/themes/default_dark/images/18px/ok.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/remove.png
  plugins/mcreator-themes/themes/default_dark/images/18px/remove.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/removeall.png
  plugins/mcreator-themes/themes/default_dark/images/18px/removeall.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/templatelib.png
  plugins/mcreator-themes/themes/default_dark/images/18px/templatelib.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/up.png
  plugins/mcreator-themes/themes/default_dark/images/18px/up.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/visibility.png
  plugins/mcreator-themes/themes/default_dark/images/18px/visibility.svg
  plugins/mcreator-themes/themes/default_dark/images/18px/warning.png
  plugins/mcreator-themes/themes/default_dark/images/18px/warning.svg
  plugins/mcreator-themes/themes/default_dark/images/tag.png
  plugins/mcreator-themes/themes/default_dark/images/tag.svg
  src/main/java/net/mcreator/ui/component/JColor.java
  src/main/java/net/mcreator/ui/component/JItemListField.java
  src/main/java/net/mcreator/ui/component/JStringListField.java
  src/main/java/net/mcreator/ui/dialogs/ProgressDialog.java
  src/main/java/net/mcreator/ui/minecraft/MCItemListField.java
  src/main/java/net/mcreator/ui/procedure/ProcedureSelector.java
  src/main/java/net/mcreator/ui/procedure/RetvalProcedureSelector.java
  src/main/java/net/mcreator/ui/validation/component/VTextField.java
  src/main/java/net/mcreator/ui/views/editor/image/layer/LayerPanel.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYGEditor.java
  src/main/java/net/mcreator/util/image/IconUtils.java
Labels: official

#4730 Fix #4724
  plugins/generator-1.20.1/forge-1.20.1/templates/feature/feature.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/feature/feature.java.ftl
Labels: bug

#4727 Add replaceable blocks to the #replaceable tag
  plugins/generator-1.20.1/forge-1.20.1/block.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/fluid.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/plant.definition.yaml
  plugins/generator-1.20.4/neoforge-1.20.4/block.definition.yaml
  plugins/generator-1.20.4/neoforge-1.20.4/fluid.definition.yaml
  plugins/generator-1.20.4/neoforge-1.20.4/plant.definition.yaml
Labels: bug

#4735 Fix tests failing on blocks with multiple output types
  src/main/java/net/mcreator/blockly/data/ToolboxBlock.java
  src/test/java/net/mcreator/integration/generator/GTFeatureBlocks.java
  src/test/java/net/mcreator/integration/generator/GTProcedureBlocks.java
Labels: bug
