Repository MCreator/MCreator, pull requests merged in 2024-05, with the labels that each got.

#4798 Fix #4797
  plugins/generator-1.20.1/forge-1.20.1/procedures/entity_set_slot.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/entity_get_slot.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/entity_inventory_foreach.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/entity_set_slot.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/itemhandler_set_slot.java.ftl
Labels: bug

#4800 Fix #4796
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/biomes.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/elementinits/biomes.java.ftl
Labels: bug, community review

#4802 Blockly (events) refactoring
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/main/java/net/mcreator/ui/blockly/BlocklyPanel.java
  src/main/java/net/mcreator/ui/blockly/JavaScriptEventListener.java
  src/main/java/net/mcreator/ui/modgui/AchievementGUI.java
  src/main/java/net/mcreator/ui/modgui/CommandGUI.java
  src/main/java/net/mcreator/ui/modgui/FeatureGUI.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/main/java/net/mcreator/ui/modgui/ProcedureGUI.java
  src/main/resources/blockly/js/mcreator_blockly.js
Labels: community review

#4350 Added glow condition to armor items
  plugins/generator-1.20.1/forge-1.20.1/templates/armor.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/armor.java.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Armor.java
  src/main/java/net/mcreator/ui/modgui/ArmorGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#4799 Java 21
  .github/workflows/deploy.yml
  .github/workflows/documentation.yml
  .github/workflows/test.yml
  .idea/compiler.xml
  .idea/misc.xml
  build.gradle
  platform/linux/linux.gradle
  platform/mac/mac.gradle
  platform/setup.gradle
  platform/windows/windows.gradle
  src/main/java/net/mcreator/blockly/BlocklyBlockUtil.java
  src/main/java/net/mcreator/blockly/BlocklyToCode.java
  src/main/java/net/mcreator/blockly/java/blocks/BinaryOperationsBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/TextJoinBlock.java
  src/main/java/net/mcreator/element/converter/v2023_3/MaterialProcedureConverter.java
  src/main/java/net/mcreator/element/converter/v2024_1/AdvancementTriggerInverter.java
  src/main/java/net/mcreator/element/types/Procedure.java
  src/main/java/net/mcreator/generator/Generator.java
  src/main/java/net/mcreator/generator/TagsUtils.java
  src/main/java/net/mcreator/java/debug/JVMDebugClient.java
  src/main/java/net/mcreator/minecraft/MinecraftImageGenerator.java
  src/main/java/net/mcreator/ui/MCreatorApplication.java
  src/main/java/net/mcreator/ui/MCreatorDropTarget.java
  src/main/java/net/mcreator/ui/MCreatorTabs.java
  src/main/java/net/mcreator/ui/blockly/BlocklyEditorToolbar.java
  src/main/java/net/mcreator/ui/component/util/TreeUtils.java
  src/main/java/net/mcreator/ui/debug/DebugFramesView.java
  src/main/java/net/mcreator/ui/dialogs/file/NativeFileDialogs.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/NewImageDialog.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/NewLayerDialog.java
  src/main/java/net/mcreator/ui/laf/renderer/AstTreeCellRendererCustom.java
  src/main/java/net/mcreator/ui/minecraft/states/entity/JEntityDataEntry.java
  src/main/java/net/mcreator/ui/modgui/CustomElementGUI.java
  src/main/java/net/mcreator/ui/modgui/ModElementGUI.java
  src/main/java/net/mcreator/ui/notifications/NotificationsRenderer.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/StampTool.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
  src/main/java/net/mcreator/util/XMLUtil.java
  src/main/java/net/mcreator/workspace/WorkspaceFileManager.java
Labels: official

#4723 Tab elements order data structure
  src/main/java/net/mcreator/generator/Generator.java
  src/main/java/net/mcreator/ui/dialogs/ElementOrderEditor.java
  src/main/java/net/mcreator/workspace/Workspace.java
  src/main/java/net/mcreator/workspace/elements/ModElement.java
  src/main/java/net/mcreator/workspace/misc/CreativeTabsOrder.java
  src/main/java/net/mcreator/workspace/misc/WorkspaceInfo.java
Labels: community review

#4772 Added entity_hurt_player Advancement Trigger
  plugins/generator-1.20.1/datapack-1.20.1/jsontriggers/entity_hurt_player.json.ftl
  plugins/generator-1.20.4/datapack-1.20.4/jsontriggers/entity_hurt_player.json.ftl
  plugins/mcreator-core/jsontriggers/$entities.json
  plugins/mcreator-core/jsontriggers/entity_hurt_player.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature, community review

#4372 Add name tag and death messages visibility related blocks
  plugins/generator-1.20.1/forge-1.20.1/procedures/team_is_deathmessage_visibility.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/team_is_nametag_visibility.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/team_set_deathmessage_visibility.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/team_set_nametag_visibility.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/team_is_deathmessage_visibility.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/team_is_nametag_visibility.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/team_set_deathmessage_visibility.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/team_set_nametag_visibility.java.ftl
  plugins/mcreator-core/procedures/team_is_deathmessage_visibility.json
  plugins/mcreator-core/procedures/team_is_nametag_visibility.json
  plugins/mcreator-core/procedures/team_set_deathmessage_visibility.json
  plugins/mcreator-core/procedures/team_set_nametag_visibility.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature, community review

#4816 Fix Blockly undo not triggering the change listener
  src/main/resources/blockly/js/mcreator_blockly.js
Labels: bug

#4713 "Skip placement" setting for features
  plugins/generator-1.20.1/datapack-1.20.1/feature.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/feature.definition.yaml
  plugins/generator-1.20.4/datapack-1.20.4/feature.definition.yaml
  plugins/generator-1.20.4/neoforge-1.20.4/feature.definition.yaml
  plugins/mcreator-localization/help/default/feature/skip_placement.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/feature/BlocklyToFeature.java
  src/main/java/net/mcreator/element/types/Feature.java
  src/main/java/net/mcreator/ui/modgui/FeatureGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review

#4436 Option to display model layers' hurt animation
  plugins/generator-1.20.1/forge-1.20.1/templates/livingentity/livingentity_renderer.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/livingentity/livingentity_renderer.java.ftl
  plugins/mcreator-localization/help/default/entity/model_layer_hurt_animation.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/main/java/net/mcreator/ui/minecraft/modellayers/JModelLayerListEntry.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review

#3503 Dynamic dependencies mutator for call procedure block
  plugins/generator-1.20.1/forge-1.20.1/procedures/_call_procedure.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/_call_procedure_at.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/procedures/_procedure_retval.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/_call_procedure.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/_call_procedure_at.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/procedures/_procedure_retval.java.ftl
  plugins/mcreator-core/blockly/js/extensions_procedure_deps.js
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/toolboxes/toolbox_procedure.xml
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/data/Dependency.java
  src/main/java/net/mcreator/blockly/java/blocks/ProcedureCallBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/ProcedureRetvalBlock.java
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2024_2/CallProcedureAtBlockConverter.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptTemplates.java
Labels: new feature, community review, changes FV

#4720 Particle scaling
  plugins/generator-1.20.1/forge-1.20.1/templates/particle.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/particle.java.ftl
  src/main/java/net/mcreator/element/types/Particle.java
  src/main/java/net/mcreator/ui/modgui/ParticleGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review

#4844 Always include dependencies mutation tag
  plugins/mcreator-core/blockly/js/extensions_procedure_deps.js
  plugins/mcreator-core/blockly/toolboxes/toolbox_procedure.xml
Labels: bug

#4706 Add the option to make ranged item projectile power vary based on use time
  plugins/generator-1.20.1/forge-1.20.1/templates/item/item.java.ftl
  plugins/generator-1.20.1/forge-1.20.1/templates/projectile/projectile.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/item/item.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/templates/projectile/projectile.java.ftl
  plugins/mcreator-localization/help/default/item/charges_power.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review

#4824 Textures system/selection refactor
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/dialogs/ListSelectorDialog.java
  src/main/java/net/mcreator/ui/dialogs/MCItemSelectorDialog.java
  src/main/java/net/mcreator/ui/dialogs/TextureMappingDialog.java
  src/main/java/net/mcreator/ui/dialogs/TypedTextureSelectorDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/ImageButtonDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/ImageDialog.java
  src/main/java/net/mcreator/ui/laf/renderer/WTextureComboBoxRenderer.java
  src/main/java/net/mcreator/ui/minecraft/TextureComboBox.java
  src/main/java/net/mcreator/ui/minecraft/TextureHolder.java
  src/main/java/net/mcreator/ui/minecraft/modellayers/JModelLayerListEntry.java
  src/main/java/net/mcreator/ui/minecraft/states/item/JItemStatesListEntry.java
  src/main/java/net/mcreator/ui/modgui/AchievementGUI.java
  src/main/java/net/mcreator/ui/modgui/ArmorGUI.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/DimensionGUI.java
  src/main/java/net/mcreator/ui/modgui/FluidGUI.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/main/java/net/mcreator/ui/modgui/MusicDiscGUI.java
  src/main/java/net/mcreator/ui/modgui/OverlayGUI.java
  src/main/java/net/mcreator/ui/modgui/PaintingGUI.java
  src/main/java/net/mcreator/ui/modgui/ParticleGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/main/java/net/mcreator/ui/modgui/PotionEffectGUI.java
  src/main/java/net/mcreator/ui/modgui/ProjectileGUI.java
  src/main/java/net/mcreator/ui/modgui/ToolGUI.java
  src/main/java/net/mcreator/ui/modgui/VillagerProfessionGUI.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYG.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYGEditor.java
  src/main/java/net/mcreator/workspace/references/ReferencesFinder.java
  src/main/java/net/mcreator/workspace/resources/Texture.java
Labels: community review

#4842 Minor improvement for mod elements list D&D logic
  src/main/java/net/mcreator/ui/component/JSelectableListMouseListenerWithDND.java
  src/main/java/net/mcreator/ui/component/MousePressListener.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
Labels: community review

#4371 Added "Raider" Behavioural characteristic
  plugins/generator-1.20.1/forge-1.20.1/livingentity.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.20.4/neoforge-1.20.4/livingentity.definition.yaml
  plugins/generator-1.20.4/neoforge-1.20.4/templates/livingentity/livingentity.java.ftl
  plugins/mcreator-localization/help/default/entity/behaviour.md
  plugins/mcreator-localization/help/default/entity/raid_celebration_sound.md
  plugins/mcreator-localization/help/default/entity/raid_spawns_counts.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, community review
