Repository MCreator/MCreator, pull requests merged in 2024-12, with the labels that each got.

#5197 A way to add elements of other mods to tags
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/minecraft/BiomeListField.java
  src/main/java/net/mcreator/ui/minecraft/DamageTypeListField.java
  src/main/java/net/mcreator/ui/minecraft/EnchantmentListField.java
  src/main/java/net/mcreator/ui/minecraft/MCItemListField.java
  src/main/java/net/mcreator/ui/minecraft/SpawnableEntityListField.java
  src/main/java/net/mcreator/ui/workspace/WorkspacePanelTags.java
Labels: new feature, community review

#5206 Fix #5204
  plugins/generator-1.20.1/forge-1.20.1/templates/elementinits/biomes.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/elementinits/biomes.java.ftl
Labels: bug

#5200 Placement generator for feature ME
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/blockly/BlocklyEditorToolbar.java
  src/main/java/net/mcreator/ui/dialogs/BlocklyHelperDialog.java
  src/main/java/net/mcreator/ui/dialogs/PlacementHelperDialog.java
  src/main/java/net/mcreator/ui/modgui/FeatureGUI.java
  src/test/java/net/mcreator/integration/ui/DialogsTest.java
Labels: new feature, community review

#5208 Several dimension settings
  plugins/generator-1.20.1/datapack-1.20.1/dimension.definition.yaml
  plugins/generator-1.20.1/datapack-1.20.1/templates/dimension/dimension_end.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/dimension/dimension_nether.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/dimension/dimension_overworld.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/dimension/dimension_type.json.ftl
  plugins/generator-1.20.1/datapack-1.20.1/templates/dimension/overworld_noise_router.json.ftl
  plugins/generator-1.20.1/forge-1.20.1/dimension.definition.yaml
  plugins/generator-1.20.1/forge-1.20.1/templates/dimension/dimension.java.ftl
  plugins/generator-1.21.1/datapack-1.21.1/dimension.definition.yaml
  plugins/generator-1.21.1/datapack-1.21.1/templates/dimension/dimension_end.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/templates/dimension/dimension_nether.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/templates/dimension/dimension_overworld.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/templates/dimension/dimension_type.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/templates/dimension/overworld_noise_router.json.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/dimension.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/dimension/dimension.java.ftl
  plugins/mcreator-localization/help/default/dimension/ambient_light.md
  plugins/mcreator-localization/help/default/dimension/can_use_beds.md
  plugins/mcreator-localization/help/default/dimension/cloud_height.md
  plugins/mcreator-localization/help/default/dimension/default_effects.md
  plugins/mcreator-localization/help/default/dimension/generate_aquifers.md
  plugins/mcreator-localization/help/default/dimension/generate_ore_veins.md
  plugins/mcreator-localization/help/default/dimension/has_clouds.md
  plugins/mcreator-localization/help/default/dimension/has_raids.md
  plugins/mcreator-localization/help/default/dimension/horizontal_noise_size.md
  plugins/mcreator-localization/help/default/dimension/is_dark.md
  plugins/mcreator-localization/help/default/dimension/piglin_safe.md
  plugins/mcreator-localization/help/default/dimension/sea_level.md
  plugins/mcreator-localization/help/default/dimension/sky_type.md
  plugins/mcreator-localization/help/default/dimension/sleep_result.md
  plugins/mcreator-localization/help/default/dimension/spawning_block_light_limit.md
  plugins/mcreator-localization/help/default/dimension/spawning_light_limit.md
  plugins/mcreator-localization/help/default/dimension/sun_height_affects_fog.md
  plugins/mcreator-localization/help/default/dimension/use_custom_effects.md
  plugins/mcreator-localization/help/default/dimension/vertical_noise_size.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2024_4/DimensionSettingsConverter.java
  src/main/java/net/mcreator/element/types/Dimension.java
  src/main/java/net/mcreator/ui/modgui/DimensionGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature, changes FV

#5226 Some missing reference finder annotations
  src/main/java/net/mcreator/element/types/Armor.java
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Dimension.java
  src/main/java/net/mcreator/element/types/Fluid.java
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/element/types/Tool.java
Labels: bug

#5233 "Fix" #5232
  plugins/mcreator-core/features/feature_lake.json
  plugins/mcreator-core/templates/ftpl/Lake features - Custom fluid lake.ftpl
  plugins/mcreator-localization/lang/texts.properties
Labels: bug

#5229 Extra templates for Blockly blocks
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/blockstate_get_direction.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/blockstate_with_direction.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/blockstate_with_enum_property.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/blockstate_with_integer_property.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/utils/blockstate_props/get_direction.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/utils/blockstate_props/with_direction.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/utils/blockstate_props/with_enum_property.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/utils/blockstate_props/with_integer_property.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/command.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/procedure.java.ftl
  src/main/java/net/mcreator/blockly/BlocklyToCode.java
  src/main/java/net/mcreator/element/types/Achievement.java
  src/main/java/net/mcreator/element/types/Command.java
  src/main/java/net/mcreator/element/types/Feature.java
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/main/java/net/mcreator/element/types/Procedure.java
  src/main/java/net/mcreator/generator/blockly/BlocklyBlockCodeGenerator.java
Labels: new feature, community review
