Repository MCreator/MCreator, pull requests merged in 2025-08, with the labels that each got.

#5699 Fix block bases resetting some properties when editing element
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
Labels: bug

#5710 Add Block and Item Textures for Minecraft 1.21.8
  plugins/mcreator-core/datalists/icons/BLACK_HARNESS.png
  plugins/mcreator-core/datalists/icons/BLUE_EGG.png
  plugins/mcreator-core/datalists/icons/BLUE_HARNESS.png
  plugins/mcreator-core/datalists/icons/BROWN_EGG.png
  plugins/mcreator-core/datalists/icons/BROWN_HARNESS.png
  plugins/mcreator-core/datalists/icons/BUSH.png
  plugins/mcreator-core/datalists/icons/CACTUS_FLOWER.png
  plugins/mcreator-core/datalists/icons/CYAN_HARNESS.png
  plugins/mcreator-core/datalists/icons/DRIED_GHAST.png
  plugins/mcreator-core/datalists/icons/FIREFLY_BUSH.png
  plugins/mcreator-core/datalists/icons/GRAY_HARNESS.png
  plugins/mcreator-core/datalists/icons/GREEN_HARNESS.png
  plugins/mcreator-core/datalists/icons/HAPPY_GHAST_SPAWN_EGG.png
  plugins/mcreator-core/datalists/icons/LEAF_LITTER.png
  plugins/mcreator-core/datalists/icons/LIGHT_BLUE_HARNESS.png
  plugins/mcreator-core/datalists/icons/LIGHT_GRAY_HARNESS.png
  plugins/mcreator-core/datalists/icons/LIME_HARNESS.png
  plugins/mcreator-core/datalists/icons/MAGENTA_HARNESS.png
  plugins/mcreator-core/datalists/icons/MUSIC_DISC_LAVA_CHICKEN.png
  plugins/mcreator-core/datalists/icons/MUSIC_DISC_TEARS.png
  plugins/mcreator-core/datalists/icons/ORANGE_HARNESS.png
  plugins/mcreator-core/datalists/icons/PINK_HARNESS.png
  plugins/mcreator-core/datalists/icons/PURPLE_HARNESS.png
  plugins/mcreator-core/datalists/icons/RED_HARNESS.png
  plugins/mcreator-core/datalists/icons/SHORT_DRY_GRASS.png
  plugins/mcreator-core/datalists/icons/TALL_DRY_GRASS.png
  plugins/mcreator-core/datalists/icons/TEST_BLOCK.png
  plugins/mcreator-core/datalists/icons/TEST_INSTANCE_BLOCK.png
  plugins/mcreator-core/datalists/icons/WHITE_HARNESS.png
  plugins/mcreator-core/datalists/icons/WILDFLOWERS.png
  plugins/mcreator-core/datalists/icons/YELLOW_HARNESS.png
Labels: official, new feature

#5504 Loot table preview
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/minecraft/MinecraftImageGenerator.java
  src/main/java/net/mcreator/ui/minecraft/loottable/JLootTablePoolsList.java
  src/main/java/net/mcreator/ui/minecraft/loottable/LootTablePreview.java
  src/main/java/net/mcreator/ui/modgui/LootTableGUI.java
Labels: community review, new feature

#5703 Added support for fixed item animations
  plugins/generator-1.21.1/neoforge-1.21.1/templates/item/item_renderer.java.ftl
  plugins/generator-1.21.8/neoforge-1.21.8/templates/item/item_renderer.java.ftl
Labels: community review

#5707 Added some procedure triggers to item ME
  plugins/generator-1.21.1/neoforge-1.21.1/templates/item/item.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/utils/triggers.java.ftl
  plugins/generator-1.21.8/neoforge-1.21.8/templates/item/item.java.ftl
  plugins/generator-1.21.8/neoforge-1.21.8/utils/triggers.java.ftl
  plugins/mcreator-localization/help/default/item/every_tick_while_using.md
  plugins/mcreator-localization/help/default/item/on_item_entity_destroyed.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature
