Repository MCreator/MCreator, pull requests merged in 2025-01, with the labels that each got.

#5243 2025.1 kick-off
  .github/workflows/deploy.yml
  .github/workflows/documentation.yml
  .github/workflows/test.yml
  build.gradle
  gradlew
  platform/setup.gradle
  src/main/java/net/mcreator/generator/template/base/DefaultFreemarkerConfiguration.java
  src/main/resources/mcreator.conf
  src/test/resources/workspaces/test-2024.4.zip
Labels: official

#5259 2025.1 splash screen
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official

#5254 Improve armor texture import
  src/main/java/net/mcreator/ui/dialogs/TextureImportDialogs.java
  src/main/java/net/mcreator/ui/modgui/ArmorGUI.java
  src/main/java/net/mcreator/workspace/resources/CustomTexture.java
Labels: bug

#5230 Blockly resource location field
  plugins/mcreator-core/blockly/js/field_resourcelocation.js
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-core/features/block_holderset_tag.json
  plugins/mcreator-core/features/feature_geode_simple.json
  plugins/mcreator-core/features/feature_root_system.json
  plugins/mcreator-core/features/feature_vegetation_patch.json
  plugins/mcreator-core/features/feature_waterlogged_vegetation_patch.json
  plugins/mcreator-core/features/rule_test_tag_match.json
  src/test/java/net/mcreator/integration/generator/BlocklyTestUtil.java
Labels: new feature

#5245 Default message for empty single entry selectors
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/component/JSingleEntrySelector.java
  src/main/java/net/mcreator/ui/modgui/AchievementGUI.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
Labels: new feature

#5216 Unused Blockly blocks cleanup button
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/main/resources/blockly/js/mcreator_blockly.js
Labels: new feature

#5228 Multiline dynamic GUI tooltips support
  plugins/generator-1.20.1/forge-1.20.1/templates/gui/gui_window.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/gui/gui_window.java.ftl
Labels: new feature

#5285 Carving mask placement remover
  plugins/generator-1.20.1/datapack-1.20.1/features/placement_carving_mask.json.ftl
  plugins/generator-1.21.1/datapack-1.21.1/features/placement_carving_mask.json.ftl
  plugins/mcreator-core/features/placement_carving_mask.json
  plugins/mcreator-localization/lang/texts.properties
  plugins/ref-generator-1.21.1/datapack-1.21.1/features/placement_carving_mask.json.ftl
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2025_1/FeatureCarvingMaskRemover.java
Labels: changes FV

#5290 [Bugfix] Sprite with the same width and height would cause some errors
  src/main/java/net/mcreator/element/parts/gui/Sprite.java
Labels: bug

#5288 Ported Particle [1.21.4]
  plugins/generator-1.20.1/forge-1.20.1/templates/particle.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/particle.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/generator.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/particle.definition.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/templates/elementinits/particles.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/elementinits/particletypes.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/json/particle.json.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/particle.java.ftl
  plugins/mcreator-localization/help/default/particle/emissive_rendering.md
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2025_1/ParticleLitRemover.java
  src/main/java/net/mcreator/element/types/Particle.java
  src/main/java/net/mcreator/ui/modgui/ParticleGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: changes FV

#5262 Minor improvement to entry lists
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/component/entries/JSimpleListEntry.java
  src/main/java/net/mcreator/ui/component/entries/JSingleEntriesList.java
  src/main/java/net/mcreator/ui/minecraft/potions/JPotionListEntry.java
Labels: new feature

#5303 Add 1.21.4 Block and Item Icons
  plugins/mcreator-core/datalists/icons/BLACK_BUNDLE.png
  plugins/mcreator-core/datalists/icons/BLUE_BUNDLE.png
  plugins/mcreator-core/datalists/icons/BORDURE_INDENTED_BANNER_PATTERN.png
  plugins/mcreator-core/datalists/icons/BROWN_BUNDLE.png
  plugins/mcreator-core/datalists/icons/CHISELED_RESIN_BRICKS.png
  plugins/mcreator-core/datalists/icons/CLOSED_EYEBLOSSOM.png
  plugins/mcreator-core/datalists/icons/CREAKING_HEART.png
  plugins/mcreator-core/datalists/icons/CREAKING_SPAWN_EGG.png
  plugins/mcreator-core/datalists/icons/CYAN_BUNDLE.png
  plugins/mcreator-core/datalists/icons/FIELD_MASONED_BANNER_PATTERN.png
  plugins/mcreator-core/datalists/icons/GRAY_BUNDLE.png
  plugins/mcreator-core/datalists/icons/GREEN_BUNDLE.png
  plugins/mcreator-core/datalists/icons/LIGHT_BLUE_BUNDLE.png
  plugins/mcreator-core/datalists/icons/LIGHT_GRAY_BUNDLE.png
  plugins/mcreator-core/datalists/icons/LIME_BUNDLE.png
  plugins/mcreator-core/datalists/icons/MAGENTA_BUNDLE.png
  plugins/mcreator-core/datalists/icons/OPEN_EYEBLOSSOM.png
  plugins/mcreator-core/datalists/icons/ORANGE_BUNDLE.png
  plugins/mcreator-core/datalists/icons/PALE_HANGING_MOSS.png
  plugins/mcreator-core/datalists/icons/PALE_MOSS_BLOCK.png
  plugins/mcreator-core/datalists/icons/PALE_MOSS_CARPET.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_BOAT.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_BUTTON.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_CHEST_BOAT.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_DOOR.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_FENCE.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_FENCE_GATE.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_HANGING_SIGN.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_HANGING_SIGN_ITEM.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_LEAVES.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_LOG.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_PLANKS.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_PRESSURE_PLATE.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_SAPLING.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_SIGN.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_SLAB.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_STAIRS.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_TRAPDOOR.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_WALL_HANGING_SIGN.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_WALL_SIGN.png
  plugins/mcreator-core/datalists/icons/PALE_OAK_WOOD.png
  plugins/mcreator-core/datalists/icons/PINK_BUNDLE.png
  plugins/mcreator-core/datalists/icons/POTTED_CLOSED_EYEBLOSSOM.png
  plugins/mcreator-core/datalists/icons/POTTED_OPEN_EYEBLOSSOM.png
  plugins/mcreator-core/datalists/icons/POTTED_PALE_OAK_SAPLING.png
  plugins/mcreator-core/datalists/icons/PURPLE_BUNDLE.png
  plugins/mcreator-core/datalists/icons/RED_BUNDLE.png
  plugins/mcreator-core/datalists/icons/RESIN_BLOCK.png
  plugins/mcreator-core/datalists/icons/RESIN_BRICK.png
  plugins/mcreator-core/datalists/icons/RESIN_BRICKS.png
  plugins/mcreator-core/datalists/icons/RESIN_BRICK_SLAB.png
  plugins/mcreator-core/datalists/icons/RESIN_BRICK_STAIRS.png
  plugins/mcreator-core/datalists/icons/RESIN_BRICK_WALL.png
  plugins/mcreator-core/datalists/icons/RESIN_CLUMP.png
  plugins/mcreator-core/datalists/icons/STANDING_PALE_OAK_SIGN.png
  plugins/mcreator-core/datalists/icons/STRIPPED_PALE_OAK_LOG.png
  plugins/mcreator-core/datalists/icons/STRIPPED_PALE_OAK_WOOD.png
  plugins/mcreator-core/datalists/icons/WHITE_BUNDLE.png
  plugins/mcreator-core/datalists/icons/YELLOW_BUNDLE.png
Labels: official, new feature
