Repository MCreator/MCreator, pull requests merged in 2025-04, with the labels that each got.

#5406 Updated some datalist textures
  plugins/mcreator-core/datalists/effects.yaml
  plugins/mcreator-core/datalists/mapcolors.yaml
Labels: new feature

#5401 Optional tags support
  plugins/generator-1.21.1/datapack-1.21.1/templates/tags.json.ftl
  plugins/generator-1.21.4/datapack-1.21.4/templates/tags.json.ftl
  plugins/mcreator-localization/lang/texts.properties
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#5350 Add vibration sensitivity to Block ME
  plugins/generator-1.21.1/neoforge-1.21.1/block.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/block.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/blockentity.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/block.definition.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/templates/block/block.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/block/blockentity.java.ftl
  plugins/mcreator-localization/help/default/block/on_received_vibration.md
  plugins/mcreator-localization/help/default/block/receive_vibration_condition.md
  plugins/mcreator-localization/help/default/block/sensitive_to_vibration.md
  plugins/mcreator-localization/help/default/block/vibration_sensitivity_radius.md
  plugins/mcreator-localization/help/default/block/vibrational_events.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: community review, new feature

#5385 "Null comparison" procedure block
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  plugins/mcreator-core/blockly/js/mcreator_extensions.js
  plugins/mcreator-core/blockly/toolboxes/toolbox_procedure.xml
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/blockly/java/BlocklyToJava.java
  src/main/java/net/mcreator/blockly/java/blocks/NullComparisonBlock.java
Labels: new feature

#5438 Remove unused/duplicate mcitem entries
  plugins/generator-1.21.1/datapack-1.21.1/mappings/blocksitems.yaml
  plugins/generator-1.21.4/datapack-1.21.4/mappings/blocksitems.yaml
  plugins/generator-addon-1.21.x/addon-1.21.x/mappings/blocksitems.yaml
  plugins/mcreator-core/datalists/blocksitems.yaml
  plugins/mcreator-core/datalists/icons/DAYLIGHT_DETECTOR_INVERTED.png
  plugins/mcreator-core/datalists/icons/LEAVES2.png
  plugins/mcreator-core/datalists/icons/LIT_REDSTONE_LAMP.png
  plugins/mcreator-core/datalists/icons/LIT_REDSTONE_ORE.png
  plugins/mcreator-core/datalists/icons/LOG2.png
  plugins/mcreator-core/datalists/icons/POWERED_COMPARATOR.png
  plugins/mcreator-core/datalists/icons/POWERED_REPEATER.png
  plugins/mcreator-core/datalists/icons/PURPUR_DOUBLE_SLAB.png
  plugins/mcreator-core/datalists/icons/STRUCTURE_BLOCK#1.png
  plugins/mcreator-core/datalists/icons/STRUCTURE_BLOCK#2.png
  plugins/mcreator-core/datalists/icons/STRUCTURE_BLOCK#3.png
  plugins/mcreator-core/datalists/icons/STRUCTURE_BLOCK#4.png
  plugins/mcreator-core/datalists/icons/TALLGRASS#0.png
  plugins/mcreator-core/datalists/icons/TALLGRASS.png
  plugins/mcreator-core/datalists/icons/UNLIT_REDSTONE_TORCH.png
Labels: community review

#5415 Added item holding renderer to villager and witch
  plugins/generator-1.21.1/neoforge-1.21.1/templates/livingentity/livingentity_renderer.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/livingentity/livingentity_renderer.java.ftl
  plugins/mcreator-localization/lang/texts.properties
Labels: community review

#5410 [UX] Reopen some dialogs, not only close
  src/main/java/net/mcreator/ui/dialogs/NewVariableDialog.java
  src/main/java/net/mcreator/ui/validation/optionpane/VOptionPane.java
Labels: community review

#5432 Added Block Java Models Support
  plugins/generator-1.21.1/neoforge-1.21.1/block.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/block.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/blockentityrenderer.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/block.definition.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/templates/block/block.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/block/blockentityrenderer.java.ftl
  plugins/mcreator-localization/help/default/block/model.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
Labels: community review, new feature

#5436 Simplify some image editor shortcuts
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/MainMenuBar.java
  src/main/java/net/mcreator/ui/action/AcceleratorMap.java
  src/main/java/net/mcreator/ui/action/ActionRegistry.java
  src/main/java/net/mcreator/ui/views/editor/image/action/ImageEditorSwapColorsAction.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/component/ColorSelector.java
Labels: new feature

#5445 Improvements to banner pattern element
  plugins/mcreator-localization/help/default/banner_pattern/banner_preview.md
  plugins/mcreator-localization/help/default/banner_pattern/shield_preview.md
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/mod_preview_bases/banner_pattern_preview_base.png
  plugins/mcreator-themes/themes/default_dark/images/mod_preview_bases/shield_pattern_preview_base.png
  src/main/java/net/mcreator/element/types/BannerPattern.java
  src/main/java/net/mcreator/minecraft/MinecraftImageGenerator.java
  src/main/java/net/mcreator/ui/modgui/BannerPatternGUI.java
Labels: community review, new feature

#5433 Remove legacy material setting from blocks
  plugins/generator-1.21.1/neoforge-1.21.1/block.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/mappings/materials.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/mappings/noteblockinstruments.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/block.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/block.definition.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/mappings/materials.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/mappings/noteblockinstruments.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/templates/block/block.java.ftl
  plugins/mcreator-core/datalists/blockstateproperties.yaml
  plugins/mcreator-core/datalists/materials.yaml
  plugins/mcreator-core/datalists/noteblockinstruments.yaml
  plugins/mcreator-localization/help/default/block/block_set_type.md
  plugins/mcreator-localization/help/default/block/ignited_by_lava.md
  plugins/mcreator-localization/help/default/block/material.md
  plugins/mcreator-localization/help/default/block/note_block_instrument.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2025_2/BlockLegacyMaterialRemover.java
  src/main/java/net/mcreator/element/parts/Material.java
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/minecraft/ElementUtil.java
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/main/java/net/mcreator/ui/dialogs/tools/OrePackMakerTool.java
  src/main/java/net/mcreator/ui/dialogs/tools/WoodPackMakerTool.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: changes FV, new feature

#5435 Add game event trigger procedure block
  plugins/generator-1.21.1/neoforge-1.21.1/mappings/gameevents.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/world_trigger_gameevent.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/mappings/gameevents.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/procedures/world_trigger_gameevent.java.ftl
  plugins/mcreator-core/procedures/world_trigger_gameevent.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
Labels: new feature

#5460 Decouple canvas (container for all image related editor data)
  src/main/java/net/mcreator/ui/views/editor/image/ImageMakerView.java
  src/main/java/net/mcreator/ui/views/editor/image/canvas/Canvas.java
  src/main/java/net/mcreator/ui/views/editor/image/canvas/CanvasRenderer.java
  src/main/java/net/mcreator/ui/views/editor/image/canvas/Selection.java
  src/main/java/net/mcreator/ui/views/editor/image/clipboard/transferables/CanvasTransferable.java
  src/main/java/net/mcreator/ui/views/editor/image/layer/Layer.java
  src/main/java/net/mcreator/ui/views/editor/image/layer/LayerPanel.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/AbstractDrawingTool.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/ColorPickerTool.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/DrawingTool.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/LineTool.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/ShapeTool.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/StampTool.java
  src/main/java/net/mcreator/ui/views/editor/image/versioning/change/Addition.java
  src/main/java/net/mcreator/ui/views/editor/image/versioning/change/CanvasResize.java
  src/main/java/net/mcreator/ui/views/editor/image/versioning/change/Consolidation.java
  src/main/java/net/mcreator/ui/views/editor/image/versioning/change/Modification.java
  src/main/java/net/mcreator/ui/views/editor/image/versioning/change/Relocation.java
Labels: official

#5468 Removed option for no layer images in image editor
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/dialogs/imageeditor/NewImageDialog.java
  src/main/java/net/mcreator/ui/views/editor/image/ImageMakerView.java
Labels: bug

#5430 Rework of guistate and converter for guistate dependency
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/gui_get_text_textfield.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/gui_get_value_checkbox.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/gui_set_text_textfield.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/elementinits/menus.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/elementinits/screens.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/gui/gui_container.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/gui/gui_msg_button.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/gui/gui_msg_slot.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/gui/gui_window.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/procedures/gui_get_text_textfield.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/procedures/gui_get_value_checkbox.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/procedures/gui_set_text_textfield.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/elementinits/menus.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/elementinits/screens.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/gui/gui_container.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/gui/gui_msg_button.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/gui/gui_msg_slot.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/gui/gui_window.java.ftl
  plugins/mcreator-core/procedures/gui_get_text_textfield.json
  plugins/mcreator-core/procedures/gui_get_value_checkbox.json
  plugins/mcreator-core/procedures/gui_set_text_textfield.json
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/GeneratableElement.java
  src/main/java/net/mcreator/element/converter/ConverterRegistry.java
  src/main/java/net/mcreator/element/converter/v2025_2/GuistateProceduresConverter.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/ButtonDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/EntityModelDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/ImageButtonDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/ImageDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/InputSlotDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/LabelDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/OutputSlotDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/SpriteDialog.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/TooltipDialog.java
  src/main/java/net/mcreator/ui/modgui/CustomGUIGUI.java
Labels: community review, changes FV

#5471 Added double shift-click search function
  src/main/java/net/mcreator/ui/MCreator.java
  src/main/java/net/mcreator/ui/blockly/BlocklyEditorToolbar.java
  src/main/java/net/mcreator/ui/gradle/ConsoleSearchBar.java
  src/main/java/net/mcreator/ui/gradle/GradleConsole.java
  src/main/java/net/mcreator/ui/ide/CodeEditorView.java
  src/main/java/net/mcreator/ui/ide/SearchBar.java
  src/main/java/net/mcreator/ui/modgui/ProcedureGUI.java
  src/main/java/net/mcreator/ui/search/GlobalSearchListener.java
  src/main/java/net/mcreator/ui/search/ISearchable.java
  src/main/java/net/mcreator/ui/search/ITextFieldSearchable.java
  src/main/java/net/mcreator/ui/workspace/AbstractMainWorkspacePanel.java
Labels: new feature

#5458 Added search function to ModElementGUI
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/modgui/ModElementGUI.java
  src/main/java/net/mcreator/ui/modgui/ModElementGUISearch.java
  src/main/java/net/mcreator/ui/search/ITextFieldSearchable.java
Labels: community review, new feature
