Repository MCreator/MCreator, pull requests merged in 2025-05, with the labels that each got.

#5459 Support for 2D icons for items/tools in GUI
  plugins/generator-1.21.1/neoforge-1.21.1/templates/json/item.json.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/json/item_cmodel.json.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/json/item_cmodel_obj.json.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/json/item_model_blocking.json.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/json/rangeditem.json.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/json/tool.json.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/item.definition.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/templates/json/item_gui.json.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/json/model_item.json.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/json/model_item_shield.json.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/tool.definition.yaml
  plugins/mcreator-localization/help/default/item/gui_texture.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/element/types/Tool.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/main/java/net/mcreator/ui/modgui/ToolGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#5413 Adding Text Field Sync
  plugins/generator-1.21.1/neoforge-1.21.1/gui.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/elementinits/menus.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/gui/gui_container.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/gui/gui_msg_menustate.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/gui.definition.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/templates/elementinits/menus.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/gui/gui_container.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/gui/gui_msg_menustate.java.ftl
  plugins/mcreator-core/procedures/gui_get_text_textfield.json
  plugins/mcreator-core/procedures/gui_get_value_checkbox.json
  plugins/mcreator-core/procedures/gui_set_text_textfield.json
  plugins/mcreator-localization/lang/texts.properties
Labels: community review, new feature

#5442 Allow executing procedures with null dependencies
  plugins/generator-1.21.1/neoforge-1.21.1/templates/procedure.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/procedure.java.ftl
  plugins/mcreator-localization/help/default/procedure/skip_dependency_null_check.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Procedure.java
  src/main/java/net/mcreator/ui/modgui/ProcedureGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#5482 Enhance VersionManager to support complex changes as initial image revision
  src/main/java/net/mcreator/ui/views/editor/image/versioning/VersionManager.java
Labels: bug

#5477 Added parameter to projectile ME to disable gravity
  plugins/generator-1.21.1/neoforge-1.21.1/templates/projectile/projectile.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/projectile/projectile.java.ftl
  plugins/mcreator-localization/help/default/projectile/disable_gravity.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Projectile.java
  src/main/java/net/mcreator/ui/modgui/ProjectileGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: community review, new feature

#5476 Added "Is entity attack swinging" procedure block
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/entity_is_attack_swinging.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/procedures/entity_is_attack_swinging.java.ftl
  plugins/mcreator-core/procedures/entity_is_attack_swinging.json
  plugins/mcreator-localization/lang/texts.properties
Labels: new feature

#5461 Added some item settings to block/plant ME
  plugins/generator-1.21.1/neoforge-1.21.1/block.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/plant.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/block.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/elementinits/blocks.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/elementinits/items.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/json/block_loot_table.json.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/plant/plant.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/block.definition.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/plant.definition.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/templates/block/block.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/elementinits/items.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/json/block_loot_table.json.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/plant/plant.java.ftl
  plugins/mcreator-localization/help/default/common/has_block_item.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/element/types/interfaces/IBlock.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#5492 [Bugfix] Player right-click global procedure triggers fired inconsistently in some cases
  plugins/generator-1.21.1/neoforge-1.21.1/triggers/player_right_click_block.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/triggers/player_right_click_empty_hand.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/triggers/player_right_click_entity.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/triggers/player_right_click_block.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/triggers/player_right_click_empty_hand.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/triggers/player_right_click_entity.java.ftl
Labels: community review, bug

#5472 Image editor metadata system
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/preferences/data/ImageEditorSection.java
  src/main/java/net/mcreator/preferences/data/PreferencesData.java
  src/main/java/net/mcreator/ui/dialogs/TextureImportDialogs.java
  src/main/java/net/mcreator/ui/minecraft/recourcepack/ResourcePackEditor.java
  src/main/java/net/mcreator/ui/views/editor/image/ImageMakerView.java
  src/main/java/net/mcreator/ui/views/editor/image/canvas/Canvas.java
  src/main/java/net/mcreator/ui/views/editor/image/metadata/MetadataManager.java
  src/main/java/net/mcreator/ui/views/editor/image/metadata/MetadataOutdatedException.java
  src/main/java/net/mcreator/ui/workspace/resources/WorkspacePanelTextures.java
Labels: community review, new feature

#5493 Small improvements
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/block.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/dimension/portaltrigger.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/fluid/fluidblock.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/fluid/fluidbucket.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/item/item.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/plant/plant.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/block/block.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/dimension/portaltrigger.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/fluid/fluidblock.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/fluid/fluidbucket.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/item/item.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/plant/plant.java.ftl
  src/main/java/net/mcreator/element/types/Fluid.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/ui/modgui/FluidGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#5508 Item fixes and improvements
  plugins/generator-1.21.4/neoforge-1.21.4/templates/item/item.java.ftl
  plugins/mcreator-localization/help/default/item/when_finish_using.md
  plugins/mcreator-localization/help/default/item/when_stopped_using.md
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
Labels: bug

#5516 Tooltips over GUI slots cause double tooltip to be shown
  plugins/generator-1.21.1/neoforge-1.21.1/templates/gui/gui_window.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/gui/gui_window.java.ftl
Labels: bug

#5522 Fix wrong entity scaling with baby models
  plugins/generator-1.21.1/neoforge-1.21.1/templates/livingentity/livingentity_renderer.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/livingentity/livingentity_renderer.java.ftl
Labels: community review, bug

#5515 Improve "has player in inventory" procedure block
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/entity_has_item_inventory.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/utils/entity/entity_has_item_inventory.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/procedures/entity_has_item_inventory.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/procedures/utils/entity/entity_has_item_inventory.java.ftl
  plugins/mcreator-localization/lang/texts.properties
Labels: community review, bug

#5520 Improvements to math dual operation block
  plugins/mcreator-core/blockly/js/mcreator_blocks.js
  src/main/java/net/mcreator/blockly/java/BlocklyToJava.java
  src/main/java/net/mcreator/blockly/java/JavaKeywordsMap.java
  src/main/java/net/mcreator/blockly/java/ProcedureCodeOptimizer.java
  src/main/java/net/mcreator/blockly/java/blocks/LogicBinaryOperationsBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/NumberBinaryOperationsBlock.java
  src/main/java/net/mcreator/blockly/java/blocks/SingularMathOperationsBlock.java
  src/test/java/net/mcreator/integration/generator/GTProcedureBlocks.java
Labels: community review, new feature, bug
