Repository MCreator/MCreator, pull requests merged in 2025-09, with the labels that each got.

#5720 Conditional custom item Java model animations
  plugins/generator-1.21.1/neoforge-1.21.1/templates/item/item_renderer.java.ftl
  plugins/generator-1.21.8/neoforge-1.21.8/templates/item/item_renderer.java.ftl
  plugins/mcreator-localization/help/default/item/model_animations.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/ui/minecraft/itemanimations/JItemAnimationList.java
  src/main/java/net/mcreator/ui/minecraft/itemanimations/JItemAnimationListEntry.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: community review

#5702 Elements can now be excluded with !
  src/main/java/net/mcreator/ui/workspace/WorkspacePanel.java
Labels: new feature

#5510 Add a Slider GUI component
  plugins/generator-1.21.1/neoforge-1.21.1/gui.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/gui_get_value_slider.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/gui_set_value_slider.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/gui/gui_msg_menustate.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/gui/gui_msg_slider.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/gui/gui_window.java.ftl
  plugins/generator-1.21.8/neoforge-1.21.8/gui.definition.yaml
  plugins/generator-1.21.8/neoforge-1.21.8/procedures/gui_get_value_slider.java.ftl
  plugins/generator-1.21.8/neoforge-1.21.8/procedures/gui_set_value_slider.java.ftl
  plugins/generator-1.21.8/neoforge-1.21.8/templates/gui/gui_msg_menustate.java.ftl
  plugins/generator-1.21.8/neoforge-1.21.8/templates/gui/gui_msg_slider.java.ftl
  plugins/generator-1.21.8/neoforge-1.21.8/templates/gui/gui_window.java.ftl
  plugins/mcreator-core/procedures/gui_get_value_slider.json
  plugins/mcreator-core/procedures/gui_set_value_slider.json
  plugins/mcreator-localization/help/default/gui/when_slider_moves.md
  plugins/mcreator-localization/lang/texts.properties
  plugins/mcreator-themes/themes/default_dark/images/wysiwyg_editor/addslider.png
  src/main/java/net/mcreator/element/parts/gui/GUIComponent.java
  src/main/java/net/mcreator/element/parts/gui/Slider.java
  src/main/java/net/mcreator/element/types/GUI.java
  src/main/java/net/mcreator/minecraft/MinecraftImageGenerator.java
  src/main/java/net/mcreator/ui/dialogs/wysiwyg/SliderDialog.java
  src/main/java/net/mcreator/ui/wysiwyg/WYSIWYGEditor.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: community review, new feature

#5726 Plugin YAML files merging
  src/main/java/net/mcreator/generator/DefinitionsProvider.java
  src/main/java/net/mcreator/generator/GeneratorConfiguration.java
  src/main/java/net/mcreator/generator/GeneratorVariableTypes.java
  src/main/java/net/mcreator/generator/mapping/MappingLoader.java
  src/main/java/net/mcreator/minecraft/DataListLoader.java
  src/main/java/net/mcreator/plugin/modapis/ModAPIManager.java
  src/main/java/net/mcreator/util/yaml/AdaptiveYamlMergePolicy.java
  src/main/java/net/mcreator/util/yaml/YamlMerge.java
  src/main/java/net/mcreator/util/yaml/YamlUtil.java
Labels: community review

#5769 Fixes #5765, Fixes #5766
  plugins/mcreator-core/procedures/world_make_portal.json
  src/main/java/net/mcreator/ui/blockly/BlocklyJavascriptBridge.java
  src/test/java/net/mcreator/integration/generator/BlocklyTestUtil.java
Labels: bug

#5767 Improvements to code editor search/replace bars
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/ide/ReplaceBar.java
  src/main/java/net/mcreator/ui/ide/SearchBar.java
  src/main/java/net/mcreator/ui/ide/action/ShowFindAction.java
  src/main/java/net/mcreator/ui/ide/action/ShowReplaceAction.java
Labels: new feature

#5759 Xp amount setting for blocks and plants
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/block.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/plant/plant.java.ftl
  plugins/generator-1.21.8/neoforge-1.21.8/templates/block/block.java.ftl
  plugins/generator-1.21.8/neoforge-1.21.8/templates/plant/plant.java.ftl
  plugins/mcreator-localization/help/default/block/xp_amount.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#5768 Max imports preference
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/java/ImportFormat.java
  src/main/java/net/mcreator/preferences/data/CodeStyleSection.java
  src/main/java/net/mcreator/preferences/data/PreferencesData.java
Labels: new feature
