Repository MCreator/MCreator, pull requests merged in 2025-10, with the labels that each got.

#5797 Better network sync
  plugins/generator-1.21.1/neoforge-1.21.1/templates/modbase/variableslist.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/variables/blockstate.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/variables/direction.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/variables/itemstack.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/variables/logic.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/variables/number.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/variables/string.yaml
  plugins/generator-1.21.8/neoforge-1.21.8/templates/modbase/variableslist.java.ftl
  plugins/generator-1.21.8/neoforge-1.21.8/variables/blockstate.yaml
  plugins/generator-1.21.8/neoforge-1.21.8/variables/direction.yaml
  plugins/generator-1.21.8/neoforge-1.21.8/variables/itemstack.yaml
  plugins/generator-1.21.8/neoforge-1.21.8/variables/logic.yaml
  plugins/generator-1.21.8/neoforge-1.21.8/variables/number.yaml
  plugins/generator-1.21.8/neoforge-1.21.8/variables/string.yaml
Labels: community review

#5800 Added option to make blocks/plants strippable
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/block.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/plant/plant.java.ftl
  plugins/generator-1.21.8/neoforge-1.21.8/templates/block/block.java.ftl
  plugins/generator-1.21.8/neoforge-1.21.8/templates/plant/plant.java.ftl
  plugins/mcreator-localization/help/default/block/stripping_result.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Block.java
  src/main/java/net/mcreator/element/types/Plant.java
  src/main/java/net/mcreator/ui/modgui/BlockGUI.java
  src/main/java/net/mcreator/ui/modgui/PlantGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: community review, new feature

#5817 Generate stripped logs with woodpack
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/dialogs/tools/WoodPackMakerTool.java
Labels: new feature
