Repository MCreator/MCreator, pull requests merged in 2025-03, with the labels that each got.

#5383 Fix duplicate titles of debug panel sections
  src/main/java/net/mcreator/ui/debug/DebugPanel.java
Labels: bug

#5382 Fix "Debug client" action icon
  plugins/mcreator-themes/themes/default_dark/images/16px/debugclient.svg
Labels: bug

#5407 Fix some image-related issues
  src/main/java/net/mcreator/ui/dialogs/imageeditor/NewImageDialog.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/ResizeCanvasDialog.java
  src/main/java/net/mcreator/ui/dialogs/imageeditor/ResizeDialog.java
  src/main/java/net/mcreator/ui/views/AnimationMakerView.java
  src/main/java/net/mcreator/ui/views/editor/image/tool/tools/StampTool.java
Labels: bug

#5404 Fix #5408 - Ridable living entity player control was not working
  plugins/generator-1.21.4/neoforge-1.21.4/templates/livingentity/livingentity.java.ftl
Labels: community review, bug

#5411 Fix #5409 - ME preview icons did not update correctly in some rare cases
  src/main/java/net/mcreator/ui/modgui/ModElementGUI.java
  src/main/java/net/mcreator/workspace/elements/ModElementManager.java
Labels: bug

#5396 2025.2 kick-off
  .github/workflows/deploy.yml
  .github/workflows/documentation.yml
  .github/workflows/test.yml
  build.gradle
  platform/setup.gradle
  src/main/resources/mcreator.conf
  src/test/resources/workspaces/test-2025.1.zip
Labels: official

#5429 2025.2 splash screen
  src/main/java/net/mcreator/ui/workspace/selector/WorkspaceSelector.java
  src/main/resources/net/mcreator/ui/res/splash.png
Labels: official

#5390 Fix #5388 - Big projectile hitboxes not working with block collisions
  plugins/generator-1.21.1/neoforge-1.21.1/templates/projectile/projectile.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/projectile/projectile.java.ftl
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: bug

#5424 Disabling armor parts with custom model caused build errors
  plugins/generator-1.21.1/neoforge-1.21.1/templates/armor.java.ftl
Labels: bug

#5426 Procedure external trigger dependency check did not work in some cases
  src/main/java/net/mcreator/ui/modgui/ProcedureGUI.java
Labels: bug
