Repository MCreator/MCreator, pull requests merged in 2025-06, with the labels that each got.

#5362 Added Item Java Models Support
  plugins/generator-1.21.1/neoforge-1.21.1/item.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/item/item.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/item/item_renderer.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/json/item.json.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/item.definition.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/templates/item/item_renderer.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/json/item.json.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/json/model_item.json.ftl
  plugins/mcreator-localization/help/default/item/model.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/Item.java
  src/main/java/net/mcreator/ui/minecraft/states/item/JItemStatesListEntry.java
  src/main/java/net/mcreator/ui/modgui/ItemGUI.java
Labels: community review, new feature

#5480 Added vibration sensitivity to Livingentity ME
  plugins/generator-1.21.1/neoforge-1.21.1/livingentity.definition.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/templates/livingentity/livingentity.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/livingentity.definition.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/templates/livingentity/livingentity.java.ftl
  plugins/mcreator-localization/help/default/entity/on_received_vibration.md
  plugins/mcreator-localization/help/default/entity/receive_vibration_condition.md
  plugins/mcreator-localization/help/default/entity/sensitive_to_vibration.md
  plugins/mcreator-localization/help/default/entity/vibration_sensitivity_radius.md
  plugins/mcreator-localization/help/default/entity/vibrational_events.md
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/element/types/LivingEntity.java
  src/main/java/net/mcreator/ui/modgui/LivingEntityGUI.java
  src/test/java/net/mcreator/integration/TestWorkspaceDataProvider.java
Labels: new feature

#5533 Default configuredfeature mapping
  plugins/generator-1.21.1/datapack-1.21.1/mappings/configuredfeatures.yaml
  plugins/generator-1.21.4/datapack-1.21.4/mappings/configuredfeatures.yaml
Labels: bug

#5539 Fix #5529 - With newer versions of NeoForge, hoppers ignored the take restriction of custom blocks with inventory
  plugins/generator-1.21.1/neoforge-1.21.1/templates/block/blockentity.java.ftl
  plugins/generator-1.21.1/neoforge-1.21.1/templates/elementinits/blockentities.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/block/blockentity.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/templates/elementinits/blockentities.java.ftl
Labels: bug

#5538 [Bugfix] new value check and parameter value case
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/_event_parameter_set.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/procedures/_event_parameter_set.java.ftl
  src/main/java/net/mcreator/blockly/java/blocks/EventParameterSetBlock.java
Labels: bug

#5536 [Event Parameters] Add some parameters
  plugins/generator-1.21.1/neoforge-1.21.1/mappings/eventparameters.yaml
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/_event_parameter_set.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/mappings/eventparameters.yaml
  plugins/generator-1.21.4/neoforge-1.21.4/procedures/_event_parameter_set.java.ftl
  plugins/mcreator-core/datalists/eventparameters.yaml
Labels: community review

#5543 Fix procedure code optimizer failing with consecutive comments
  src/main/java/net/mcreator/blockly/java/ProcedureCodeOptimizer.java
  src/main/java/net/mcreator/java/JavaMemberExtractor.java
Labels: bug

#5532 Shortcut to add recipe unlocking items
  plugins/mcreator-localization/lang/texts.properties
  src/main/java/net/mcreator/ui/component/JItemListField.java
  src/main/java/net/mcreator/ui/minecraft/MCItemHolder.java
  src/main/java/net/mcreator/ui/minecraft/recipemakers/AbstractRecipeMaker.java
  src/main/java/net/mcreator/ui/minecraft/recipemakers/BlastFurnaceRecipeMaker.java
  src/main/java/net/mcreator/ui/minecraft/recipemakers/BrewingRecipeMaker.java
  src/main/java/net/mcreator/ui/minecraft/recipemakers/CampfireCookingRecipeMaker.java
  src/main/java/net/mcreator/ui/minecraft/recipemakers/CraftingRecipeMaker.java
  src/main/java/net/mcreator/ui/minecraft/recipemakers/SmeltingRecipeMaker.java
  src/main/java/net/mcreator/ui/minecraft/recipemakers/SmithingRecipeMaker.java
  src/main/java/net/mcreator/ui/minecraft/recipemakers/SmokerRecipeMaker.java
  src/main/java/net/mcreator/ui/minecraft/recipemakers/StoneCutterRecipeMaker.java
  src/main/java/net/mcreator/ui/modgui/RecipeGUI.java
Labels: new feature

#5498 Added a new procedure block to spawn entity and get its reference
  plugins/generator-1.21.1/neoforge-1.21.1/procedures/spawn_entity_get.java.ftl
  plugins/generator-1.21.4/neoforge-1.21.4/procedures/spawn_entity_get.java.ftl
  plugins/mcreator-core/procedures/spawn_entity_get.json
  plugins/mcreator-localization/lang/texts.properties
Labels: community review, new feature
